// PC-side baker: renders every item sprite exactly like the old in-game code did, and writes source/itemrom.h (const data for ROM).
// Built and run by tools/bake_items.sh. Needs only a plain C compiler (gcc / clang / tcc).
#include <stdio.h>
#include <stdint.h>
typedef uint8_t u8; typedef uint16_t u16; typedef uint32_t u32;
#define RGB(r,g,b) ((u16)((r)|((g)<<5)|((b)<<10)))
static inline u16 shade(u16 c,int n){ int r=c&31,g=(c>>5)&31,b=(c>>10)&31; return RGB(r*n/16,g*n/16,b*n/16); }   // identical to main.c
#include "../source/itembake.h"
int main(int argc,char**argv){
    const char*out=argc>1?argv[1]:"itemrom.h"; FILE*f=fopen(out,"w"); if(!f){ perror(out); return 1; }
    bakeAll();
    fprintf(f,"// itemrom.h - GENERATED by tools/bake_items.sh (tools/bake_items.c + source/itembake.h). Do not edit.\n");
    fprintf(f,"// %d item sprites of %dx%d RGB555 (0x%04X = see-through), stored in ROM so they use no RAM.\n",NIV,IW,IH,IKEY);
    fprintf(f,"static const u16 romSpr[%d][%d] __attribute__((aligned(4)))={\n",NIV,IW*IH);
    for(int k=0;k<NIV;k++){ fprintf(f,"{"); const u16*p=&bakeBuf[k][0][0];
        for(int i=0;i<IW*IH;i++){ fprintf(f,"%s0x%X",i?(i%IW?",":",\n"):"",p[i]); } fprintf(f,"},\n"); }
    fprintf(f,"};\n");
    // the first opaque column and one past the last, per sprite row (blitItem skips the see-through margins): a ROM table, so it uses no RAM
    fprintf(f,"static const u8 itemSpan[%d][%d][2]={\n",NIV,IH);
    for(int k=0;k<NIV;k++){ fprintf(f,"{"); for(int j=0;j<IH;j++){ const u16*s=&bakeBuf[k][j][0]; int a=IW,b=0;
            for(int i=0;i<IW;i++) if(s[i]!=IKEY){ if(i<a) a=i; b=i+1; }
            if(a>=b) a=b=0;
            fprintf(f,"%s{%d,%d}",j?",":"",a,b); } fprintf(f,"},\n"); }
    fprintf(f,"};\n"); fclose(f); return 0;
}
