#!/usr/bin/env python3
"""Voice clips -> tiny 4-bit IMA-ADPCM blobs (6554 Hz mono, same format as encode_sfx.py) + source/voices.h.
usage (from the project root): python3 tools/encode_voices.py [tools/voices_src]
Every tools/voices_src/<name>.wav becomes source/sfx/v_<slug>.adp; source/voices.h lists them all.
To add a clip: drop a (cleaned, trimmed, mono) .wav in tools/voices_src, run this, then call voxPlay(V_<slug>) where it should sound."""
import sys, os, re, glob, wave
import numpy as np
from scipy.signal import resample_poly, butter, sosfilt
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from encode_sfx import encode, decode, RATE

src = sys.argv[1] if len(sys.argv) > 1 else "tools/voices_src"
os.makedirs("source/sfx", exist_ok=True)
slugs, total = [], 0
for f in sorted(glob.glob(src + "/*.wav"), key=lambda p: os.path.basename(p).lower()):
    slug = re.sub(r"[^a-z0-9]+", "_", os.path.splitext(os.path.basename(f))[0].lower()).strip("_")
    w = wave.open(f); sr = w.getframerate(); x = np.frombuffer(w.readframes(w.getnframes()), dtype="<i2").astype(np.float64)
    if w.getnchannels() == 2: x = x.reshape(-1, 2).mean(1)
    from math import gcd
    g = gcd(RATE, sr); x = resample_poly(x, RATE // g, sr // g)
    x = sosfilt(butter(4, 3000, "lp", fs=RATE, output="sos"), x)
    x = np.round(np.clip(x, -32768, 32767)).astype(np.int32)
    b = encode(x); open(f"source/sfx/v_{slug}.adp", "wb").write(b); total += len(b)
    y = decode(b); snr = 10 * np.log10(np.sum(x.astype(float) ** 2) / max(1, np.sum((x - y).astype(float) ** 2)))
    print(f"v_{slug}: {len(x)/RATE:.2f}s {len(b)} bytes SNR {snr:.1f} dB"); slugs.append(slug)

L = " \\\n".join(f"    X({s})" for s in slugs)
with open("source/voices.h", "w") as h:
    h.write(f"""// voices.h - GENERATED by tools/encode_voices.py (do not edit by hand): the {len(slugs)} voice clips of the Sim you control.
// Each is source/sfx/v_<name>.adp (4-bit IMA-ADPCM, 6554 Hz, the same blobs the effect voice already plays), baked into the ROM here.
// They sit after the old effects in sfxTab: sound id = SFX_VOICE0 + V_<name>. Play one with voxPlay(V_<name>) (main.c); who plays what is in voxEvent
// (sims events) and voxSoc (house.h, socials), plus a few spots in main.c (falls, bails, fights, needs).
#ifndef VOICES_H
#define VOICES_H
#define VOICE_LIST(X) \\
{L}
#define VX_ASM(n) ".global v_" #n "\\nv_" #n ":\\n.incbin \\"source/sfx/v_" #n ".adp\\"\\n.balign 4\\n"
__asm__(".pushsection .rodata\\n.balign 4\\n" VOICE_LIST(VX_ASM) ".popsection\\n");
#define VX_EXT(n) extern const u8 v_##n[];
VOICE_LIST(VX_EXT)
#define VX_ENUM(n) V_##n,
enum {{ VOICE_LIST(VX_ENUM) VOICE_N }};
#define VX_TAB(n) v_##n,
#define VOICE_TAB VOICE_LIST(VX_TAB)
static signed char vxQ[2]; static int vxQn;   // clips waiting for the current one to end (voxChain)
#endif
""")
print("total", total, "bytes,", len(slugs), "clips")
