// Host tool: bakes the pre-sampled floor tiles (flTab) into source/fltab.h so they live in ROM, not EWRAM.
// Build + run:  gcc -O1 -o /tmp/gen_fltab tools/gen_fltab.c && /tmp/gen_fltab > source/fltab.h
// Uses the very same maths as bakeTex() in main.c. Re-run it if you change a floor texture (flTex / flVs), CA, or the diamond shape.
#include <stdio.h>
#include <stdint.h>
typedef uint8_t u8; typedef uint16_t u16; typedef uint32_t u32;
#define CA 8
#define CB (CA/2)
#define NFL 14
#define RGB(r,g,b) ((u16)((r)|((g)<<5)|((b)<<10)))
static u16 shade(u16 c,int n){ int r=c&31,g=(c>>5)&31,b=(c>>10)&31; return RGB(r*n/16,g*n/16,b*n/16); }
typedef struct { const char*nm; u16 c[4]; const char*p[8]; } Tex;
#define PN_FLAT  "00000000","00000000","00000000","00000000","00000000","00000000","00000000","00000000"
#define PN_NOISE "01000200","00020010","20001000","00100020","01000100","00200001","10002000","00010200"
#define PN_CONC  "00000100","02000000","00001000","00000020","00100000","00000002","20000000","00020100"
#define PN_TILE  "11111111","12001200","10001000","10001000","11111111","12001200","10001000","10001000"
#define PN_STEEL "00000000","01110000","00220000","00000000","00000000","00000111","00000022","00000000"
static const Tex flTex[NFL]={
 {"TAN CHECK",{RGB(26,21,14),0,0,0},{PN_FLAT}},
 {"BEIGE CARPET",{RGB(24,21,16),RGB(21,18,13),RGB(27,24,19),0},{PN_NOISE}},
 {"TEAL CARPET",{RGB(6,16,16),RGB(4,12,13),RGB(8,19,19),0},{PN_NOISE}},
 {"CHECKER LINO",{RGB(29,29,28),RGB(5,5,8),0,0},{"00001111","00001111","00001111","00001111","11110000","11110000","11110000","11110000"}},
 {"WOOD PLANKS",{RGB(20,13,6),RGB(12,7,3),RGB(23,16,8),0},{"11111111","10020000","10000200","10002000","11111111","02001000","00201000","00001002"}},
 {"PINK TILE",{RGB(28,18,20),RGB(30,28,27),RGB(30,22,23),0},{PN_TILE}},
 {"BLUE TILE",{RGB(9,19,26),RGB(28,29,30),RGB(14,24,29),0},{PN_TILE}},
 {"CONCRETE",{RGB(15,15,14),RGB(18,18,17),RGB(12,12,11),0},{PN_CONC}},
 {"STEEL PLATE",{RGB(12,14,16),RGB(20,22,24),RGB(7,8,10),0},{PN_STEEL}},
 {"METAL GRATE",{RGB(4,5,7),RGB(17,18,20),RGB(10,11,13),0},{"11111111","10001000","10201020","10001000","11111111","10001000","10201020","10001000"}},
 {"HAZARD",{RGB(30,25,2),RGB(4,4,5),0,0},{"00000000","00000000","11111111","11111111","00000000","00000000","11111111","11111111"}},
 {"GREEN LINO",{RGB(12,19,10),RGB(14,22,12),RGB(10,16,8),0},{PN_NOISE}},
 {"OIL STAINED",{RGB(14,14,13),RGB(8,8,9),RGB(11,11,11),0},{"00000000","00022000","00211200","00022100","00002000","00000000","00000000","00000000"}},
 {"RED TILE",{RGB(22,8,5),RGB(14,6,4),RGB(25,11,7),0},{PN_TILE}},
};
static const u8 flVs[NFL]={14,15,15,16,14,15,15,15,15,15,15,15,15,15};   // shade (of 16) for the odd tiles of a checkerboard of tiles
static const u8 rTab0=CA;
static u16 tab[NFL][2][2*CB+1][2*CA+1];
int main(void){
    u8 hhT0[CA+1]; for(int at=0;at<=CA;at++) hhT0[at]=(u8)((rTab0/2)*(rTab0-at)/rTab0);
    for(int fl=0;fl<NFL;fl++){
        const Tex*t=&flTex[fl]; int vs=flVs[fl];
        for(int var=0;var<2;var++)for(int tt=-CA;tt<=CA;tt++){
            int hh=hhT0[tt<0?-tt:tt];
            for(int y=-hh;y<=hh;y++){
                int X=tt*CB+y*CA+CA*CB, Y=y*CA-tt*CB+CA*CB;
                int ta=X*8/(2*CA*CB), tb=Y*8/(2*CA*CB);
                if(ta<0)ta=0;
                if(ta>7)ta=7;
                if(tb<0)tb=0;
                if(tb>7)tb=7;
                u16 c=t->c[t->p[tb][ta]-'0']; if(var) c=shade(c,vs);
                tab[fl][var][y+CB][tt+CA]=c;
            }
        }
    }
    printf("// fltab.h - GENERATED by tools/gen_fltab.c (do not edit). The floor tiles pre-sampled onto the iso diamond: [floor][odd tile][row][column].\n");
    printf("// They live in ROM (const) instead of an 8.5 KB EWRAM buffer filled at start-up. Re-run the tool if a floor texture or CA changes.\n");
    printf("static const u16 flTab[NFL][2][2*CB+1][2*CA+1]={\n");
    for(int f=0;f<NFL;f++){ printf("{"); for(int v=0;v<2;v++){ printf("{"); for(int r=0;r<2*CB+1;r++){ printf("{"); for(int c=0;c<2*CA+1;c++) printf("%u%s",tab[f][v][r][c],c<2*CA?",":""); printf("}%s",r<2*CB?",":""); } printf("}%s",v<1?",":""); } printf("}%s\n",f<NFL-1?",":""); }
    printf("};\n");
    return 0; }
