#!/usr/bin/env python3
"""Bakes tables the game used to work out at every power-on into source/bakedtabs.h, so they live in ROM instead of RAM.
usage:  python3 tools/gen_bakedtabs.py          (from the project root; re-run when a wallpaper in source/main.c (wpTex) changes)

  wpTab[NWP][2][8][8]  the wallpapers pre-shaded for the left (12/16) and right (9/16) wall faces     3584 bytes of EWRAM before
  wpHi / wpLo          per column: the lit row under the top edge, the shaded row above the bottom     896 bytes of IWRAM before
  wpAvg[NWP]           each wallpaper's average colour                                                  28 bytes of IWRAM before
  scKnee[2][1024]      the mixers' soft-limit curve                                                   2048 bytes of EWRAM before
  acSin, acHue         the main menu's acid rainbow: a parabola sine and the colour wheel                512 bytes of EWRAM before
The maths is the game's own (shade / lite / avgTex / bakeTex / scInit / acidInit); the wallpapers are read out of source/main.c itself."""
import re, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'source', 'main.c')).read()

def RGB(r, g, b): return r | (g << 5) | (b << 10)
def shade(c, n): r, g, b = c & 31, (c >> 5) & 31, (c >> 10) & 31; return RGB(r * n // 16, g * n // 16, b * n // 16)
def lite(c, n):
    r, g, b = (c & 31) * n // 16, ((c >> 5) & 31) * n // 16, ((c >> 10) & 31) * n // 16
    return RGB(min(r, 31), min(g, 31), min(b, 31))
def cdiv(a, b):   # C integer division (truncates toward zero)
    q = abs(a) // abs(b); return q if (a >= 0) == (b > 0) else -q

# ---- the wallpapers, as main.c defines them ----
pn = {m.group(1): re.findall(r'"([0-3]{8})"', m.group(2)) for m in re.finditer(r'#define (PN_\w+)\s+(.*)', src)}
blk = src[src.index('static const Tex wpTex[NWP]={'):]; blk = blk[:blk.index('};')]
NWP = int(re.search(r'#define NWP (\d+)', src).group(1))
wp = []
for m in re.finditer(r'\{"([^"]+)",\{([^}]*)\},\{([^}]*)\}\}', blk):
    cols = [eval(c.strip().replace('RGB', 'RGB')) if c.strip() != '0' else 0 for c in re.split(r',(?![^()]*\))', m.group(2))]
    pat = m.group(3).strip()
    rows = pn[pat] if pat in pn else re.findall(r'"([0-3]{8})"', pat)
    assert len(cols) == 4 and len(rows) == 8, m.group(1)
    wp.append((m.group(1), cols, rows))
assert len(wp) == NWP, (len(wp), NWP)

def avg(cols, rows):
    r = g = b = 0
    for v in range(8):
        for u in range(8):
            c = cols[int(rows[v][u])]; r += c & 31; g += (c >> 5) & 31; b += (c >> 10) & 31
    return RGB(r // 64, g // 64, b // 64)

tab = [[[[shade(cols[int(rows[v][u])], 9 if f else 12) for v in range(8)] for u in range(8)] for f in range(2)] for _, cols, rows in wp]
hi = [[[lite(tab[w][f][u][1], 19) for u in range(8)] for f in range(2)] for w in range(NWP)]
lo = [[[shade(tab[w][f][u][6], 13) for u in range(8)] for f in range(2)] for w in range(NWP)]
av = [avg(cols, rows) for _, cols, rows in wp]
knee = [[d * 31 // (d + 31) for d in range(1024)], [d * 32 // (d + 32) for d in range(1024)]]
asin = []
for i in range(256):
    x = i & 127; v = (x * (128 - x)) >> 5; v = min(v, 127); asin.append(v if i < 128 else -v)
ahue = []
for i in range(128):
    p = i * 12; seg = p >> 8; f = (p & 255) >> 3; up, dn = f, 31 - f
    r, g, b = [(31, up, 0), (dn, 31, 0), (0, 31, up), (0, dn, 31), (up, 0, 31)][seg] if seg < 5 else (31, 0, dn)
    ahue.append(RGB(r, g, b))

def arr(v):
    if isinstance(v[0], list): return '{' + ','.join(arr(x) for x in v) + '}'
    return '{' + ','.join(str(x) for x in v) + '}'
out = ['// bakedtabs.h - GENERATED by tools/gen_bakedtabs.py (do not edit): tables the game used to build in RAM at power-on, now in ROM.',
       '// Re-run the tool when a wallpaper (wpTex in main.c) changes. Needs u8 / u16 and NWP before it.',
       '_Static_assert(NWP==%d,"bakedtabs.h: re-run tools/gen_bakedtabs.py");' % NWP,
       'static const u16 wpTab[NWP][2][8][8]=%s;' % arr(tab),
       'static const u16 wpHi[NWP][2][8]=%s;' % arr(hi),
       'static const u16 wpLo[NWP][2][8]=%s;' % arr(lo),
       'static const u16 wpAvg[NWP]=%s;' % arr(av),
       'static const u8 scKnee[2][1024]=%s;' % arr(knee),
       'static const signed char acSin[256]=%s;' % arr(asin),
       'static const u16 acHue[128]=%s;' % arr(ahue), '']
open(os.path.join(ROOT, 'source', 'bakedtabs.h'), 'w').write('\n'.join(out))
print('wrote source/bakedtabs.h: %d wallpapers' % NWP)
