#!/usr/bin/env python3
"""Turns a folder of Sims 2 wallpaper .package files into source/wallart.h: one 8 x WALL_H texture per wallpaper (one tile of wall, full height),
pre-shaded for the two wall faces the camera sees, baked into the ROM (no RAM used), plus a name and an average colour for each.

usage:  python3 tools/make_wallpapers.py FOLDER_WITH_PACKAGES        (run from the project root; needs numpy + Pillow)
Also writes assets/preview/wallpapers.png (every texture, enlarged).
The textures in the default build come from the "KHLVH wallpaper" set (ModTheSims, by KHLVH, 2005): see the README credits."""
import sys, os, glob, re
import numpy as np
from PIL import Image
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sims2tex

WALL_H = 24                      # must match WALL_H in source/main.c
SHADE = (12, 9)                  # face 0 (wall running along x, seen from +y) and face 1 (along y): the same shades as the old wall blocks
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ")
DROP = {"WALL", "WALLS", "WALLPAPER", "PAPER", "TREATMENT", "COVER", "COVERING", "PANEL", "PANELS", "FINISH", "BY", "MAGICOINC", "INC"}

def nice(fn):   # "PineappleRepublicWallTreatment-KHLVH06162005.package" -> "PINEAPPLE REPUBLIC"
    b = os.path.basename(fn).rsplit('.', 1)[0]; b = re.sub(r'-?KHLVH-?\d*', '', b); b = re.sub(r'\d{8}$', '', b)
    words = re.findall(r'[A-Z]+(?![a-z])|[A-Z]?[a-z]+|\d+', b.replace('#', ' '))
    w = [x.upper() for x in words if x.upper() not in DROP] or [x.upper() for x in words]
    s = '';
    for x in w:
        if len(s) + len(x) + (1 if s else 0) > 14: break
        s += (' ' if s else '') + x
    return ''.join(c for c in s if c in FONT) or 'WALL'

def to15(rgb): r, g, b = [(int(v) * 31 + 127) // 255 for v in rgb]; return r | (g << 5) | (b << 10)
def shade(c, n): return ((c & 31) * n // 16) | ((((c >> 5) & 31) * n // 16) << 5) | ((((c >> 10) & 31) * n // 16) << 10)

def main(folder):
    fs = sorted(glob.glob(os.path.join(folder, '*.package')), key=lambda f: nice(f))
    tex, names, avg, prev = [], [], [], []
    for f in fs:
        t = sims2tex.textures(f)
        if not t: print('skip (no texture):', f); continue
        img = Image.fromarray(t[0][1])
        small = np.asarray(img.resize((8, WALL_H), Image.LANCZOS)).astype(int)    # one tile wide, full wall height
        small = np.clip((small - 128) * 1.08 + 128 + 6, 0, 255)                   # a touch of contrast and light: the GBA screen is dark
        c15 = [[to15(small[y, x]) for y in range(WALL_H)] for x in range(8)]       # [column][row]
        tex.append(c15); names.append(nice(f)); avg.append(to15(small.reshape(-1, 3).mean(0)))
        prev.append(Image.fromarray(small.astype(np.uint8)).resize((32, WALL_H * 4), Image.NEAREST))
    n = len(tex)
    out = ["// GENERATED by tools/make_wallpapers.py from the KHLVH Sims 2 wallpaper set (ModTheSims, by KHLVH): edit the tool, not this file.",
           "// %d wallpapers, each one tile of wall (8 columns) by WALL_H rows, pre-shaded for the two faces the camera sees. All in ROM." % n,
           "#define NWX %d" % n,
           "static const char* const wxName[NWX]={" + ",".join('"%s"' % s for s in names) + "};",
           "static const u16 wxAvg[NWX]={" + ",".join(str(a) for a in avg) + "};",
           "static const u16 wxTex[NWX][2][8][%d]={" % WALL_H]
    for t in tex:
        faces = []
        for sh in SHADE: faces.append("{" + ",".join("{" + ",".join(str(shade(c, sh)) for c in col) + "}" for col in t) + "}")
        out.append("{" + ",".join(faces) + "},")
    out.append("};")
    open(os.path.join(ROOT, 'source', 'wallart.h'), 'w').write("\n".join(out) + "\n")
    cols = 16; rows = (n + cols - 1) // cols; sheet = Image.new('RGB', (cols * 36, rows * (WALL_H * 4 + 4)), (20, 20, 30))
    for i, p in enumerate(prev): sheet.paste(p, ((i % cols) * 36 + 2, (i // cols) * (WALL_H * 4 + 4) + 2))
    os.makedirs(os.path.join(ROOT, 'assets', 'preview'), exist_ok=True); sheet.save(os.path.join(ROOT, 'assets', 'preview', 'wallpapers.png'))
    print('wrote source/wallart.h: %d wallpapers, %d KB of ROM' % (n, n * 2 * 8 * WALL_H * 2 // 1024))

if __name__ == '__main__': main(sys.argv[1] if len(sys.argv) > 1 else 'assets/wallpapers')
