#!/usr/bin/env python3
"""The CUTSCENE CAPTION font: one size between the game's small (5 px capitals) and medium (10 px) text, 7 px capitals,
ASCII only (the captions are plain English). Rasterised from DejaVu Sans Bold with the same 9 coverage steps the game
blends with. Writes source/csfont.h (fo_c fw_c fa_c fp_c, glyphs in FNT_CHARS order; cutscene.h's csText draws it).
usage: python3 tools/make_csfont.py [font.ttf]"""
import os, sys
from PIL import Image, ImageDraw, ImageFont
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TTF = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
CAP, BELOW, GAP, SPACE, LEVELS = 7, 3, 1, 3, 8
src = open(os.path.join(ROOT, "source/fontdata.h")).read()
i = src.index('#define FNT_CHARS "') + len('#define FNT_CHARS "'); j = src.index('"\n', i)
chars = src[i:j].encode().decode("unicode_escape")
def fit():
    s = 4.0
    while s < 40:
        f = ImageFont.truetype(TTF, s); bb = f.getbbox("H")
        if bb[3] - bb[1] == CAP: return f
        s += 0.25
    sys.exit("no size gives %d px capitals" % CAP)
font = fit(); H = CAP + BELOW
gl = []
for ch in chars:
    im = Image.new("L", (CAP * 3 + 16, H), 0)
    ImageDraw.Draw(im).text((4, CAP), ch, font=font, fill=255, anchor="ls")
    bb = im.getbbox(); im = im.crop((bb[0], 0, bb[2], H)) if bb else Image.new("L", (1, H), 0)
    gl.append(im)
dw = max(gl[chars.index(d)].width for d in "0123456789")
offs, ws, adv, data = [], [], [], []
for ch, g in zip(chars, gl):
    if ch in "0123456789": c = Image.new("L", (dw, H), 0); c.paste(g, ((dw - g.width) // 2, 0)); g = c
    offs.append(len(data)); ws.append(g.width); adv.append(g.width + GAP)
    for y in range(H):
        for x in range(g.width): data.append(round(g.getpixel((x, y)) * LEVELS / 255))
def arr(t, n, a, per=32):
    rows = [",".join(map(str, a[k:k+per])) for k in range(0, len(a), per)]
    return "static const %s %s[%d]={\n%s};\n" % (t, n, len(a), ",\n".join(rows))
out = ["// GENERATED by tools/make_csfont.py - the cutscene caption font: %d px capitals, cell %d rows, ASCII in FNT_CHARS order.\n" % (CAP, H),
       arr("u16", "fo_c", offs, 16), arr("u8", "fw_c", ws), arr("u8", "fa_c", adv), arr("u8", "fp_c", data, 48),
       "#define FH_c %d\n#define FSP_c %d\n" % (H, SPACE)]
open(os.path.join(ROOT, "source/csfont.h"), "w").write("".join(out))
print("csfont.h:", len(data), "glyph bytes,", len(chars), "glyphs, avg advance %.1f" % (sum(adv) / len(adv)))
