#!/usr/bin/env python3
# make_decor_items.py - writes source/decorart.h: the LIVING AND DECOR pack (rug, dining table, chair, desk, floor lamp, houseplant,
# dresser, fireplace, kitchen counter). Same box + texture format as homeart.h (see itembake.h). Edit the art here, then run:
#   python3 tools/make_decor_items.py && sh tools/bake_items.sh
import os
out=['// decorart.h - GENERATED by tools/make_decor_items.py (LIVING AND DECOR pack). HOST-ONLY, included from itembake.h. Edit the script, not this file.']
def pal(nm,cols): out.append('static const u16 %s[%d]={%s};'%(nm,len(cols),','.join('RGB(%d,%d,%d)'%c for c in cols)))
def mat(nm,p,rows):
    w=len(rows[0]); assert all(len(r)==w for r in rows),(nm,rows)
    out.append('MAT(%s,%s,%d,%d,%s)'%(nm,p,w,len(rows),','.join('"%s"'%r for r in rows)))
def box(nm,bx):
    out.append('static const IBox %s[%d]={'%(nm,len(bx))+','.join('{%d,%d,%d,%d,%d,%d,{%s}}'%(b[:6]+(','.join('&'+m for m in b[6]),)) for b in bx)+'};')
def S(nm,p,c): mat(nm,p,[c])   # a plain colour

# rug: red with a gold border pattern, flat on the floor
pal('pDpRg',[(12,3,4),(23,7,8),(29,22,12)])
S('mDRgSide','pDpRg','a')
mat('mDRgTop','pDpRg',['aaaaaaaa','abbbbbba','abcbbcba','abbccbba','abbccbba','abcbbcba','abbbbbba','aaaaaaaa'])
box('bxDRug',[(0,0,8,8,0,1,['mDRgSide']*4+['mDRgTop'])])

# dining table: four legs, a wooden top
pal('pDpTb',[(8,4,2),(21,13,6),(27,19,10)])
S('mDTbLeg','pDpTb','a'); S('mDTbEdge','pDpTb','b')
mat('mDTbTop','pDpTb',['aaaaaaaa','abbbbbba','abccccba','abbbbbba','abccccba','abbbbbba','abbbbbba','aaaaaaaa'])
box('bxDTable',[(0,1,1,2,0,6,['mDTbLeg']*5),(7,1,8,2,0,6,['mDTbLeg']*5),(0,6,1,7,0,6,['mDTbLeg']*5),(7,6,8,7,0,6,['mDTbLeg']*5),
               (0,1,8,7,6,8,['mDTbEdge']*4+['mDTbTop'])])

# chair: legs, a red cushion, a tall back (the back is at the rear, the seat faces the open floor like the sofa)
pal('pDpCh',[(8,4,2),(20,12,6),(27,6,6),(30,13,11)])
S('mDChLeg','pDpCh','a'); S('mDChWood','pDpCh','b'); S('mDChSeat','pDpCh','c')
mat('mDChSeatT','pDpCh',['cccccc','cdcccc','cccccc','cccccc','ccccdc','cccccc'])
mat('mDChBackF','pDpCh',['bbbbbb','bcccdb','bccccb','bcccdb','bbbbbb','bbbbbb','bbbbbb'])
box('bxDChair',[(1,2,2,3,0,3,['mDChLeg']*5),(6,2,7,3,0,3,['mDChLeg']*5),(1,6,2,7,0,3,['mDChLeg']*5),(6,6,7,7,0,3,['mDChLeg']*5),
               (1,2,7,7,3,5,['mDChSeat']*4+['mDChSeatT']),(1,2,7,3,5,12,['mDChWood','mDChWood','mDChBackF','mDChWood','mDChWood'])])

# desk: a drawer unit, a leg, a top, and a computer with a blue screen facing the open floor
pal('pDpDk',[(8,5,3),(20,13,7),(27,20,11),(5,5,8),(9,22,31),(22,27,31),(14,15,18)])
S('mDDkWood','pDpDk','b'); S('mDDkCase','pDpDk','d'); S('mDDkKeyS','pDpDk','g')
mat('mDDkTop','pDpDk',['aaaaaaaa','abbbbbba','abccccba','abbbbbba','abccccba','abbbbbba','abbbbbba','aaaaaaaa'])
mat('mDDkDraw','pDpDk',['aaa','abb','aab','aaa','abb'][:3]+['abb','aab'][:0])
mat('mDDkMon','pDpDk',['dddddd','deeeed','deffed','deeeed','deeeed','dddddd'])
mat('mDDkMonT','pDpDk',['dddddd','dgggdd'])
mat('mDDkKey','pDpDk',['gggggg','gdgdgd'])
box('bxDDesk',[(0,1,8,7,5,7,['mDDkWood']*4+['mDDkTop']),(0,1,3,7,0,5,['mDDkDraw','mDDkWood','mDDkWood','mDDkWood','mDDkWood']),(7,1,8,7,0,5,['mDDkWood']*5),
              (2,2,6,3,7,12,['mDDkMon','mDDkCase','mDDkCase','mDDkCase','mDDkMonT']),(3,2,5,4,7,8,['mDDkCase']*5),(2,4,6,6,7,8,['mDDkKey']*4+['mDDkKeyS'])])

# floor lamp: a dark base, a thin pole, a glowing yellow shade
pal('pDpLp',[(5,5,8),(12,12,15),(30,25,11),(31,31,23)])
S('mDLpBase','pDpLp','b'); S('mDLpPole','pDpLp','a')
mat('mDLpSh','pDpLp',['ccccc','cdddc','cdddc','cdddc','ccccc'])
mat('mDLpShT','pDpLp',['ddddd','dcccd','dcccd','dcccd','ddddd'])
box('bxDLamp',[(2,2,6,6,0,1,['mDLpBase']*5),(4,4,5,5,1,12,['mDLpPole']*5),(2,2,6,6,12,17,['mDLpSh']*4+['mDLpShT'])])

# houseplant: a terracotta pot and two tiers of leaves
pal('pDpPl',[(13,6,3),(24,12,6),(4,13,5),(9,22,9),(15,28,14)])
mat('mDPlPot','pDpPl',['bbbb','abba','abba','aaaa'])
mat('mDPlRimT','pDpPl',['aaaa','acca','acca','aaaa'])
mat('mDPlLeaf','pDpPl',['cdcdcd','dcecdc','cdcdce','ecdcdc','dcecdc'])
mat('mDPlLeafT','pDpPl',['cdcdcdcc','dcedcdce','cdcdecdc','dcecdcdc','cdcdcdec','dcdcedcd','cecdcdcd','dcdcdced'])
mat('mDPlLeaf2','pDpPl',['dce','cdd','ecd','dcc'])
mat('mDPlLeaf2T','pDpPl',['dced','cdcd','edcd','cded'])
box('bxDPlant',[(2,2,6,6,0,5,['mDPlPot']*4+['mDPlRimT']),(1,1,7,7,5,10,['mDPlLeaf']*4+['mDPlLeafT']),(2,2,6,6,10,14,['mDPlLeaf2']*4+['mDPlLeaf2T'])])

# dresser: a wooden chest of three drawers with gold knobs
pal('pDpDz',[(8,4,2),(21,13,6),(27,19,10),(31,26,9)])
mat('mDDrF','pDpDz',['aaaaaa','abbbba','abbdba','aaaaaa','abbbba','abbdba','aaaaaa','abbbba','abbdba','aaaaaa'])
S('mDDrS','pDpDz','b')
mat('mDDrT','pDpDz',['aaaaaa','abbbba','abccba','abccba','abbbba','aaaaaa'])
box('bxDDresser',[(1,2,7,7,0,10,['mDDrF','mDDrS','mDDrS','mDDrS','mDDrT'])])

# fireplace: a brick surround with a burning opening and a wooden mantel
pal('pDpFp',[(7,3,3),(20,8,6),(14,6,5),(2,2,3),(31,19,4),(31,28,10),(22,14,7),(11,6,3)])
mat('mDFpF','pDpFp',['bcbbcbbc','bbcbbcbb','bcbbcbbc','bddddddb','bdddeddb','bddeffdb','bdeffffd','bdddddddb'[:8],'bbbbbbbb','bcbbcbbc','bbcbbcbb','bcbbcbbc'])
S('mDFpS','pDpFp','b')
mat('mDFpMantF','pDpFp',['gggggggg','hhhhhhhh'])
S('mDFpMantS','pDpFp','g')
mat('mDFpMantT','pDpFp',['gggggggg']*6)
mat('mDFpTop','pDpFp',['bbbbbb','bcbcbc','bbbbbb','bcbcbc'])
box('bxDFire',[(0,3,8,8,0,12,['mDFpF','mDFpS','mDFpS','mDFpS','mDFpS']),(0,2,8,8,12,14,['mDFpMantF','mDFpMantS','mDFpMantS','mDFpMantS','mDFpMantT']),(1,5,7,8,14,18,['mDFpS']*4+['mDFpTop'])])

# kitchen counter: cabinet doors, a steel worktop with a sink and two hobs
pal('pDpKc',[(8,8,10),(24,24,26),(16,17,20),(8,18,29),(5,5,7),(28,10,6)])
mat('mDKcF','pDpKc',['aaaaaaaa','abbbbbba','abbbbbba','abbbbbba','abbaabba','abbbbbba','abbbbbba','aaaaaaaa'])
S('mDKcS','pDpKc','b')
mat('mDKcT','pDpKc',['aaaaaaaa','accccdda','accccdda','accccdda','abbbbbba','abeeebba','abbbbbba','aaaaaaaa'])
box('bxDCounter',[(0,1,8,7,0,8,['mDKcF','mDKcS','mDKcS','mDKcS','mDKcT'])])

here=os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here,'..','source','decorart.h'),'w').write('\n'.join(out)+'\n')
print('wrote source/decorart.h')
