import sys;sys.path.insert(0,'.')
import numpy as np
from scipy import signal
from xm import parse
S=parse('/mnt/user-data/uploads/the_dipper_man_-_the_dipper_man.xm')
MIXR=18157
used=set(i for o in S['order'] for r in S['pats'][o] for n,i,v,e,ep in r if n and n<97 for i in [i])
insts=[];total=0
for k,I in enumerate(S['insts']):
    s=I['samples'][0]; x=np.array(s['data'])
    period=7680-(0+s['rel'])*64-s['fine']/2-48*64; fc4=8363*2**((4608-period)/768)
    X=np.abs(np.fft.rfft(x))**2; fr=np.fft.rfftfreq(len(x),1/fc4); ds=1
    for d in (4,2):
        if X[fr>0.4*fc4/d].sum()/X.sum()<0.004: ds=d;break
    y=signal.resample_poly(x,1,ds) if ds>1 else x.copy()
    pk=abs(y).max(); y=y/pk*0.98 if pk>0 else y   # normalise; gain folded into vol
    q=np.round(y*127).astype(int); fade=min(48,len(q)//4); q[-fade:]=(q[-fade:]*np.linspace(1,0,fade)).astype(int)
    q=np.append(q,0)   # guard sample for interpolation
    vol=int(round(s['vol']*pk))   # keep relative loudness: vol(0..64) * original peak
    vol=min(64,max(1,int(round(s['vol']/64*pk*64))))
    base=fc4/MIXR/ds
    steps=[int(round(base*2**((n-49)/12)*65536)) for n in range(1,97)]
    insts.append((q,vol,steps,ds,fc4)); total+=len(q)
    print(k+1,'ds',ds,'len',len(q),'vol',vol,'fc4 %.0f'%fc4)
print('sample bytes',total)
# patterns
ev=[];off=[]
for p in S['pats']:
    off.append(len(ev))
    for r in p:
        e=[(ch,i-1,n-1) for ch,(n,i,v,_,_) in enumerate(r) if n and n<97]
        ev.append(len(e))
        for ch,i,n in e: ev.append(ch|(i<<4)|(n<<8))
o=[]
o.append('// generated by tools/xm2gba.py from the_dipper_man.xm - do not edit\n')
o.append('#define MUS_RATE %d\n#define MUS_ROW %d\n#define MUS_RFR %d\n#define MUS_NORD %d\n#define MUS_LOOP 4\n'%(MIXR,int(0.12*MIXR),int(round((0.12*MIXR-int(0.12*MIXR))*256)),len(S['order'])))
def arr(t,nm,vals,w=24):
    o.append('static const %s %s[%d]={'%(t,nm,len(vals)))
    for j in range(0,len(vals),w): o.append(','.join(str(v) for v in vals[j:j+w])+',\n')
    o.append('};\n')
arr('u8','musOrder',S['order'],30); arr('u16','musPatOff',off); arr('u16','musEv',ev)
arr('u8','musVol',[i[1] for i in insts]); 
arr('u32','musStep',[s for i in insts for s in i[2]],8)
arr('u32','musLen',[(len(i[0])-1) for i in insts])
for k,i in enumerate(insts): arr('s8','musS%d'%k,[int(v) for v in i[0]],32)
o.append('static const s8* const musData[16]={'+','.join('musS%d'%k for k in range(16))+'};\n')
open('musicdata.h','w').write(''.join(o))
print('events u16',len(ev),'header bytes',len(''.join(o)))
