// artists.h - WHO MADE WHICH SONG, shown in the jukebox (right-aligned on the song's row and on the NOW line).
//
//   ARTIST("SONG NAME","Artist")     SONG NAME = the name exactly as it is written in source/songs.h
//
// A song with no line here simply shows no artist. Real UTF-8 works: the font (see "EXTENDED FONT" in README.md) draws punctuation, Latin-1 and
// Latin Extended-A letters with their accents (Polish, Czech, Hungarian, Romanian, Turkish, Croatian ...), ss, ae, oe, o-slash, euro, pound and more.
// Anything it still lacks falls back to the plain letter.
ARTIST("AIM AND SHOOT","Singhs")
ARTIST("AN ODE TO THE SPANISH FLEXICODE","Singhs")
ARTIST("THE MAGIC ACT","Singhs")
ARTIST("AMIGA MUSIC","DayBar")
ARTIST("HOT DAMN","DayBar")
ARTIST("HOT DAMN (ORIGINAL)","DayBar")
ARTIST("MELTDOWN IN MARS","DayBar")
ARTIST("STAGED THE FULL PERFORMANCE","DayBar")
ARTIST("EARTH AND THE SPACE CITIZENS","VaninBlack")
ARTIST("EMERGENCY ON THE DANCE FLOOR","Sk9m")
ARTIST("EMERGENCY (ORIGINAL)","Sk9m")
ARTIST("SUNMAN SUNRISE","Sk9m")
ARTIST("THE CYNICAL SYNDICATION","Sk9m")
ARTIST("CONDENSED MUSIC","Sk9m")
ARTIST("EXCUSES","Breno Orêian")
ARTIST("TREE-AGE IN ACTION","Breno Orêian")
ARTIST("TREE-AGE IN ACTION (ORIGINAL)","Breno Orêian")
ARTIST("TREE-AGE IN ACTION (FAST)","Breno Orêian")
ARTIST("TREE-AGE IN ACTION (FAST) (ORIGINAL)","Breno Orêian")
ARTIST("GOTTCHO BARRACHO","El B.D'ees")
ARTIST("GOTTCHO BARRACHO (ORIGINAL)","El B.D'ees")
ARTIST("MI CORA ZONE","El B.D'ees")
ARTIST("THE TICKING BOMB","VanInBlack")
ARTIST("MISTER QUICKBULLET","VaninBlack")
ARTIST("OVER MY VOICE","DayBar")
ARTIST("YOU'RE WINNER (ORIGINAL)","Dipper")
ARTIST("WHISTLER MAN","Danny Steele")
ARTIST("WHISTLER MAN (ORIGINAL)","Danny Steele")
ARTIST("WORTHLESS CLOUDS","The Dipper Man")
ARTIST("NURSERY TIME","Danny Steele")
ARTIST("CLOSER TO THE END","Danny Steele")
ARTIST("CLOSER TO THE END (ORIGINAL)","Danny Steele")
ARTIST("COCAINE COLA","DayBar")
ARTIST("COCAINE COLA (ORIGINAL)","DayBar")
ARTIST("HERE TODAY (MISSY'S SONG)","Missy Jeanne")
