// chips.h - the chiptune loops of the creator menu: made by tools/make_chiptunes.py, packed by tools/encode_chip.py (do not edit)
//   CHIP(id,"NAME",secret)   secret = 1: only after the title-screen code (UP UP DOWN DOWN LEFT LEFT RIGHT B A START)
CHIP(chip_meltdown_in_mars_house,"MELTDOWN IN MARS",0)
CHIP(chip_sunman_sunrise,"SUNMAN SUNRISE",0)
CHIP(chip_whistler_shuffle,"WHISTLER MAN",0)
CHIP(chip_cynicaller_dnb,"THE CYNICAL SYNDICATION",0)
CHIP(chip_mi_cora_zone,"MI CORA ZONE",0)
CHIP(chip_excuses_house,"EXCUSES",0)
CHIP(chip_aim_and_shoot,"AIM AND SHOOT",0)
CHIP(chip_gottcho_barracho_ii,"GOTTCHO BARRACHO",0)
CHIP(chip_spanish_flexicode,"AN ODE TO THE SPANISH FLEXICODE",0)
CHIP(chip_amiga_music,"AMIGA MUSIC",1)
CHIP(chip_emergency_hitech,"EMERGENCY ON THE DANCE FLOOR",1)
CHIP(chip_hotdamn_rave,"HOT DAMN",1)
