// chips.h - the chiptune loops of the creator menu: voiced by tools/make_chiptunes.py, stored as synth data by tools/chip_synth.py (do not edit)
//   CHIP(id,"NAME",secret,offset into chipsyn.bin)   secret = 1: only after the title-screen code (UP UP DOWN DOWN LEFT LEFT RIGHT B A START)
CHIP(chip_meltdown_in_mars_house,"MELTDOWN IN MARS",0,95168)
CHIP(chip_sunman_sunrise,"SUNMAN SUNRISE",0,98856)
CHIP(chip_whistler_shuffle,"WHISTLER MAN",0,104792)
CHIP(chip_cynicaller_dnb,"THE CYNICAL SYNDICATION",0,111588)
CHIP(chip_mi_cora_zone,"MI CORA ZONE",0,118168)
CHIP(chip_excuses_house,"EXCUSES",0,123716)
CHIP(chip_aim_and_shoot,"AIM AND SHOOT",0,129112)
CHIP(chip_gottcho_barracho_ii,"GOTTCHO BARRACHO",0,133076)
CHIP(chip_spanish_flexicode,"AN ODE TO THE SPANISH FLEXICODE",0,138312)
CHIP(chip_amiga_music,"AMIGA MUSIC",1,143552)
CHIP(chip_emergency_hitech,"EMERGENCY ON THE DANCE FLOOR",1,147504)
CHIP(chip_hotdamn_rave,"HOT DAMN",1,152412)
