// chips.h - the chiptune loops of the creator menu: voiced by tools/make_chiptunes.py, stored as synth data by tools/chip_synth.py (do not edit)
//   CHIP(id,"NAME",secret,offset into chipsyn.bin)   secret = 1: only after the title-screen code (UP UP DOWN DOWN LEFT LEFT RIGHT B A START)
CHIP(chip_meltdown_in_mars_house,"MELTDOWN IN MARS",0,95424)
CHIP(chip_sunman_sunrise,"SUNMAN SUNRISE",0,99112)
CHIP(chip_whistler_shuffle,"WHISTLER MAN",0,105048)
CHIP(chip_cynicaller_dnb,"THE CYNICAL SYNDICATION",0,111844)
CHIP(chip_mi_cora_zone,"MI CORA ZONE",0,118424)
CHIP(chip_excuses_house,"EXCUSES",0,123972)
CHIP(chip_aim_and_shoot,"AIM AND SHOOT",0,129368)
CHIP(chip_gottcho_barracho_ii,"GOTTCHO BARRACHO",0,133332)
CHIP(chip_spanish_flexicode,"AN ODE TO THE SPANISH FLEXICODE",0,138568)
CHIP(chip_magic_act,"THE MAGIC ACT",0,143808)
CHIP(chip_amiga_music,"AMIGA MUSIC",1,149580)
CHIP(chip_emergency_hitech,"EMERGENCY ON THE DANCE FLOOR",1,153532)
CHIP(chip_hotdamn_rave,"HOT DAMN",1,158440)
CHIP(chip_nursery_time,"NURSERY TIME",1,162336)
CHIP(chip_closer_to_the_end,"CLOSER TO THE END",1,166364)
CHIP(chip_cs_whistler,"WHISTLER MAN  SCENE SCORE",1,173516)
