// decorart.h - GENERATED by tools/make_decor_items.py (LIVING AND DECOR pack). HOST-ONLY, included from itembake.h. Edit the script, not this file.
static const u16 pDpRg[3]={RGB(12,3,4),RGB(23,7,8),RGB(29,22,12)};
MAT(mDRgSide,pDpRg,1,1,"a")
MAT(mDRgTop,pDpRg,8,8,"aaaaaaaa","abbbbbba","abcbbcba","abbccbba","abbccbba","abcbbcba","abbbbbba","aaaaaaaa")
static const IBox bxDRug[1]={{0,0,8,8,0,1,{&mDRgSide,&mDRgSide,&mDRgSide,&mDRgSide,&mDRgTop}}};
static const u16 pDpTb[3]={RGB(8,4,2),RGB(21,13,6),RGB(27,19,10)};
MAT(mDTbLeg,pDpTb,1,1,"a")
MAT(mDTbEdge,pDpTb,1,1,"b")
MAT(mDTbTop,pDpTb,8,8,"aaaaaaaa","abbbbbba","abccccba","abbbbbba","abccccba","abbbbbba","abbbbbba","aaaaaaaa")
static const IBox bxDTable[5]={{0,1,1,2,0,6,{&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg}},{7,1,8,2,0,6,{&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg}},{0,6,1,7,0,6,{&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg}},{7,6,8,7,0,6,{&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg,&mDTbLeg}},{0,1,8,7,6,8,{&mDTbEdge,&mDTbEdge,&mDTbEdge,&mDTbEdge,&mDTbTop}}};
static const u16 pDpCh[4]={RGB(8,4,2),RGB(20,12,6),RGB(27,6,6),RGB(30,13,11)};
MAT(mDChLeg,pDpCh,1,1,"a")
MAT(mDChWood,pDpCh,1,1,"b")
MAT(mDChSeat,pDpCh,1,1,"c")
MAT(mDChSeatT,pDpCh,6,6,"cccccc","cdcccc","cccccc","cccccc","ccccdc","cccccc")
MAT(mDChBackF,pDpCh,6,7,"bbbbbb","bcccdb","bccccb","bcccdb","bbbbbb","bbbbbb","bbbbbb")
static const IBox bxDChair[6]={{1,2,2,3,0,3,{&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg}},{6,2,7,3,0,3,{&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg}},{1,6,2,7,0,3,{&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg}},{6,6,7,7,0,3,{&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg,&mDChLeg}},{1,2,7,7,3,5,{&mDChSeat,&mDChSeat,&mDChSeat,&mDChSeat,&mDChSeatT}},{1,2,7,3,5,12,{&mDChWood,&mDChWood,&mDChBackF,&mDChWood,&mDChWood}}};
static const u16 pDpDk[7]={RGB(8,5,3),RGB(20,13,7),RGB(27,20,11),RGB(5,5,8),RGB(9,22,31),RGB(22,27,31),RGB(14,15,18)};
MAT(mDDkWood,pDpDk,1,1,"b")
MAT(mDDkCase,pDpDk,1,1,"d")
MAT(mDDkKeyS,pDpDk,1,1,"g")
MAT(mDDkTop,pDpDk,8,8,"aaaaaaaa","abbbbbba","abccccba","abbbbbba","abccccba","abbbbbba","abbbbbba","aaaaaaaa")
MAT(mDDkDraw,pDpDk,3,3,"aaa","abb","aab")
MAT(mDDkMon,pDpDk,6,6,"dddddd","deeeed","deffed","deeeed","deeeed","dddddd")
MAT(mDDkMonT,pDpDk,6,2,"dddddd","dgggdd")
MAT(mDDkKey,pDpDk,6,2,"gggggg","gdgdgd")
static const IBox bxDDesk[6]={{0,1,8,7,5,7,{&mDDkWood,&mDDkWood,&mDDkWood,&mDDkWood,&mDDkTop}},{0,1,3,7,0,5,{&mDDkDraw,&mDDkWood,&mDDkWood,&mDDkWood,&mDDkWood}},{7,1,8,7,0,5,{&mDDkWood,&mDDkWood,&mDDkWood,&mDDkWood,&mDDkWood}},{2,2,6,3,7,12,{&mDDkMon,&mDDkCase,&mDDkCase,&mDDkCase,&mDDkMonT}},{3,2,5,4,7,8,{&mDDkCase,&mDDkCase,&mDDkCase,&mDDkCase,&mDDkCase}},{2,4,6,6,7,8,{&mDDkKey,&mDDkKey,&mDDkKey,&mDDkKey,&mDDkKeyS}}};
static const u16 pDpLp[4]={RGB(5,5,8),RGB(12,12,15),RGB(30,25,11),RGB(31,31,23)};
MAT(mDLpBase,pDpLp,1,1,"b")
MAT(mDLpPole,pDpLp,1,1,"a")
MAT(mDLpSh,pDpLp,5,5,"ccccc","cdddc","cdddc","cdddc","ccccc")
MAT(mDLpShT,pDpLp,5,5,"ddddd","dcccd","dcccd","dcccd","ddddd")
static const IBox bxDLamp[3]={{2,2,6,6,0,1,{&mDLpBase,&mDLpBase,&mDLpBase,&mDLpBase,&mDLpBase}},{4,4,5,5,1,12,{&mDLpPole,&mDLpPole,&mDLpPole,&mDLpPole,&mDLpPole}},{2,2,6,6,12,17,{&mDLpSh,&mDLpSh,&mDLpSh,&mDLpSh,&mDLpShT}}};
static const u16 pDpPl[5]={RGB(13,6,3),RGB(24,12,6),RGB(4,13,5),RGB(9,22,9),RGB(15,28,14)};
MAT(mDPlPot,pDpPl,4,4,"bbbb","abba","abba","aaaa")
MAT(mDPlRimT,pDpPl,4,4,"aaaa","acca","acca","aaaa")
MAT(mDPlLeaf,pDpPl,6,5,"cdcdcd","dcecdc","cdcdce","ecdcdc","dcecdc")
MAT(mDPlLeafT,pDpPl,8,8,"cdcdcdcc","dcedcdce","cdcdecdc","dcecdcdc","cdcdcdec","dcdcedcd","cecdcdcd","dcdcdced")
MAT(mDPlLeaf2,pDpPl,3,4,"dce","cdd","ecd","dcc")
MAT(mDPlLeaf2T,pDpPl,4,4,"dced","cdcd","edcd","cded")
static const IBox bxDPlant[3]={{2,2,6,6,0,5,{&mDPlPot,&mDPlPot,&mDPlPot,&mDPlPot,&mDPlRimT}},{1,1,7,7,5,10,{&mDPlLeaf,&mDPlLeaf,&mDPlLeaf,&mDPlLeaf,&mDPlLeafT}},{2,2,6,6,10,14,{&mDPlLeaf2,&mDPlLeaf2,&mDPlLeaf2,&mDPlLeaf2,&mDPlLeaf2T}}};
static const u16 pDpDz[4]={RGB(8,4,2),RGB(21,13,6),RGB(27,19,10),RGB(31,26,9)};
MAT(mDDrF,pDpDz,6,10,"aaaaaa","abbbba","abbdba","aaaaaa","abbbba","abbdba","aaaaaa","abbbba","abbdba","aaaaaa")
MAT(mDDrS,pDpDz,1,1,"b")
MAT(mDDrT,pDpDz,6,6,"aaaaaa","abbbba","abccba","abccba","abbbba","aaaaaa")
static const IBox bxDDresser[1]={{1,2,7,7,0,10,{&mDDrF,&mDDrS,&mDDrS,&mDDrS,&mDDrT}}};
static const u16 pDpFp[8]={RGB(7,3,3),RGB(20,8,6),RGB(14,6,5),RGB(2,2,3),RGB(31,19,4),RGB(31,28,10),RGB(22,14,7),RGB(11,6,3)};
MAT(mDFpF,pDpFp,8,12,"bcbbcbbc","bbcbbcbb","bcbbcbbc","bddddddb","bdddeddb","bddeffdb","bdeffffd","bddddddd","bbbbbbbb","bcbbcbbc","bbcbbcbb","bcbbcbbc")
MAT(mDFpS,pDpFp,1,1,"b")
MAT(mDFpMantF,pDpFp,8,2,"gggggggg","hhhhhhhh")
MAT(mDFpMantS,pDpFp,1,1,"g")
MAT(mDFpMantT,pDpFp,8,6,"gggggggg","gggggggg","gggggggg","gggggggg","gggggggg","gggggggg")
MAT(mDFpTop,pDpFp,6,4,"bbbbbb","bcbcbc","bbbbbb","bcbcbc")
static const IBox bxDFire[3]={{0,3,8,8,0,12,{&mDFpF,&mDFpS,&mDFpS,&mDFpS,&mDFpS}},{0,2,8,8,12,14,{&mDFpMantF,&mDFpMantS,&mDFpMantS,&mDFpMantS,&mDFpMantT}},{1,5,7,8,14,18,{&mDFpS,&mDFpS,&mDFpS,&mDFpS,&mDFpTop}}};
static const u16 pDpKc[6]={RGB(8,8,10),RGB(24,24,26),RGB(16,17,20),RGB(8,18,29),RGB(5,5,7),RGB(28,10,6)};
MAT(mDKcF,pDpKc,8,8,"aaaaaaaa","abbbbbba","abbbbbba","abbbbbba","abbaabba","abbbbbba","abbbbbba","aaaaaaaa")
MAT(mDKcS,pDpKc,1,1,"b")
MAT(mDKcT,pDpKc,8,8,"aaaaaaaa","accccdda","accccdda","accccdda","abbbbbba","abeeebba","abbbbbba","aaaaaaaa")
static const IBox bxDCounter[1]={{0,1,8,7,0,8,{&mDKcF,&mDKcS,&mDKcS,&mDKcS,&mDKcT}}};
