// items.h - BORE room items on the GBA: sprite blitting, facing and the tile -> sprite mapping.
// The sprite art itself is pre-baked into ROM (itemrom.h, GENERATED by tools/bake_items.sh from itembake.h), so item sprites use ZERO RAM
// and the number of items is limited only by ROM. See the NEW ITEM note in itemids.h.
// Include AFTER px/shade/EWRAM_BSS/SW/SH/fb are defined.
#include "itemids.h"
#include "itemrom.h"
static void blitItem(int k,int sx,int sy){
    const u16*s=romSpr[k]; int x0=sx-IOX, y0=sy-IOY;   // sprites are read straight from the cartridge: no RAM
    if(x0>SW||x0+IW<0||y0>SH||y0+IH<0) return;
    for(int j=0;j<IH;j++){ int y=y0+j; if((unsigned)y>=SH) continue;
        for(int i=0;i<IW;i++){ u16 c=s[j*IW+i]; if(c!=IKEY){ int x=x0+i; if((unsigned)x<SW) fb[y*SW+x]=c; } } }
}
static const char* const spawnArt[12]={"..hhh..",".hhhhh.",".hsssh.",".sssss.","..sss..",".rrrrr.","rrrrrrr","srrrrrs",".rrrrr.",".bb.bb.",".bb.bb.",".kk.kk."};
static void drawSpawn(int sx,int sy){   // editor marker: a little standing person
    for(int j=0;j<12;j++)for(int i=0;i<7;i++){ char c=spawnArt[j][i]; if(c=='.') continue;
        u16 col=c=='h'?RGB(10,6,3):c=='s'?RGB(30,23,17):c=='r'?RGB(28,8,7):c=='b'?RGB(7,9,20):RGB(3,3,5); px(sx-3+i,sy-11+j,col); }
}
// which way an item faces (world dir 0=S(+y) 1=E(+x) 2=N(-y) 3=W(-x)): away from a wall, toward open floor
static int itemOpen(int x,int y){ if(x<0||y<0||x>=MW||y>=MH) return 0; char c=lifeMap[y][x]; return c=='.'||c=='D'||c=='B'||c=='P'; }
static int itemFacing(int x,int y){
    static const signed char dx[4]={0,1,0,-1}, dy[4]={1,0,-1,0};
    for(int d=0;d<4;d++) if(itemOpen(x+dx[d],y+dy[d])&&!itemOpen(x+dx[(d+2)&3],y+dy[(d+2)&3])) return d;
    for(int d=0;d<4;d++) if(itemOpen(x+dx[d],y+dy[d])) return d;
    return 0;
}
static int itemAlongU(int x,int y,char ch){   // rails / ledges / benches link up with neighbours of their own kind; in the rotated view the axis may swap
    int ax=(x>0&&lifeMap[y][x-1]==ch)+(x<MW-1&&lifeMap[y][x+1]==ch), ay=(y>0&&lifeMap[y-1][x]==ch)+(y<MH-1&&lifeMap[y+1][x]==ch);
    int axisX=!(ay>0&&ax==0); return axisX?!(cview&1):(cview&1);
}
// draw the item standing on real tile (x,y); (sx,sy) = screen centre of the tile
static void drawItemTile(char c,int sx,int sy,int x,int y){
    if(c=='#') blitItem(V_CRATE,sx,sy);
    else if(c=='F') blitItem(V_FRIDGE+((itemFacing(x,y)-cview)&3),sx,sy);
    else if(c=='T') blitItem(V_TOILET+((itemFacing(x,y)-cview)&3),sx,sy);
    else if(c=='=') blitItem(itemAlongU(x,y,'=')?V_RAILU:V_RAILV,sx,sy);
    else if(c=='L') blitItem(itemAlongU(x,y,'L')?V_LEDGEU:V_LEDGEV,sx,sy);
    else if(c=='N') blitItem(itemAlongU(x,y,'N')?V_BENCHU:V_BENCHV,sx,sy);
    else if(c=='J') blitItem(itemAlongU(x,y,'J')?V_JERSEYU:V_JERSEYV,sx,sy);
    else if(c=='X') blitItem(V_FUNBOX,sx,sy);
    else if(c=='O') blitItem(V_BARREL,sx,sy);
    else if(c=='Y') blitItem(V_TRASH,sx,sy);
    else if(c=='Z') blitItem(V_PLANTER,sx,sy);
    else if(c=='K') blitItem(V_PICNIC,sx,sy);
    else if(c=='M') blitItem(V_MPAD,sx,sy);
    else if(isLaunch(c)) blitItem(V_LAUNCH+(((c-'9')-cview)&3),sx,sy);
    else if(isKicker(c)) blitItem(V_KICKER+(((c-'1')-cview)&3),sx,sy);
    else if(isQPipe(c)) blitItem(V_QPIPE+(((c-'5')-cview)&3),sx,sy);
    else if(c=='S') blitItem(V_BED+((itemFacing(x,y)-cview)&3),sx,sy);
    else if(c=='H') blitItem(V_SHOWER+((itemFacing(x,y)-cview)&3),sx,sy);
    else if(c=='C') blitItem(V_SOFA+((itemFacing(x,y)-cview)&3),sx,sy);
    else if(c=='D') blitItem(V_DOOR,sx,sy);
}
