// generated by tools/xm2gba.py from the .xm songs listed in source/songs.h - do not edit
// needs before it: u8 u16 u32 s8, and the XmSong struct (main.c)
#define MUS_RATE 18157
// The note events and the sample data live in source/music/xmdata.bin (pulled into the ROM here with .incbin); the small tables below are plain C arrays.
__asm__(".pushsection .rodata\n"
  ".global xm_the_dipper_man_ev\nxm_the_dipper_man_ev:\n.incbin \"source/music/xmdata.bin\",0,3159\n"
  ".global xm_the_dipper_man_S0\nxm_the_dipper_man_S0:\n.incbin \"source/music/xmdata.bin\",3159,912\n"
  ".global xm_the_dipper_man_S2\nxm_the_dipper_man_S2:\n.incbin \"source/music/xmdata.bin\",4071,9355\n"
  ".global xm_the_dipper_man_S3\nxm_the_dipper_man_S3:\n.incbin \"source/music/xmdata.bin\",13426,911\n"
  ".global xm_the_dipper_man_S7\nxm_the_dipper_man_S7:\n.incbin \"source/music/xmdata.bin\",14337,1030\n"
  ".global xm_the_dipper_man_S8\nxm_the_dipper_man_S8:\n.incbin \"source/music/xmdata.bin\",15367,32195\n"
  ".global xm_the_dipper_man_S10\nxm_the_dipper_man_S10:\n.incbin \"source/music/xmdata.bin\",47562,229\n"
  ".global xm_the_dipper_man_S12\nxm_the_dipper_man_S12:\n.incbin \"source/music/xmdata.bin\",47791,922\n"
  ".global xm_the_dipper_man_S13\nxm_the_dipper_man_S13:\n.incbin \"source/music/xmdata.bin\",48713,1318\n"
  ".global xm_the_dipper_man_S14\nxm_the_dipper_man_S14:\n.incbin \"source/music/xmdata.bin\",50031,859\n"
  ".global xm_the_dipper_man_S15\nxm_the_dipper_man_S15:\n.incbin \"source/music/xmdata.bin\",50890,1027\n"
  ".global xm_earth_and_the_space_citizens_ev\nxm_earth_and_the_space_citizens_ev:\n.incbin \"source/music/xmdata.bin\",51917,917\n"
  ".global xm_earth_and_the_space_citizens_S0\nxm_earth_and_the_space_citizens_S0:\n.incbin \"source/music/xmdata.bin\",52834,18739\n"
  ".global xm_earth_and_the_space_citizens_S1\nxm_earth_and_the_space_citizens_S1:\n.incbin \"source/music/xmdata.bin\",71573,57862\n"
  ".global xm_earth_and_the_space_citizens_S2\nxm_earth_and_the_space_citizens_S2:\n.incbin \"source/music/xmdata.bin\",129435,59382\n"
  ".global xm_earth_and_the_space_citizens_S3\nxm_earth_and_the_space_citizens_S3:\n.incbin \"source/music/xmdata.bin\",188817,60269\n"
  ".global xm_earth_and_the_space_citizens_S4\nxm_earth_and_the_space_citizens_S4:\n.incbin \"source/music/xmdata.bin\",249086,3611\n"
  ".global xm_earth_and_the_space_citizens_S6\nxm_earth_and_the_space_citizens_S6:\n.incbin \"source/music/xmdata.bin\",252697,10317\n"
  ".global xm_earth_and_the_space_citizens_S7\nxm_earth_and_the_space_citizens_S7:\n.incbin \"source/music/xmdata.bin\",263014,20599\n"
  ".global xm_earth_and_the_space_citizens_S9\nxm_earth_and_the_space_citizens_S9:\n.incbin \"source/music/xmdata.bin\",283613,20076\n"
  ".global xm_earth_and_the_space_citizens_S11\nxm_earth_and_the_space_citizens_S11:\n.incbin \"source/music/xmdata.bin\",303689,1210\n"
  ".global xm_earth_and_the_space_citizens_S12\nxm_earth_and_the_space_citizens_S12:\n.incbin \"source/music/xmdata.bin\",304899,3971\n"
  ".global xm_earth_and_the_space_citizens_S13\nxm_earth_and_the_space_citizens_S13:\n.incbin \"source/music/xmdata.bin\",308870,30745\n"
  ".global xm_earth_and_the_space_citizens_S15\nxm_earth_and_the_space_citizens_S15:\n.incbin \"source/music/xmdata.bin\",339615,9362\n"
  ".global xm_earth_and_the_space_citizens_S16\nxm_earth_and_the_space_citizens_S16:\n.incbin \"source/music/xmdata.bin\",348977,15968\n"
  ".global xm_amiga_music_ev\nxm_amiga_music_ev:\n.incbin \"source/music/xmdata.bin\",364945,1753\n"
  ".global xm_amiga_music_S0\nxm_amiga_music_S0:\n.incbin \"source/music/xmdata.bin\",366698,45678\n"
  ".global xm_amiga_music_S1\nxm_amiga_music_S1:\n.incbin \"source/music/xmdata.bin\",412376,45672\n"
  ".global xm_amiga_music_S2\nxm_amiga_music_S2:\n.incbin \"source/music/xmdata.bin\",458048,49380\n"
  ".global xm_amiga_music_S3\nxm_amiga_music_S3:\n.incbin \"source/music/xmdata.bin\",507428,4168\n"
  ".global xm_amiga_music_S4\nxm_amiga_music_S4:\n.incbin \"source/music/xmdata.bin\",511596,4577\n"
  ".global xm_amiga_music_S9\nxm_amiga_music_S9:\n.incbin \"source/music/xmdata.bin\",516173,847\n"
  ".global xm_amiga_music_S10\nxm_amiga_music_S10:\n.incbin \"source/music/xmdata.bin\",517020,302\n"
  ".global xm_amiga_music_S11\nxm_amiga_music_S11:\n.incbin \"source/music/xmdata.bin\",517322,676\n"
  ".global xm_amiga_music_S14\nxm_amiga_music_S14:\n.incbin \"source/music/xmdata.bin\",517998,4681\n"
  ".global xm_emergency_hitech_ev\nxm_emergency_hitech_ev:\n.incbin \"source/music/xmdata.bin\",522679,10977\n"
  ".global xm_emergency_hitech_S0\nxm_emergency_hitech_S0:\n.incbin \"source/music/xmdata.bin\",533656,1225\n"
  ".global xm_emergency_hitech_S1\nxm_emergency_hitech_S1:\n.incbin \"source/music/xmdata.bin\",534881,3210\n"
  ".global xm_emergency_hitech_S2\nxm_emergency_hitech_S2:\n.incbin \"source/music/xmdata.bin\",538091,1019\n"
  ".global xm_emergency_hitech_S3\nxm_emergency_hitech_S3:\n.incbin \"source/music/xmdata.bin\",539110,719\n"
  ".global xm_emergency_hitech_S4\nxm_emergency_hitech_S4:\n.incbin \"source/music/xmdata.bin\",539829,1741\n"
  ".global xm_emergency_hitech_S5\nxm_emergency_hitech_S5:\n.incbin \"source/music/xmdata.bin\",541570,2072\n"
  ".global xm_emergency_hitech_S6\nxm_emergency_hitech_S6:\n.incbin \"source/music/xmdata.bin\",543642,4961\n"
  ".global xm_emergency_hitech_S7\nxm_emergency_hitech_S7:\n.incbin \"source/music/xmdata.bin\",548603,9932\n"
  ".global xm_emergency_hitech_S8\nxm_emergency_hitech_S8:\n.incbin \"source/music/xmdata.bin\",558535,3266\n"
  ".global xm_emergency_hitech_S9\nxm_emergency_hitech_S9:\n.incbin \"source/music/xmdata.bin\",561801,7696\n"
  ".global xm_emergency_hitech_S10\nxm_emergency_hitech_S10:\n.incbin \"source/music/xmdata.bin\",569497,2045\n"
  ".global xm_emergency_hitech_S11\nxm_emergency_hitech_S11:\n.incbin \"source/music/xmdata.bin\",571542,7481\n"
  ".global xm_emergency_hitech_S12\nxm_emergency_hitech_S12:\n.incbin \"source/music/xmdata.bin\",579023,88774\n"
  ".global xm_emergency_hitech_S13\nxm_emergency_hitech_S13:\n.incbin \"source/music/xmdata.bin\",667797,596\n"
  ".global xm_emergency_hitech_S14\nxm_emergency_hitech_S14:\n.incbin \"source/music/xmdata.bin\",668393,16640\n"
  ".global xm_emergency_dance_floor_ev\nxm_emergency_dance_floor_ev:\n.incbin \"source/music/xmdata.bin\",685033,3122\n"
  ".global xm_emergency_dance_floor_S7\nxm_emergency_dance_floor_S7:\n.incbin \"source/music/xmdata.bin\",688155,3936\n"
  ".global xm_emergency_dance_floor_S8\nxm_emergency_dance_floor_S8:\n.incbin \"source/music/xmdata.bin\",692091,22335\n"
  ".global xm_tree_swaying_action_ev\nxm_tree_swaying_action_ev:\n.incbin \"source/music/xmdata.bin\",714426,1947\n"
  ".global xm_tree_swaying_action_S0\nxm_tree_swaying_action_S0:\n.incbin \"source/music/xmdata.bin\",716373,72229\n"
  ".global xm_tree_swaying_action_S1\nxm_tree_swaying_action_S1:\n.incbin \"source/music/xmdata.bin\",788602,72618\n"
  ".global xm_tree_swaying_action_S2\nxm_tree_swaying_action_S2:\n.incbin \"source/music/xmdata.bin\",861220,4668\n"
  ".global xm_tree_swaying_action_S6\nxm_tree_swaying_action_S6:\n.incbin \"source/music/xmdata.bin\",865888,8530\n"
  ".global xm_meltdown_in_mars_house_ev\nxm_meltdown_in_mars_house_ev:\n.incbin \"source/music/xmdata.bin\",874418,19474\n"
  ".global xm_meltdown_in_mars_house_S0\nxm_meltdown_in_mars_house_S0:\n.incbin \"source/music/xmdata.bin\",893892,1231\n"
  ".global xm_meltdown_in_mars_house_S1\nxm_meltdown_in_mars_house_S1:\n.incbin \"source/music/xmdata.bin\",895123,3845\n"
  ".global xm_meltdown_in_mars_house_S2\nxm_meltdown_in_mars_house_S2:\n.incbin \"source/music/xmdata.bin\",898968,1086\n"
  ".global xm_meltdown_in_mars_house_S3\nxm_meltdown_in_mars_house_S3:\n.incbin \"source/music/xmdata.bin\",900054,4900\n"
  ".global xm_meltdown_in_mars_house_S4\nxm_meltdown_in_mars_house_S4:\n.incbin \"source/music/xmdata.bin\",904954,1487\n"
  ".global xm_meltdown_in_mars_house_S5\nxm_meltdown_in_mars_house_S5:\n.incbin \"source/music/xmdata.bin\",906441,4579\n"
  ".global xm_meltdown_in_mars_house_S6\nxm_meltdown_in_mars_house_S6:\n.incbin \"source/music/xmdata.bin\",911020,4563\n"
  ".global xm_meltdown_in_mars_house_S7\nxm_meltdown_in_mars_house_S7:\n.incbin \"source/music/xmdata.bin\",915583,4580\n"
  ".global xm_meltdown_in_mars_house_S8\nxm_meltdown_in_mars_house_S8:\n.incbin \"source/music/xmdata.bin\",920163,9977\n"
  ".global xm_meltdown_in_mars_house_S9\nxm_meltdown_in_mars_house_S9:\n.incbin \"source/music/xmdata.bin\",930140,6582\n"
  ".global xm_meltdown_in_mars_house_S10\nxm_meltdown_in_mars_house_S10:\n.incbin \"source/music/xmdata.bin\",936722,4237\n"
  ".global xm_meltdown_in_mars_house_S11\nxm_meltdown_in_mars_house_S11:\n.incbin \"source/music/xmdata.bin\",940959,1155\n"
  ".global xm_meltdown_in_mars_house_S12\nxm_meltdown_in_mars_house_S12:\n.incbin \"source/music/xmdata.bin\",942114,2316\n"
  ".global xm_meltdown_in_mars_house_S13\nxm_meltdown_in_mars_house_S13:\n.incbin \"source/music/xmdata.bin\",944430,4641\n"
  ".global xm_meltdown_in_mars_house_S14\nxm_meltdown_in_mars_house_S14:\n.incbin \"source/music/xmdata.bin\",949071,9926\n"
  ".global xm_meltdown_in_mars_house_S15\nxm_meltdown_in_mars_house_S15:\n.incbin \"source/music/xmdata.bin\",958997,15846\n"
  ".global xm_meltdown_in_mars_house_S16\nxm_meltdown_in_mars_house_S16:\n.incbin \"source/music/xmdata.bin\",974843,1969\n"
  ".global xm_meltdown_in_mars_house_S17\nxm_meltdown_in_mars_house_S17:\n.incbin \"source/music/xmdata.bin\",976812,4157\n"
  ".global xm_worthless_clouds_ev\nxm_worthless_clouds_ev:\n.incbin \"source/music/xmdata.bin\",980969,89075\n"
  ".global xm_worthless_clouds_S0\nxm_worthless_clouds_S0:\n.incbin \"source/music/xmdata.bin\",1070044,3441\n"
  ".global xm_worthless_clouds_S3\nxm_worthless_clouds_S3:\n.incbin \"source/music/xmdata.bin\",1073485,16567\n"
  ".global xm_worthless_clouds_S6\nxm_worthless_clouds_S6:\n.incbin \"source/music/xmdata.bin\",1090052,4342\n"
  ".global xm_worthless_clouds_S19\nxm_worthless_clouds_S19:\n.incbin \"source/music/xmdata.bin\",1094394,7225\n"
  ".global xm_sunman_sunrise_ev\nxm_sunman_sunrise_ev:\n.incbin \"source/music/xmdata.bin\",1101619,8318\n"
  ".global xm_sunman_sunrise_S0\nxm_sunman_sunrise_S0:\n.incbin \"source/music/xmdata.bin\",1109937,1315\n"
  ".global xm_sunman_sunrise_S1\nxm_sunman_sunrise_S1:\n.incbin \"source/music/xmdata.bin\",1111252,4204\n"
  ".global xm_sunman_sunrise_S2\nxm_sunman_sunrise_S2:\n.incbin \"source/music/xmdata.bin\",1115456,848\n"
  ".global xm_sunman_sunrise_S3\nxm_sunman_sunrise_S3:\n.incbin \"source/music/xmdata.bin\",1116304,5570\n"
  ".global xm_sunman_sunrise_S4\nxm_sunman_sunrise_S4:\n.incbin \"source/music/xmdata.bin\",1121874,1387\n"
  ".global xm_sunman_sunrise_S5\nxm_sunman_sunrise_S5:\n.incbin \"source/music/xmdata.bin\",1123261,2369\n"
  ".global xm_sunman_sunrise_S6\nxm_sunman_sunrise_S6:\n.incbin \"source/music/xmdata.bin\",1125630,1741\n"
  ".global xm_sunman_sunrise_S7\nxm_sunman_sunrise_S7:\n.incbin \"source/music/xmdata.bin\",1127371,2861\n"
  ".global xm_sunman_sunrise_S8\nxm_sunman_sunrise_S8:\n.incbin \"source/music/xmdata.bin\",1130232,18311\n"
  ".global xm_sunman_sunrise_S9\nxm_sunman_sunrise_S9:\n.incbin \"source/music/xmdata.bin\",1148543,7677\n"
  ".global xm_sunman_sunrise_S10\nxm_sunman_sunrise_S10:\n.incbin \"source/music/xmdata.bin\",1156220,1783\n"
  ".global xm_sunman_sunrise_S11\nxm_sunman_sunrise_S11:\n.incbin \"source/music/xmdata.bin\",1158003,11644\n"
  ".global xm_sunman_sunrise_S12\nxm_sunman_sunrise_S12:\n.incbin \"source/music/xmdata.bin\",1169647,9978\n"
  ".global xm_sunman_sunrise_S13\nxm_sunman_sunrise_S13:\n.incbin \"source/music/xmdata.bin\",1179625,46154\n"
  ".global xm_sunman_sunrise_S14\nxm_sunman_sunrise_S14:\n.incbin \"source/music/xmdata.bin\",1225779,4989\n"
  ".global xm_gottcho_barracho_ii_ev\nxm_gottcho_barracho_ii_ev:\n.incbin \"source/music/xmdata.bin\",1230768,14746\n"
  ".global xm_gottcho_barracho_ii_S0\nxm_gottcho_barracho_ii_S0:\n.incbin \"source/music/xmdata.bin\",1245514,1481\n"
  ".global xm_gottcho_barracho_ii_S1\nxm_gottcho_barracho_ii_S1:\n.incbin \"source/music/xmdata.bin\",1246995,1425\n"
  ".global xm_gottcho_barracho_ii_S2\nxm_gottcho_barracho_ii_S2:\n.incbin \"source/music/xmdata.bin\",1248420,4863\n"
  ".global xm_gottcho_barracho_ii_S3\nxm_gottcho_barracho_ii_S3:\n.incbin \"source/music/xmdata.bin\",1253283,1514\n"
  ".global xm_gottcho_barracho_ii_S4\nxm_gottcho_barracho_ii_S4:\n.incbin \"source/music/xmdata.bin\",1254797,695\n"
  ".global xm_gottcho_barracho_ii_S5\nxm_gottcho_barracho_ii_S5:\n.incbin \"source/music/xmdata.bin\",1255492,3746\n"
  ".global xm_gottcho_barracho_ii_S6\nxm_gottcho_barracho_ii_S6:\n.incbin \"source/music/xmdata.bin\",1259238,4133\n"
  ".global xm_gottcho_barracho_ii_S7\nxm_gottcho_barracho_ii_S7:\n.incbin \"source/music/xmdata.bin\",1263371,8260\n"
  ".global xm_gottcho_barracho_ii_S8\nxm_gottcho_barracho_ii_S8:\n.incbin \"source/music/xmdata.bin\",1271631,4962\n"
  ".global xm_gottcho_barracho_ii_S9\nxm_gottcho_barracho_ii_S9:\n.incbin \"source/music/xmdata.bin\",1276593,4136\n"
  ".global xm_gottcho_barracho_ii_S10\nxm_gottcho_barracho_ii_S10:\n.incbin \"source/music/xmdata.bin\",1280729,10827\n"
  ".global xm_gottcho_barracho_ii_S11\nxm_gottcho_barracho_ii_S11:\n.incbin \"source/music/xmdata.bin\",1291556,13334\n"
  ".global xm_gottcho_barracho_ii_S12\nxm_gottcho_barracho_ii_S12:\n.incbin \"source/music/xmdata.bin\",1304890,33449\n"
  ".global xm_gottcho_barracho_ii_S13\nxm_gottcho_barracho_ii_S13:\n.incbin \"source/music/xmdata.bin\",1338339,5825\n"
  ".global xm_gottcho_barracho_ev\nxm_gottcho_barracho_ev:\n.incbin \"source/music/xmdata.bin\",1344164,21262\n"
  ".global xm_spanish_flexicode_ev\nxm_spanish_flexicode_ev:\n.incbin \"source/music/xmdata.bin\",1365426,8606\n"
  ".global xm_spanish_flexicode_S4\nxm_spanish_flexicode_S4:\n.incbin \"source/music/xmdata.bin\",1374032,2897\n"
  ".global xm_spanish_flexicode_S6\nxm_spanish_flexicode_S6:\n.incbin \"source/music/xmdata.bin\",1376929,4442\n"
  ".global xm_spanish_flexicode_S12\nxm_spanish_flexicode_S12:\n.incbin \"source/music/xmdata.bin\",1381371,35839\n"
  ".global xm_mi_cora_zone_ev\nxm_mi_cora_zone_ev:\n.incbin \"source/music/xmdata.bin\",1417210,21885\n"
  ".global xm_mi_cora_zone_S0\nxm_mi_cora_zone_S0:\n.incbin \"source/music/xmdata.bin\",1439095,6158\n"
  ".global xm_mi_cora_zone_S1\nxm_mi_cora_zone_S1:\n.incbin \"source/music/xmdata.bin\",1445253,24647\n"
  ".global xm_mi_cora_zone_S2\nxm_mi_cora_zone_S2:\n.incbin \"source/music/xmdata.bin\",1469900,3265\n"
  ".global xm_mi_cora_zone_S3\nxm_mi_cora_zone_S3:\n.incbin \"source/music/xmdata.bin\",1473165,2345\n"
  ".global xm_mi_cora_zone_S4\nxm_mi_cora_zone_S4:\n.incbin \"source/music/xmdata.bin\",1475510,4866\n"
  ".global xm_mi_cora_zone_S5\nxm_mi_cora_zone_S5:\n.incbin \"source/music/xmdata.bin\",1480376,2626\n"
  ".global xm_mi_cora_zone_S6\nxm_mi_cora_zone_S6:\n.incbin \"source/music/xmdata.bin\",1483002,1879\n"
  ".global xm_mi_cora_zone_S7\nxm_mi_cora_zone_S7:\n.incbin \"source/music/xmdata.bin\",1484881,3730\n"
  ".global xm_mi_cora_zone_S8\nxm_mi_cora_zone_S8:\n.incbin \"source/music/xmdata.bin\",1488611,3991\n"
  ".global xm_excuses_house_ev\nxm_excuses_house_ev:\n.incbin \"source/music/xmdata.bin\",1492602,12998\n"
  ".global xm_excuses_house_S0\nxm_excuses_house_S0:\n.incbin \"source/music/xmdata.bin\",1505600,1726\n"
  ".global xm_excuses_house_S1\nxm_excuses_house_S1:\n.incbin \"source/music/xmdata.bin\",1507326,4887\n"
  ".global xm_excuses_house_S2\nxm_excuses_house_S2:\n.incbin \"source/music/xmdata.bin\",1512213,717\n"
  ".global xm_excuses_house_S3\nxm_excuses_house_S3:\n.incbin \"source/music/xmdata.bin\",1512930,6577\n"
  ".global xm_excuses_house_S4\nxm_excuses_house_S4:\n.incbin \"source/music/xmdata.bin\",1519507,1383\n"
  ".global xm_excuses_house_S5\nxm_excuses_house_S5:\n.incbin \"source/music/xmdata.bin\",1520890,14958\n"
  ".global xm_excuses_house_S6\nxm_excuses_house_S6:\n.incbin \"source/music/xmdata.bin\",1535848,1571\n"
  ".global xm_excuses_house_S7\nxm_excuses_house_S7:\n.incbin \"source/music/xmdata.bin\",1537419,950\n"
  ".global xm_excuses_house_S8\nxm_excuses_house_S8:\n.incbin \"source/music/xmdata.bin\",1538369,10739\n"
  ".global xm_excuses_house_S9\nxm_excuses_house_S9:\n.incbin \"source/music/xmdata.bin\",1549108,21457\n"
  ".global xm_excuses_house_S10\nxm_excuses_house_S10:\n.incbin \"source/music/xmdata.bin\",1570565,42915\n"
  ".global xm_excuses_house_S11\nxm_excuses_house_S11:\n.incbin \"source/music/xmdata.bin\",1613480,3731\n"
  ".global xm_excuses_house_S12\nxm_excuses_house_S12:\n.incbin \"source/music/xmdata.bin\",1617211,23309\n"
  ".global xm_excuses_house_S13\nxm_excuses_house_S13:\n.incbin \"source/music/xmdata.bin\",1640520,4929\n"
  ".global xm_excuses_house_S14\nxm_excuses_house_S14:\n.incbin \"source/music/xmdata.bin\",1645449,42836\n"
  ".global xm_excuses_house_S15\nxm_excuses_house_S15:\n.incbin \"source/music/xmdata.bin\",1688285,86380\n"
  ".global xm_excuses_house_S16\nxm_excuses_house_S16:\n.incbin \"source/music/xmdata.bin\",1774665,21555\n"
  ".global xm_excuses_house_S17\nxm_excuses_house_S17:\n.incbin \"source/music/xmdata.bin\",1796220,5811\n"
  ".global xm_excuses_house_S18\nxm_excuses_house_S18:\n.incbin \"source/music/xmdata.bin\",1802031,19988\n"
  ".global xm_whistler_shuffle_ev\nxm_whistler_shuffle_ev:\n.incbin \"source/music/xmdata.bin\",1822019,6380\n"
  ".global xm_whistler_shuffle_S0\nxm_whistler_shuffle_S0:\n.incbin \"source/music/xmdata.bin\",1828399,1227\n"
  ".global xm_whistler_shuffle_S1\nxm_whistler_shuffle_S1:\n.incbin \"source/music/xmdata.bin\",1829626,4542\n"
  ".global xm_whistler_shuffle_S2\nxm_whistler_shuffle_S2:\n.incbin \"source/music/xmdata.bin\",1834168,1402\n"
  ".global xm_whistler_shuffle_S3\nxm_whistler_shuffle_S3:\n.incbin \"source/music/xmdata.bin\",1835570,858\n"
  ".global xm_whistler_shuffle_S4\nxm_whistler_shuffle_S4:\n.incbin \"source/music/xmdata.bin\",1836428,6220\n"
  ".global xm_whistler_shuffle_S5\nxm_whistler_shuffle_S5:\n.incbin \"source/music/xmdata.bin\",1842648,2384\n"
  ".global xm_whistler_shuffle_S6\nxm_whistler_shuffle_S6:\n.incbin \"source/music/xmdata.bin\",1845032,18305\n"
  ".global xm_whistler_shuffle_S7\nxm_whistler_shuffle_S7:\n.incbin \"source/music/xmdata.bin\",1863337,18321\n"
  ".global xm_whistler_shuffle_S8\nxm_whistler_shuffle_S8:\n.incbin \"source/music/xmdata.bin\",1881658,2489\n"
  ".global xm_whistler_shuffle_S9\nxm_whistler_shuffle_S9:\n.incbin \"source/music/xmdata.bin\",1884147,13342\n"
  ".global xm_whistler_shuffle_S10\nxm_whistler_shuffle_S10:\n.incbin \"source/music/xmdata.bin\",1897489,4093\n"
  ".global xm_whistler_shuffle_S11\nxm_whistler_shuffle_S11:\n.incbin \"source/music/xmdata.bin\",1901582,6080\n"
  ".global xm_whistler_shuffle_S12\nxm_whistler_shuffle_S12:\n.incbin \"source/music/xmdata.bin\",1907662,2202\n"
  ".global xm_whistler_shuffle_S13\nxm_whistler_shuffle_S13:\n.incbin \"source/music/xmdata.bin\",1909864,11546\n"
  ".global xm_whistler_shuffle_old_ev\nxm_whistler_shuffle_old_ev:\n.incbin \"source/music/xmdata.bin\",1921410,20520\n"
  ".global xm_whistler_shuffle_old_S3\nxm_whistler_shuffle_old_S3:\n.incbin \"source/music/xmdata.bin\",1941930,859\n"
  ".global xm_whistler_shuffle_old_S11\nxm_whistler_shuffle_old_S11:\n.incbin \"source/music/xmdata.bin\",1942789,6080\n"
  ".global xm_whistler_shuffle_old_S12\nxm_whistler_shuffle_old_S12:\n.incbin \"source/music/xmdata.bin\",1948869,2202\n"
  ".global xm_cynicaller_dnb_ev\nxm_cynicaller_dnb_ev:\n.incbin \"source/music/xmdata.bin\",1951071,20609\n"
  ".global xm_cynicaller_dnb_S0\nxm_cynicaller_dnb_S0:\n.incbin \"source/music/xmdata.bin\",1971680,1302\n"
  ".global xm_cynicaller_dnb_S1\nxm_cynicaller_dnb_S1:\n.incbin \"source/music/xmdata.bin\",1972982,4281\n"
  ".global xm_cynicaller_dnb_S2\nxm_cynicaller_dnb_S2:\n.incbin \"source/music/xmdata.bin\",1977263,1215\n"
  ".global xm_cynicaller_dnb_S3\nxm_cynicaller_dnb_S3:\n.incbin \"source/music/xmdata.bin\",1978478,598\n"
  ".global xm_cynicaller_dnb_S4\nxm_cynicaller_dnb_S4:\n.incbin \"source/music/xmdata.bin\",1979076,5213\n"
  ".global xm_cynicaller_dnb_S5\nxm_cynicaller_dnb_S5:\n.incbin \"source/music/xmdata.bin\",1984289,1081\n"
  ".global xm_cynicaller_dnb_S6\nxm_cynicaller_dnb_S6:\n.incbin \"source/music/xmdata.bin\",1985370,16656\n"
  ".global xm_cynicaller_dnb_S7\nxm_cynicaller_dnb_S7:\n.incbin \"source/music/xmdata.bin\",2002026,2481\n"
  ".global xm_cynicaller_dnb_S8\nxm_cynicaller_dnb_S8:\n.incbin \"source/music/xmdata.bin\",2004507,2485\n"
  ".global xm_cynicaller_dnb_S9\nxm_cynicaller_dnb_S9:\n.incbin \"source/music/xmdata.bin\",2006992,4977\n"
  ".global xm_cynicaller_dnb_S10\nxm_cynicaller_dnb_S10:\n.incbin \"source/music/xmdata.bin\",2011969,7755\n"
  ".global xm_cynicaller_dnb_S11\nxm_cynicaller_dnb_S11:\n.incbin \"source/music/xmdata.bin\",2019724,1125\n"
  ".global xm_cynicaller_dnb_S12\nxm_cynicaller_dnb_S12:\n.incbin \"source/music/xmdata.bin\",2020849,8317\n"
  ".global xm_cynicaller_dnb_S13\nxm_cynicaller_dnb_S13:\n.incbin \"source/music/xmdata.bin\",2029166,13326\n"
  ".global xm_cynicaller_dnb_S14\nxm_cynicaller_dnb_S14:\n.incbin \"source/music/xmdata.bin\",2042492,3572\n"
  ".global xm_cynicaller_dnb_S15\nxm_cynicaller_dnb_S15:\n.incbin \"source/music/xmdata.bin\",2046064,15582\n"
  ".global xm_hotdamn_rave_ev\nxm_hotdamn_rave_ev:\n.incbin \"source/music/xmdata.bin\",2061646,20568\n"
  ".global xm_hotdamn_rave_S0\nxm_hotdamn_rave_S0:\n.incbin \"source/music/xmdata.bin\",2082214,1232\n"
  ".global xm_hotdamn_rave_S1\nxm_hotdamn_rave_S1:\n.incbin \"source/music/xmdata.bin\",2083446,3950\n"
  ".global xm_hotdamn_rave_S2\nxm_hotdamn_rave_S2:\n.incbin \"source/music/xmdata.bin\",2087396,1397\n"
  ".global xm_hotdamn_rave_S3\nxm_hotdamn_rave_S3:\n.incbin \"source/music/xmdata.bin\",2088793,689\n"
  ".global xm_hotdamn_rave_S4\nxm_hotdamn_rave_S4:\n.incbin \"source/music/xmdata.bin\",2089482,4910\n"
  ".global xm_hotdamn_rave_S5\nxm_hotdamn_rave_S5:\n.incbin \"source/music/xmdata.bin\",2094392,9968\n"
  ".global xm_hotdamn_rave_S6\nxm_hotdamn_rave_S6:\n.incbin \"source/music/xmdata.bin\",2104360,4967\n"
  ".global xm_hotdamn_rave_S7\nxm_hotdamn_rave_S7:\n.incbin \"source/music/xmdata.bin\",2109327,1639\n"
  ".global xm_hotdamn_rave_S8\nxm_hotdamn_rave_S8:\n.incbin \"source/music/xmdata.bin\",2110966,4564\n"
  ".global xm_hotdamn_rave_S9\nxm_hotdamn_rave_S9:\n.incbin \"source/music/xmdata.bin\",2115530,5797\n"
  ".global xm_hotdamn_rave_S10\nxm_hotdamn_rave_S10:\n.incbin \"source/music/xmdata.bin\",2121327,2202\n"
  ".global xm_hotdamn_rave_S11\nxm_hotdamn_rave_S11:\n.incbin \"source/music/xmdata.bin\",2123529,7687\n"
  ".global xm_hotdamn_rave_S12\nxm_hotdamn_rave_S12:\n.incbin \"source/music/xmdata.bin\",2131216,2045\n"
  ".global xm_hotdamn_rave_S13\nxm_hotdamn_rave_S13:\n.incbin \"source/music/xmdata.bin\",2133261,7218\n"
  ".global xm_hotdamn_rave_S14\nxm_hotdamn_rave_S14:\n.incbin \"source/music/xmdata.bin\",2140479,17712\n"
  ".global xm_hotdamn_rave_S15\nxm_hotdamn_rave_S15:\n.incbin \"source/music/xmdata.bin\",2158191,13228\n"
  ".global xm_hotdamn_rave_S16\nxm_hotdamn_rave_S16:\n.incbin \"source/music/xmdata.bin\",2171419,7476\n"
  ".global xm_hotdamn_rave_S17\nxm_hotdamn_rave_S17:\n.incbin \"source/music/xmdata.bin\",2178895,11648\n"
  ".global xm_hotdamn_rave_S18\nxm_hotdamn_rave_S18:\n.incbin \"source/music/xmdata.bin\",2190543,15580\n"
  ".global xm_hotdamn_rave_old_ev\nxm_hotdamn_rave_old_ev:\n.incbin \"source/music/xmdata.bin\",2206123,24208\n"
  ".global xm_aim_and_shoot_ev\nxm_aim_and_shoot_ev:\n.incbin \"source/music/xmdata.bin\",2230331,11792\n"
  ".global xm_aim_and_shoot_S0\nxm_aim_and_shoot_S0:\n.incbin \"source/music/xmdata.bin\",2242123,1650\n"
  ".global xm_aim_and_shoot_S1\nxm_aim_and_shoot_S1:\n.incbin \"source/music/xmdata.bin\",2243773,4937\n"
  ".global xm_aim_and_shoot_S2\nxm_aim_and_shoot_S2:\n.incbin \"source/music/xmdata.bin\",2248710,1436\n"
  ".global xm_aim_and_shoot_S3\nxm_aim_and_shoot_S3:\n.incbin \"source/music/xmdata.bin\",2250146,1868\n"
  ".global xm_aim_and_shoot_S4\nxm_aim_and_shoot_S4:\n.incbin \"source/music/xmdata.bin\",2252014,2885\n"
  ".global xm_aim_and_shoot_S5\nxm_aim_and_shoot_S5:\n.incbin \"source/music/xmdata.bin\",2254899,1224\n"
  ".global xm_aim_and_shoot_S6\nxm_aim_and_shoot_S6:\n.incbin \"source/music/xmdata.bin\",2256123,1232\n"
  ".global xm_aim_and_shoot_S7\nxm_aim_and_shoot_S7:\n.incbin \"source/music/xmdata.bin\",2257355,13358\n"
  ".global xm_aim_and_shoot_S8\nxm_aim_and_shoot_S8:\n.incbin \"source/music/xmdata.bin\",2270713,11086\n"
  ".global xm_aim_and_shoot_S9\nxm_aim_and_shoot_S9:\n.incbin \"source/music/xmdata.bin\",2281799,2212\n"
  ".global xm_aim_and_shoot_S10\nxm_aim_and_shoot_S10:\n.incbin \"source/music/xmdata.bin\",2284011,14904\n"
  ".global xm_aim_and_shoot_S11\nxm_aim_and_shoot_S11:\n.incbin \"source/music/xmdata.bin\",2298915,11565\n"
  ".global xm_aim_and_shoot_S12\nxm_aim_and_shoot_S12:\n.incbin \"source/music/xmdata.bin\",2310480,6646\n"
  ".global xm_aim_and_shoot_S13\nxm_aim_and_shoot_S13:\n.incbin \"source/music/xmdata.bin\",2317126,17736\n"
  ".global xm_aim_and_shoot_S14\nxm_aim_and_shoot_S14:\n.incbin \"source/music/xmdata.bin\",2334862,11039\n"
  ".global xm_aim_and_shoot_S15\nxm_aim_and_shoot_S15:\n.incbin \"source/music/xmdata.bin\",2345901,7481\n"
  ".global xm_aim_and_shoot_S16\nxm_aim_and_shoot_S16:\n.incbin \"source/music/xmdata.bin\",2353382,2759\n"
  ".popsection\n");
extern const u8 xm_the_dipper_man_ev[];
extern const s8 xm_the_dipper_man_S0[];
extern const s8 xm_the_dipper_man_S2[];
extern const s8 xm_the_dipper_man_S3[];
extern const s8 xm_the_dipper_man_S7[];
extern const s8 xm_the_dipper_man_S8[];
extern const s8 xm_the_dipper_man_S10[];
extern const s8 xm_the_dipper_man_S12[];
extern const s8 xm_the_dipper_man_S13[];
extern const s8 xm_the_dipper_man_S14[];
extern const s8 xm_the_dipper_man_S15[];
extern const u8 xm_earth_and_the_space_citizens_ev[];
extern const s8 xm_earth_and_the_space_citizens_S0[];
extern const s8 xm_earth_and_the_space_citizens_S1[];
extern const s8 xm_earth_and_the_space_citizens_S2[];
extern const s8 xm_earth_and_the_space_citizens_S3[];
extern const s8 xm_earth_and_the_space_citizens_S4[];
extern const s8 xm_earth_and_the_space_citizens_S6[];
extern const s8 xm_earth_and_the_space_citizens_S7[];
extern const s8 xm_earth_and_the_space_citizens_S9[];
extern const s8 xm_earth_and_the_space_citizens_S11[];
extern const s8 xm_earth_and_the_space_citizens_S12[];
extern const s8 xm_earth_and_the_space_citizens_S13[];
extern const s8 xm_earth_and_the_space_citizens_S15[];
extern const s8 xm_earth_and_the_space_citizens_S16[];
extern const u8 xm_amiga_music_ev[];
extern const s8 xm_amiga_music_S0[];
extern const s8 xm_amiga_music_S1[];
extern const s8 xm_amiga_music_S2[];
extern const s8 xm_amiga_music_S3[];
extern const s8 xm_amiga_music_S4[];
extern const s8 xm_amiga_music_S9[];
extern const s8 xm_amiga_music_S10[];
extern const s8 xm_amiga_music_S11[];
extern const s8 xm_amiga_music_S14[];
extern const u8 xm_emergency_hitech_ev[];
extern const s8 xm_emergency_hitech_S0[];
extern const s8 xm_emergency_hitech_S1[];
extern const s8 xm_emergency_hitech_S2[];
extern const s8 xm_emergency_hitech_S3[];
extern const s8 xm_emergency_hitech_S4[];
extern const s8 xm_emergency_hitech_S5[];
extern const s8 xm_emergency_hitech_S6[];
extern const s8 xm_emergency_hitech_S7[];
extern const s8 xm_emergency_hitech_S8[];
extern const s8 xm_emergency_hitech_S9[];
extern const s8 xm_emergency_hitech_S10[];
extern const s8 xm_emergency_hitech_S11[];
extern const s8 xm_emergency_hitech_S12[];
extern const s8 xm_emergency_hitech_S13[];
extern const s8 xm_emergency_hitech_S14[];
extern const u8 xm_emergency_dance_floor_ev[];
extern const s8 xm_emergency_dance_floor_S7[];
extern const s8 xm_emergency_dance_floor_S8[];
extern const u8 xm_tree_swaying_action_ev[];
extern const s8 xm_tree_swaying_action_S0[];
extern const s8 xm_tree_swaying_action_S1[];
extern const s8 xm_tree_swaying_action_S2[];
extern const s8 xm_tree_swaying_action_S6[];
extern const u8 xm_meltdown_in_mars_house_ev[];
extern const s8 xm_meltdown_in_mars_house_S0[];
extern const s8 xm_meltdown_in_mars_house_S1[];
extern const s8 xm_meltdown_in_mars_house_S2[];
extern const s8 xm_meltdown_in_mars_house_S3[];
extern const s8 xm_meltdown_in_mars_house_S4[];
extern const s8 xm_meltdown_in_mars_house_S5[];
extern const s8 xm_meltdown_in_mars_house_S6[];
extern const s8 xm_meltdown_in_mars_house_S7[];
extern const s8 xm_meltdown_in_mars_house_S8[];
extern const s8 xm_meltdown_in_mars_house_S9[];
extern const s8 xm_meltdown_in_mars_house_S10[];
extern const s8 xm_meltdown_in_mars_house_S11[];
extern const s8 xm_meltdown_in_mars_house_S12[];
extern const s8 xm_meltdown_in_mars_house_S13[];
extern const s8 xm_meltdown_in_mars_house_S14[];
extern const s8 xm_meltdown_in_mars_house_S15[];
extern const s8 xm_meltdown_in_mars_house_S16[];
extern const s8 xm_meltdown_in_mars_house_S17[];
extern const u8 xm_worthless_clouds_ev[];
extern const s8 xm_worthless_clouds_S0[];
extern const s8 xm_worthless_clouds_S3[];
extern const s8 xm_worthless_clouds_S6[];
extern const s8 xm_worthless_clouds_S19[];
extern const u8 xm_sunman_sunrise_ev[];
extern const s8 xm_sunman_sunrise_S0[];
extern const s8 xm_sunman_sunrise_S1[];
extern const s8 xm_sunman_sunrise_S2[];
extern const s8 xm_sunman_sunrise_S3[];
extern const s8 xm_sunman_sunrise_S4[];
extern const s8 xm_sunman_sunrise_S5[];
extern const s8 xm_sunman_sunrise_S6[];
extern const s8 xm_sunman_sunrise_S7[];
extern const s8 xm_sunman_sunrise_S8[];
extern const s8 xm_sunman_sunrise_S9[];
extern const s8 xm_sunman_sunrise_S10[];
extern const s8 xm_sunman_sunrise_S11[];
extern const s8 xm_sunman_sunrise_S12[];
extern const s8 xm_sunman_sunrise_S13[];
extern const s8 xm_sunman_sunrise_S14[];
extern const u8 xm_gottcho_barracho_ii_ev[];
extern const s8 xm_gottcho_barracho_ii_S0[];
extern const s8 xm_gottcho_barracho_ii_S1[];
extern const s8 xm_gottcho_barracho_ii_S2[];
extern const s8 xm_gottcho_barracho_ii_S3[];
extern const s8 xm_gottcho_barracho_ii_S4[];
extern const s8 xm_gottcho_barracho_ii_S5[];
extern const s8 xm_gottcho_barracho_ii_S6[];
extern const s8 xm_gottcho_barracho_ii_S7[];
extern const s8 xm_gottcho_barracho_ii_S8[];
extern const s8 xm_gottcho_barracho_ii_S9[];
extern const s8 xm_gottcho_barracho_ii_S10[];
extern const s8 xm_gottcho_barracho_ii_S11[];
extern const s8 xm_gottcho_barracho_ii_S12[];
extern const s8 xm_gottcho_barracho_ii_S13[];
extern const u8 xm_gottcho_barracho_ev[];
extern const u8 xm_spanish_flexicode_ev[];
extern const s8 xm_spanish_flexicode_S4[];
extern const s8 xm_spanish_flexicode_S6[];
extern const s8 xm_spanish_flexicode_S12[];
extern const u8 xm_mi_cora_zone_ev[];
extern const s8 xm_mi_cora_zone_S0[];
extern const s8 xm_mi_cora_zone_S1[];
extern const s8 xm_mi_cora_zone_S2[];
extern const s8 xm_mi_cora_zone_S3[];
extern const s8 xm_mi_cora_zone_S4[];
extern const s8 xm_mi_cora_zone_S5[];
extern const s8 xm_mi_cora_zone_S6[];
extern const s8 xm_mi_cora_zone_S7[];
extern const s8 xm_mi_cora_zone_S8[];
extern const u8 xm_excuses_house_ev[];
extern const s8 xm_excuses_house_S0[];
extern const s8 xm_excuses_house_S1[];
extern const s8 xm_excuses_house_S2[];
extern const s8 xm_excuses_house_S3[];
extern const s8 xm_excuses_house_S4[];
extern const s8 xm_excuses_house_S5[];
extern const s8 xm_excuses_house_S6[];
extern const s8 xm_excuses_house_S7[];
extern const s8 xm_excuses_house_S8[];
extern const s8 xm_excuses_house_S9[];
extern const s8 xm_excuses_house_S10[];
extern const s8 xm_excuses_house_S11[];
extern const s8 xm_excuses_house_S12[];
extern const s8 xm_excuses_house_S13[];
extern const s8 xm_excuses_house_S14[];
extern const s8 xm_excuses_house_S15[];
extern const s8 xm_excuses_house_S16[];
extern const s8 xm_excuses_house_S17[];
extern const s8 xm_excuses_house_S18[];
extern const u8 xm_whistler_shuffle_ev[];
extern const s8 xm_whistler_shuffle_S0[];
extern const s8 xm_whistler_shuffle_S1[];
extern const s8 xm_whistler_shuffle_S2[];
extern const s8 xm_whistler_shuffle_S3[];
extern const s8 xm_whistler_shuffle_S4[];
extern const s8 xm_whistler_shuffle_S5[];
extern const s8 xm_whistler_shuffle_S6[];
extern const s8 xm_whistler_shuffle_S7[];
extern const s8 xm_whistler_shuffle_S8[];
extern const s8 xm_whistler_shuffle_S9[];
extern const s8 xm_whistler_shuffle_S10[];
extern const s8 xm_whistler_shuffle_S11[];
extern const s8 xm_whistler_shuffle_S12[];
extern const s8 xm_whistler_shuffle_S13[];
extern const u8 xm_whistler_shuffle_old_ev[];
extern const s8 xm_whistler_shuffle_old_S3[];
extern const s8 xm_whistler_shuffle_old_S11[];
extern const s8 xm_whistler_shuffle_old_S12[];
extern const u8 xm_cynicaller_dnb_ev[];
extern const s8 xm_cynicaller_dnb_S0[];
extern const s8 xm_cynicaller_dnb_S1[];
extern const s8 xm_cynicaller_dnb_S2[];
extern const s8 xm_cynicaller_dnb_S3[];
extern const s8 xm_cynicaller_dnb_S4[];
extern const s8 xm_cynicaller_dnb_S5[];
extern const s8 xm_cynicaller_dnb_S6[];
extern const s8 xm_cynicaller_dnb_S7[];
extern const s8 xm_cynicaller_dnb_S8[];
extern const s8 xm_cynicaller_dnb_S9[];
extern const s8 xm_cynicaller_dnb_S10[];
extern const s8 xm_cynicaller_dnb_S11[];
extern const s8 xm_cynicaller_dnb_S12[];
extern const s8 xm_cynicaller_dnb_S13[];
extern const s8 xm_cynicaller_dnb_S14[];
extern const s8 xm_cynicaller_dnb_S15[];
extern const u8 xm_hotdamn_rave_ev[];
extern const s8 xm_hotdamn_rave_S0[];
extern const s8 xm_hotdamn_rave_S1[];
extern const s8 xm_hotdamn_rave_S2[];
extern const s8 xm_hotdamn_rave_S3[];
extern const s8 xm_hotdamn_rave_S4[];
extern const s8 xm_hotdamn_rave_S5[];
extern const s8 xm_hotdamn_rave_S6[];
extern const s8 xm_hotdamn_rave_S7[];
extern const s8 xm_hotdamn_rave_S8[];
extern const s8 xm_hotdamn_rave_S9[];
extern const s8 xm_hotdamn_rave_S10[];
extern const s8 xm_hotdamn_rave_S11[];
extern const s8 xm_hotdamn_rave_S12[];
extern const s8 xm_hotdamn_rave_S13[];
extern const s8 xm_hotdamn_rave_S14[];
extern const s8 xm_hotdamn_rave_S15[];
extern const s8 xm_hotdamn_rave_S16[];
extern const s8 xm_hotdamn_rave_S17[];
extern const s8 xm_hotdamn_rave_S18[];
extern const u8 xm_hotdamn_rave_old_ev[];
extern const u8 xm_aim_and_shoot_ev[];
extern const s8 xm_aim_and_shoot_S0[];
extern const s8 xm_aim_and_shoot_S1[];
extern const s8 xm_aim_and_shoot_S2[];
extern const s8 xm_aim_and_shoot_S3[];
extern const s8 xm_aim_and_shoot_S4[];
extern const s8 xm_aim_and_shoot_S5[];
extern const s8 xm_aim_and_shoot_S6[];
extern const s8 xm_aim_and_shoot_S7[];
extern const s8 xm_aim_and_shoot_S8[];
extern const s8 xm_aim_and_shoot_S9[];
extern const s8 xm_aim_and_shoot_S10[];
extern const s8 xm_aim_and_shoot_S11[];
extern const s8 xm_aim_and_shoot_S12[];
extern const s8 xm_aim_and_shoot_S13[];
extern const s8 xm_aim_and_shoot_S14[];
extern const s8 xm_aim_and_shoot_S15[];
extern const s8 xm_aim_and_shoot_S16[];
static const u32 xmT[12]={1073741824,1137589835,1205234447,1276901417,1352829926,1433273380,1518500250,1608794974,1704458901,1805811301,1913190429,2026954652};   // 2^(j/12) in Q30: with a per-instrument anchor this gives every note's playback step (see xmStep in main.c)
// ---- the_dipper_man  (from tools/the_dipper_man.xm) ----
static const u8 xm_the_dipper_man_order[89]={0,0,1,1,2,2,2,2,3,4,3,5,3,4,3,6,7,8,9,2,7,8,10,11,12,4,3,5,3,4,
3,6,13,13,13,14,15,14,16,14,15,14,16,17,18,19,2,2,2,3,4,3,5,3,4,3,6,7,8,9,
2,7,8,10,11,20,20,20,20,20,20,20,20,21,22,21,20,21,22,21,20,23,23,23,23,24,24,25,26,
};
static const u16 xm_the_dipper_man_rows[27]={16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,
};
static const u32 xm_the_dipper_man_patOff[27]={0,39,115,245,366,472,578,681,832,974,1122,1273,1406,1527,1627,1745,1857,1960,2069,2196,2335,2501,2697,2899,
3005,3081,3120,
};
static const u16 xm_the_dipper_man_vt[65]={1072,2097,725,1253,1269,1221,2773,2245,514,2563,756,2804,727,3107,2294,1255,
2595,1271,1223,1571,1270,547,2775,35,2247,1059,38,550,1062,2086,3110,2598,
2083,3106,2082,1058,546,34,2594,1570,1574,2,3075,213,2790,244,741,2695,
3316,3074,3,647,3285,166,3238,120,3193,632,2681,1144,2169,2168,1145,3192,
121,
};
static const u32 xm_the_dipper_man_anc[16]={16777870,0,84174454,16717408,0,0,0,123639683,
155776239,0,61819841,0,61819841,174852916,61819841,61819841,
};
static const u8 xm_the_dipper_man_fx[1]={255,
};
static const u32 xm_the_dipper_man_len[16]={911,0,9354,910,0,0,0,1029,32194,0,228,0,921,1317,858,1026,
};
static const s8* const xm_the_dipper_man_data[16]={xm_the_dipper_man_S0,0,xm_the_dipper_man_S2,xm_the_dipper_man_S3,0,0,0,xm_the_dipper_man_S7,xm_the_dipper_man_S8,0,xm_the_dipper_man_S10,0,xm_the_dipper_man_S12,xm_the_dipper_man_S13,xm_the_dipper_man_S14,xm_the_dipper_man_S15};
static const u8 xm_the_dipper_man_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_the_dipper_man_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_the_dipper_man={xm_the_dipper_man_order,xm_the_dipper_man_rows,xm_the_dipper_man_patOff,xm_the_dipper_man_ev,xm_the_dipper_man_vt,xm_the_dipper_man_anc,xm_the_dipper_man_fx,xm_the_dipper_man_len,xm_the_dipper_man_data,xm_the_dipper_man_busL,xm_the_dipper_man_busR,89,4,2178,215};
// ---- earth_and_the_space_citizens  (from tools/earth_and_the_space_citizens.xm) ----
static const u8 xm_earth_and_the_space_citizens_order[26]={0,1,1,2,2,3,3,3,3,2,2,2,2,4,4,4,4,5,5,5,5,6,6,7,8,9,
};
static const u16 xm_earth_and_the_space_citizens_rows[10]={32,32,32,32,32,32,32,32,32,32,
};
static const u32 xm_earth_and_the_space_citizens_patOff[10]={0,40,45,136,278,423,671,759,818,842,
};
static const u16 xm_earth_and_the_space_citizens_vt[22]={3072,2050,1028,6,16,2756,226,3298,242,3314,32,2630,3120,3174,1143,244,
3316,1716,1282,210,770,3216,
};
static const u32 xm_earth_and_the_space_citizens_anc[17]={88698105,88698105,88698105,88698105,24533220,0,40741736,81483472,
0,88698105,0,61819841,247279365,147033190,174852916,174852916,
174852916,
};
static const u8 xm_earth_and_the_space_citizens_fx[1]={255,
};
static const u32 xm_earth_and_the_space_citizens_len[17]={18738,57861,59381,60268,3610,0,10316,20598,0,20075,0,1209,3970,30744,1317,9361,15967,
};
static const s8* const xm_earth_and_the_space_citizens_data[17]={xm_earth_and_the_space_citizens_S0,xm_earth_and_the_space_citizens_S1,xm_earth_and_the_space_citizens_S2,xm_earth_and_the_space_citizens_S3,xm_earth_and_the_space_citizens_S4,0,xm_earth_and_the_space_citizens_S6,xm_earth_and_the_space_citizens_S7,0,xm_earth_and_the_space_citizens_S9,0,xm_earth_and_the_space_citizens_S11,xm_earth_and_the_space_citizens_S12,xm_earth_and_the_space_citizens_S13,xm_the_dipper_man_S13,xm_earth_and_the_space_citizens_S15,xm_earth_and_the_space_citizens_S16};
static const u8 xm_earth_and_the_space_citizens_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_earth_and_the_space_citizens_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_earth_and_the_space_citizens={xm_earth_and_the_space_citizens_order,xm_earth_and_the_space_citizens_rows,xm_earth_and_the_space_citizens_patOff,xm_earth_and_the_space_citizens_ev,xm_earth_and_the_space_citizens_vt,xm_earth_and_the_space_citizens_anc,xm_earth_and_the_space_citizens_fx,xm_earth_and_the_space_citizens_len,xm_earth_and_the_space_citizens_data,xm_earth_and_the_space_citizens_busL,xm_earth_and_the_space_citizens_busR,26,0,2723,141};
// ---- amiga_music  (from tools/amiga_music.xm) ----
static const u8 xm_amiga_music_order[26]={0,1,2,2,3,3,3,8,4,4,4,4,9,5,5,10,11,12,13,14,15,16,17,18,19,20,
};
static const u16 xm_amiga_music_rows[21]={32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,8,
};
static const u32 xm_amiga_music_patOff[21]={0,14,19,24,29,304,519,567,641,744,1046,1143,1218,1285,1330,1424,1518,1590,1662,1707,1752,
};
static const u16 xm_amiga_music_vt[20]={3072,3265,2226,3299,3088,32,225,3138,2611,1684,71,200,214,1697,3286,3301,
3297,229,1601,227,
};
static const u32 xm_amiga_music_anc[16]={88698105,88698105,88698105,30909921,30909921,0,0,0,
0,61819841,15454960,61819841,147033190,174852916,87426458,0,
};
static const u8 xm_amiga_music_fx[1]={255,
};
static const u32 xm_amiga_music_len[16]={45677,45671,49379,4167,4576,0,0,0,0,846,301,675,30744,1317,4680,0,
};
static const s8* const xm_amiga_music_data[16]={xm_amiga_music_S0,xm_amiga_music_S1,xm_amiga_music_S2,xm_amiga_music_S3,xm_amiga_music_S4,0,0,0,0,xm_amiga_music_S9,xm_amiga_music_S10,xm_amiga_music_S11,xm_earth_and_the_space_citizens_S13,xm_the_dipper_man_S13,xm_amiga_music_S14,0};
static const u8 xm_amiga_music_busL[7]={179,160,137,109,79,46,12,
};
static const u8 xm_amiga_music_busR[7]={14,57,98,136,170,199,222,
};
static const XmSong xm_amiga_music={xm_amiga_music_order,xm_amiga_music_rows,xm_amiga_music_patOff,xm_amiga_music_ev,xm_amiga_music_vt,xm_amiga_music_anc,xm_amiga_music_fx,xm_amiga_music_len,xm_amiga_music_data,xm_amiga_music_busL,xm_amiga_music_busR,26,0,2161,140};
// ---- emergency_hitech  (from tools/emergency_hitech.xm) ----
static const u8 xm_emergency_hitech_order[45]={0,1,2,3,4,5,6,7,8,9,10,9,10,9,10,9,11,12,13,14,15,16,17,16,17,16,17,16,18,19,
20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,
};
static const u16 xm_emergency_hitech_rows[35]={48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,
48,48,48,48,16,
};
static const u32 xm_emergency_hitech_patOff[35]={0,63,121,310,529,817,1147,1441,1795,2110,2503,2815,3046,3343,3577,3877,4282,4768,5170,5500,5875,6199,6595,7027,
7537,7957,8467,8896,9415,9838,10339,10606,10897,10932,10976,
};
static const u16 xm_emergency_hitech_vt[31]={1692,3295,2783,1759,735,223,1536,546,1621,3262,2594,1553,1604,1656,1230,2168,
2680,1144,632,1638,3310,137,1674,3211,3175,103,685,2733,238,3123,51,
};
static const u32 xm_emergency_hitech_anc[15]={61819841,247279365,247279365,247279365,61819841,61819841,165039176,247279365,
165039176,82519588,123639683,123639683,165039176,247279365,247279365,
};
static const u8 xm_emergency_hitech_fx[1]={255,
};
static const u32 xm_emergency_hitech_len[15]={1224,3209,1018,718,1740,2071,4960,9931,3265,7695,2044,7480,88773,595,16639,
};
static const s8* const xm_emergency_hitech_data[15]={xm_emergency_hitech_S0,xm_emergency_hitech_S1,xm_emergency_hitech_S2,xm_emergency_hitech_S3,xm_emergency_hitech_S4,xm_emergency_hitech_S5,xm_emergency_hitech_S6,xm_emergency_hitech_S7,xm_emergency_hitech_S8,xm_emergency_hitech_S9,xm_emergency_hitech_S10,xm_emergency_hitech_S11,xm_emergency_hitech_S12,xm_emergency_hitech_S13,xm_emergency_hitech_S14};
static const u8 xm_emergency_hitech_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_emergency_hitech_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_emergency_hitech={xm_emergency_hitech_order,xm_emergency_hitech_rows,xm_emergency_hitech_patOff,xm_emergency_hitech_ev,xm_emergency_hitech_vt,xm_emergency_hitech_anc,xm_emergency_hitech_fx,xm_emergency_hitech_len,xm_emergency_hitech_data,xm_emergency_hitech_busL,xm_emergency_hitech_busR,45,0,752,93};
// ---- emergency_dance_floor  (from tools/emergency_dance_floor.xm) ----
static const u8 xm_emergency_dance_floor_order[52]={0,0,1,1,0,0,1,1,5,5,6,6,5,5,6,6,7,7,8,8,9,9,6,6,5,5,6,6,5,5,
8,8,7,10,10,5,6,6,5,6,6,6,6,7,7,11,12,13,14,15,16,17,
};
static const u16 xm_emergency_dance_floor_rows[18]={24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,
};
static const u32 xm_emergency_dance_floor_patOff[18]={0,96,264,462,750,798,1077,1467,1656,1774,1933,2143,2351,2559,2722,2885,3003,3121,
};
static const u16 xm_emergency_dance_floor_vt[17]={1648,1649,1703,3254,181,130,243,1685,196,1684,3267,3317,3209,216,3288,3304,
232,
};
static const u32 xm_emergency_dance_floor_anc[16]={0,0,0,0,0,0,0,61819841,
123639683,61819841,61819841,247279365,147033190,174852916,174852916,174852916,
};
static const u8 xm_emergency_dance_floor_fx[1]={255,
};
static const u32 xm_emergency_dance_floor_len[16]={0,0,0,0,0,0,0,3935,22334,846,1209,3970,30744,1317,9361,15967,
};
static const s8* const xm_emergency_dance_floor_data[16]={0,0,0,0,0,0,0,xm_emergency_dance_floor_S7,xm_emergency_dance_floor_S8,xm_amiga_music_S9,xm_earth_and_the_space_citizens_S11,xm_earth_and_the_space_citizens_S12,xm_earth_and_the_space_citizens_S13,xm_the_dipper_man_S13,xm_earth_and_the_space_citizens_S15,xm_earth_and_the_space_citizens_S16};
static const u8 xm_emergency_dance_floor_busL[7]={198,177,151,121,87,51,13,
};
static const u8 xm_emergency_dance_floor_busR[7]={13,51,88,123,154,180,201,
};
static const XmSong xm_emergency_dance_floor={xm_emergency_dance_floor_order,xm_emergency_dance_floor_rows,xm_emergency_dance_floor_patOff,xm_emergency_dance_floor_ev,xm_emergency_dance_floor_vt,xm_emergency_dance_floor_anc,xm_emergency_dance_floor_fx,xm_emergency_dance_floor_len,xm_emergency_dance_floor_data,xm_emergency_dance_floor_busL,xm_emergency_dance_floor_busR,52,0,1504,185};
// ---- tree_swaying_action  (from tools/tree_swaying_action.xm) ----
static const u8 xm_tree_swaying_action_order[33]={0,0,1,5,2,6,7,7,7,7,8,8,9,7,7,7,7,6,6,8,9,7,7,7,7,4,9,10,10,10,
10,11,12,
};
static const u16 xm_tree_swaying_action_rows[13]={32,32,32,32,32,32,32,32,32,32,32,32,16,
};
static const u32 xm_tree_swaying_action_patOff[13]={0,32,166,306,506,531,749,973,1281,1417,1515,1823,1921,
};
static const u16 xm_tree_swaying_action_vt[19]={0,17,1634,1635,694,3318,1190,246,2596,2084,1061,3106,232,3304,711,727,
41,1573,552,
};
static const u32 xm_tree_swaying_action_anc[17]={81483472,81483472,30909921,0,0,0,61819841,0,
0,0,61819841,61819841,247279365,147033190,174852916,174852916,
0,
};
static const u8 xm_tree_swaying_action_fx[1]={255,
};
static const u32 xm_tree_swaying_action_len[17]={72228,72617,4667,0,0,0,8529,0,0,0,846,1209,3970,30744,1317,9361,0,
};
static const s8* const xm_tree_swaying_action_data[17]={xm_tree_swaying_action_S0,xm_tree_swaying_action_S1,xm_tree_swaying_action_S2,0,0,0,xm_tree_swaying_action_S6,0,0,0,xm_amiga_music_S9,xm_earth_and_the_space_citizens_S11,xm_earth_and_the_space_citizens_S12,xm_earth_and_the_space_citizens_S13,xm_the_dipper_man_S13,xm_earth_and_the_space_citizens_S15,0};
static const u8 xm_tree_swaying_action_busL[7]={211,190,162,129,93,54,14,
};
static const u8 xm_tree_swaying_action_busR[7]={12,48,83,115,144,168,188,
};
static const XmSong xm_tree_swaying_action={xm_tree_swaying_action_order,xm_tree_swaying_action_rows,xm_tree_swaying_action_patOff,xm_tree_swaying_action_ev,xm_tree_swaying_action_vt,xm_tree_swaying_action_anc,xm_tree_swaying_action_fx,xm_tree_swaying_action_len,xm_tree_swaying_action_data,xm_tree_swaying_action_busL,xm_tree_swaying_action_busR,33,0,4392,211};
// ---- meltdown_in_mars_house  (from tools/meltdown_in_mars_house.xm) ----
static const u8 xm_meltdown_in_mars_house_order[48]={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,5,17,8,5,18,11,19,20,21,22,23,24,25,
5,17,26,27,9,11,28,29,24,25,5,17,8,30,31,32,0,33,
};
static const u16 xm_meltdown_in_mars_house_rows[34]={64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
64,64,64,8,
};
static const u32 xm_meltdown_in_mars_house_patOff[34]={0,292,776,1302,1909,2582,3252,3826,4529,5202,5872,6458,7158,7471,7925,8475,9178,9878,10464,11038,11639,12324,12679,13181,
13932,14605,15275,15978,16678,17135,17886,18559,19085,19473,
};
static const u16 xm_meltdown_in_mars_house_vt[26]={1536,3106,2232,34,3123,580,51,3206,17,3089,2248,3173,2165,2305,3321,1817,
1092,2776,2809,3305,2644,2199,1704,233,1720,2694,
};
static const u32 xm_meltdown_in_mars_house_anc[18]={61819841,247279365,247279365,247279365,61819841,61819841,165039176,165039176,
61819841,165039176,247279365,61819841,123639683,247279365,165039176,61819841,
247279365,61819841,
};
static const u8 xm_meltdown_in_mars_house_fx[1]={255,
};
static const u32 xm_meltdown_in_mars_house_len[18]={1230,3844,1085,4899,1486,4578,4562,4579,9976,6581,4236,1154,2315,4640,9925,15845,1968,4156,
};
static const s8* const xm_meltdown_in_mars_house_data[18]={xm_meltdown_in_mars_house_S0,xm_meltdown_in_mars_house_S1,xm_meltdown_in_mars_house_S2,xm_meltdown_in_mars_house_S3,xm_meltdown_in_mars_house_S4,xm_meltdown_in_mars_house_S5,xm_meltdown_in_mars_house_S6,xm_meltdown_in_mars_house_S7,xm_meltdown_in_mars_house_S8,xm_meltdown_in_mars_house_S9,xm_meltdown_in_mars_house_S10,xm_meltdown_in_mars_house_S11,xm_meltdown_in_mars_house_S12,xm_meltdown_in_mars_house_S13,xm_meltdown_in_mars_house_S14,xm_meltdown_in_mars_house_S15,xm_meltdown_in_mars_house_S16,xm_meltdown_in_mars_house_S17};
static const u8 xm_meltdown_in_mars_house_busL[7]={178,159,136,109,78,45,11,
};
static const u8 xm_meltdown_in_mars_house_busR[7]={14,57,98,136,171,200,223,
};
static const XmSong xm_meltdown_in_mars_house={xm_meltdown_in_mars_house_order,xm_meltdown_in_mars_house_rows,xm_meltdown_in_mars_house_patOff,xm_meltdown_in_mars_house_ev,xm_meltdown_in_mars_house_vt,xm_meltdown_in_mars_house_anc,xm_meltdown_in_mars_house_fx,xm_meltdown_in_mars_house_len,xm_meltdown_in_mars_house_data,xm_meltdown_in_mars_house_busL,xm_meltdown_in_mars_house_busR,48,0,2161,140};
// ---- worthless_clouds  (from tools/worthless_clouds.xm) ----
static const u8 xm_worthless_clouds_order[163]={0,1,2,3,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,
61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,
91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,
121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,
151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,
181,182,183,184,185,186,187,188,189,31,32,33,190,
};
static const u16 xm_worthless_clouds_rows[191]={192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,192,
192,192,192,192,192,192,192,192,192,192,192,
};
static const u32 xm_worthless_clouds_patOff[191]={0,60,175,227,445,447,449,451,453,591,878,1306,1697,2070,2479,2822,3295,3753,4250,4722,5216,5659,6141,6632,
7168,7722,8021,8320,8619,8918,9090,9213,9231,9272,9322,9324,9558,9796,10140,10465,10938,11366,11820,12280,12597,12832,13103,13434,
13797,14172,14529,14893,15316,15657,16111,16490,16865,17322,17780,18160,18632,19003,19412,19815,20207,20595,21061,21451,21890,22365,23045,23744,
24376,25086,25505,25935,26366,26789,27176,27526,28083,28721,29240,29815,30432,30954,31511,32057,32663,33232,33771,34293,34871,35446,36006,36524,
37111,37740,38343,38990,39635,40278,40955,41530,42144,42711,43365,43964,44692,45396,45959,46518,47180,47845,48479,49165,49716,50286,50873,51439,
52032,52625,53324,53977,54477,54881,55285,55691,56314,56904,57471,58013,58586,59183,59842,60442,61023,61514,62050,62627,63190,63813,64343,64866,
65448,66114,66764,67358,68011,68547,69140,69504,69916,70355,70893,71428,71893,72371,72748,73079,73477,73947,74375,74847,75418,76077,76728,77336,
77998,78652,79323,79962,80566,81282,81953,82572,83255,83806,84258,84803,85348,85887,86400,86912,87358,87728,87946,88241,88512,88783,89054,
};
static const u16 xm_worthless_clouds_vt[74]={240,1617,578,1539,3299,227,1616,65,1202,176,2229,689,192,705,2245,1683,
1026,1682,2564,3300,228,3301,1266,1689,1706,3321,3272,2809,217,233,3305,3289,
96,1684,1701,2614,3255,3126,2292,1731,1780,212,3284,2691,1604,2629,1691,3203,
2116,2117,1,129,1091,1603,53,565,513,1538,1618,1625,2634,1716,3296,224,
1686,1852,287,3359,3375,303,269,3342,781,3170,
};
static const u32 xm_worthless_clouds_anc[20]={61819841,0,0,123639683,30909921,61819841,61819841,0,
123639683,61819841,61819841,247279365,147033190,174852916,174852916,174852916,
123639683,174852916,174852916,123639683,
};
static const u8 xm_worthless_clouds_fx[1]={255,
};
static const u32 xm_worthless_clouds_len[20]={3440,0,0,16566,4576,8529,4341,0,22334,846,1209,3970,30744,1317,9361,15967,22334,1317,9361,7224,
};
static const s8* const xm_worthless_clouds_data[20]={xm_worthless_clouds_S0,0,0,xm_worthless_clouds_S3,xm_amiga_music_S4,xm_tree_swaying_action_S6,xm_worthless_clouds_S6,0,xm_emergency_dance_floor_S8,xm_amiga_music_S9,xm_earth_and_the_space_citizens_S11,xm_earth_and_the_space_citizens_S12,xm_earth_and_the_space_citizens_S13,xm_the_dipper_man_S13,xm_earth_and_the_space_citizens_S15,xm_earth_and_the_space_citizens_S16,xm_emergency_dance_floor_S8,xm_the_dipper_man_S13,xm_earth_and_the_space_citizens_S15,xm_worthless_clouds_S19};
static const u8 xm_worthless_clouds_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_worthless_clouds_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_worthless_clouds={xm_worthless_clouds_order,xm_worthless_clouds_rows,xm_worthless_clouds_patOff,xm_worthless_clouds_ev,xm_worthless_clouds_vt,xm_worthless_clouds_anc,xm_worthless_clouds_fx,xm_worthless_clouds_len,xm_worthless_clouds_data,xm_worthless_clouds_busL,xm_worthless_clouds_busR,163,0,394,184};
// ---- sunman_sunrise  (from tools/sunman_sunrise.xm) ----
static const u8 xm_sunman_sunrise_order[23]={0,1,2,3,4,5,5,5,6,7,8,9,9,9,10,11,12,13,13,13,14,15,16,
};
static const u16 xm_sunman_sunrise_rows[17]={64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,16,
};
static const u32 xm_sunman_sunrise_patOff[17]={0,208,488,936,1411,2054,2694,3226,3803,4638,5470,5678,5994,6829,7661,8109,8317,
};
static const u16 xm_sunman_sunrise_vt[28]={3189,1654,119,2235,2747,3106,34,2779,1536,612,3242,2730,81,3153,2200,2201,
3275,67,3139,17,3089,51,3123,3205,1670,135,203,1771,
};
static const u32 xm_sunman_sunrise_anc[15]={61819841,247279365,247279365,247279365,247279365,247279365,61819841,82519588,
247279365,165039176,123639683,123639683,165039176,165039176,61819841,
};
static const u8 xm_sunman_sunrise_fx[1]={255,
};
static const u32 xm_sunman_sunrise_len[15]={1314,4203,847,5569,1386,2368,1740,2860,18310,7676,1782,11643,9977,46153,4988,
};
static const s8* const xm_sunman_sunrise_data[15]={xm_sunman_sunrise_S0,xm_sunman_sunrise_S1,xm_sunman_sunrise_S2,xm_sunman_sunrise_S3,xm_sunman_sunrise_S4,xm_sunman_sunrise_S5,xm_sunman_sunrise_S6,xm_sunman_sunrise_S7,xm_sunman_sunrise_S8,xm_sunman_sunrise_S9,xm_sunman_sunrise_S10,xm_sunman_sunrise_S11,xm_sunman_sunrise_S12,xm_sunman_sunrise_S13,xm_sunman_sunrise_S14};
static const u8 xm_sunman_sunrise_busL[7]={168,150,128,102,74,43,11,
};
static const u8 xm_sunman_sunrise_busR[7]={15,61,104,145,181,212,237,
};
static const XmSong xm_sunman_sunrise={xm_sunman_sunrise_order,xm_sunman_sunrise_rows,xm_sunman_sunrise_patOff,xm_sunman_sunrise_ev,xm_sunman_sunrise_vt,xm_sunman_sunrise_anc,xm_sunman_sunrise_fx,xm_sunman_sunrise_len,xm_sunman_sunrise_data,xm_sunman_sunrise_busL,xm_sunman_sunrise_busR,23,0,2347,227};
// ---- gottcho_barracho_ii  (from tools/gottcho_barracho_ii.xm) ----
static const u8 xm_gottcho_barracho_ii_order[62]={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,
30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,
60,61,
};
static const u16 xm_gottcho_barracho_ii_rows[62]={32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,
32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,
32,16,
};
static const u32 xm_gottcho_barracho_ii_patOff[62]={0,59,152,394,633,871,1098,1330,1569,1817,2089,2376,2639,2923,3198,3509,3814,4131,4397,4702,5004,5315,5596,5916,
6200,6523,6804,6965,7113,7288,7455,7625,7771,7926,8099,8275,8448,8618,8800,9003,9296,9616,9942,10238,10537,10851,11183,11485,
11778,12095,12418,12720,13022,13336,13644,13955,14109,14249,14415,14584,14680,14745,
};
static const u16 xm_gottcho_barracho_ii_vt[23]={101,1638,3175,702,1743,632,2681,1536,578,1620,1674,1759,139,2626,3211,1553,
2611,1569,2733,2716,2204,1180,668,
};
static const u32 xm_gottcho_barracho_ii_anc[14]={61819841,247279365,247279365,247279365,247279365,61819841,82519588,123639683,
82519588,123639683,123639683,123639683,165039176,61819841,
};
static const u8 xm_gottcho_barracho_ii_fx[1]={255,
};
static const u32 xm_gottcho_barracho_ii_len[14]={1480,1424,4862,1513,694,3745,4132,8259,4961,4135,10826,13333,33448,5824,
};
static const s8* const xm_gottcho_barracho_ii_data[14]={xm_gottcho_barracho_ii_S0,xm_gottcho_barracho_ii_S1,xm_gottcho_barracho_ii_S2,xm_gottcho_barracho_ii_S3,xm_gottcho_barracho_ii_S4,xm_gottcho_barracho_ii_S5,xm_gottcho_barracho_ii_S6,xm_gottcho_barracho_ii_S7,xm_gottcho_barracho_ii_S8,xm_gottcho_barracho_ii_S9,xm_gottcho_barracho_ii_S10,xm_gottcho_barracho_ii_S11,xm_gottcho_barracho_ii_S12,xm_gottcho_barracho_ii_S13};
static const u8 xm_gottcho_barracho_ii_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_gottcho_barracho_ii_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_gottcho_barracho_ii={xm_gottcho_barracho_ii_order,xm_gottcho_barracho_ii_rows,xm_gottcho_barracho_ii_patOff,xm_gottcho_barracho_ii_ev,xm_gottcho_barracho_ii_vt,xm_gottcho_barracho_ii_anc,xm_gottcho_barracho_ii_fx,xm_gottcho_barracho_ii_len,xm_gottcho_barracho_ii_data,xm_gottcho_barracho_ii_busL,xm_gottcho_barracho_ii_busR,62,0,1702,56};
// ---- gottcho_barracho  (from tools/gottcho_barracho.xm) ----
static const u8 xm_gottcho_barracho_order[80]={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,
30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,
60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,
};
static const u16 xm_gottcho_barracho_rows[80]={96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,
96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,
96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,
};
static const u32 xm_gottcho_barracho_patOff[80]={0,58,164,346,606,875,1180,1497,1826,2155,2511,2834,3214,3585,3971,4345,4656,4985,5353,5691,6029,6376,6744,7055,
7459,7878,8327,8734,9045,9374,9730,10059,10299,10357,10378,10438,10519,10617,10733,10862,11008,11136,11270,11428,11622,11780,11941,12132,
12377,12577,12804,13055,13417,13764,14120,14476,14823,15146,15484,15840,16181,16510,16866,17231,17593,17943,18296,18649,18984,19292,19639,19998,
20363,20737,20851,20960,21057,21236,21260,21261,
};
static const u16 xm_gottcho_barracho_vt[38]={38,550,1063,1576,1575,2088,2601,3113,1536,1553,2219,635,3405,1642,1594,1554,
1555,2316,3389,1626,3227,204,1556,1610,3373,301,3276,317,1163,1260,155,1308,
3259,220,187,3292,1557,2300,
};
static const u32 xm_gottcho_barracho_anc[21]={161648555,128706469,177957468,61819841,61819841,61819841,15454960,247279365,
247279365,247279365,61819841,174852916,247279365,174852916,61819841,61819841,
61819841,123639683,247279365,165039176,147033190,
};
static const u8 xm_gottcho_barracho_fx[1]={255,
};
static const u32 xm_gottcho_barracho_len[21]={1486,7224,9354,1230,846,1209,301,3970,1968,3844,675,9361,1085,1317,921,858,1026,1029,4899,9925,30744,
};
static const s8* const xm_gottcho_barracho_data[21]={xm_meltdown_in_mars_house_S4,xm_worthless_clouds_S19,xm_the_dipper_man_S2,xm_meltdown_in_mars_house_S0,xm_amiga_music_S9,xm_earth_and_the_space_citizens_S11,xm_amiga_music_S10,xm_earth_and_the_space_citizens_S12,xm_meltdown_in_mars_house_S16,xm_meltdown_in_mars_house_S1,xm_amiga_music_S11,xm_earth_and_the_space_citizens_S15,xm_meltdown_in_mars_house_S2,xm_the_dipper_man_S13,xm_the_dipper_man_S12,xm_the_dipper_man_S14,xm_the_dipper_man_S15,xm_the_dipper_man_S7,xm_meltdown_in_mars_house_S3,xm_meltdown_in_mars_house_S14,xm_earth_and_the_space_citizens_S13};
static const u8 xm_gottcho_barracho_busL[7]={199,178,152,122,87,51,13,
};
static const u8 xm_gottcho_barracho_busR[7]={13,51,88,122,153,179,200,
};
static const XmSong xm_gottcho_barracho={xm_gottcho_barracho_order,xm_gottcho_barracho_rows,xm_gottcho_barracho_patOff,xm_gottcho_barracho_ev,xm_gottcho_barracho_vt,xm_gottcho_barracho_anc,xm_gottcho_barracho_fx,xm_gottcho_barracho_len,xm_gottcho_barracho_data,xm_gottcho_barracho_busL,xm_gottcho_barracho_busR,80,0,567,104};
// ---- spanish_flexicode  (from tools/spanish_flexicode.xm) ----
static const u8 xm_spanish_flexicode_order[46]={0,1,2,3,4,5,5,5,6,7,8,9,8,10,11,12,11,13,14,15,16,15,16,15,16,15,17,18,19,20,
21,22,23,24,24,25,26,26,26,27,28,29,30,31,32,33,
};
static const u16 xm_spanish_flexicode_rows[34]={24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,
24,24,24,16,
};
static const u32 xm_spanish_flexicode_patOff[34]={0,63,159,294,453,747,1038,1284,1563,1872,2157,2466,2775,3060,3372,3759,4167,4551,4842,5163,5270,5438,5582,5816,
6203,6587,6995,7379,7787,8078,8294,8448,8543,8605,
};
static const u16 xm_spanish_flexicode_vt[24]={101,1638,3175,702,632,2681,562,1743,2098,1536,1620,1674,1759,139,1553,3211,
1692,2204,2716,1180,668,1569,2627,2733,
};
static const u32 xm_spanish_flexicode_anc[14]={61819841,247279365,247279365,247279365,247279365,61819841,82519588,123639683,
82519588,123639683,123639683,123639683,165039176,61819841,
};
static const u8 xm_spanish_flexicode_fx[1]={255,
};
static const u32 xm_spanish_flexicode_len[14]={1480,1424,4862,1513,2896,3745,4441,8259,4961,4135,10826,13333,35838,5824,
};
static const s8* const xm_spanish_flexicode_data[14]={xm_gottcho_barracho_ii_S0,xm_gottcho_barracho_ii_S1,xm_gottcho_barracho_ii_S2,xm_gottcho_barracho_ii_S3,xm_spanish_flexicode_S4,xm_gottcho_barracho_ii_S5,xm_spanish_flexicode_S6,xm_gottcho_barracho_ii_S7,xm_gottcho_barracho_ii_S8,xm_gottcho_barracho_ii_S9,xm_gottcho_barracho_ii_S10,xm_gottcho_barracho_ii_S11,xm_spanish_flexicode_S12,xm_gottcho_barracho_ii_S13};
static const u8 xm_spanish_flexicode_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_spanish_flexicode_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_spanish_flexicode={xm_spanish_flexicode_order,xm_spanish_flexicode_rows,xm_spanish_flexicode_patOff,xm_spanish_flexicode_ev,xm_spanish_flexicode_vt,xm_spanish_flexicode_anc,xm_spanish_flexicode_fx,xm_spanish_flexicode_len,xm_spanish_flexicode_data,xm_spanish_flexicode_busL,xm_spanish_flexicode_busR,46,0,2431,190};
// ---- mi_cora_zone  (from tools/mi_cora_zone.xm) ----
static const u8 xm_mi_cora_zone_order[92]={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,
30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,
60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,
90,91,
};
static const u16 xm_mi_cora_zone_rows[92]={32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,
32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,
32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,
32,32,
};
static const u32 xm_mi_cora_zone_patOff[92]={0,50,121,208,371,508,688,913,1212,1430,1657,1884,2120,2344,2583,2822,3085,3303,3536,3769,3972,4190,4423,4656,
4880,5143,5391,5636,5857,6114,6362,6607,6840,7112,7372,7629,7928,8227,8511,8840,9127,9240,9341,9437,9513,9619,9748,9969,
10263,10586,10906,11199,11483,11782,12078,12347,12661,12987,13307,13600,13860,14159,14455,14724,14996,15199,15414,15629,15829,16080,16322,16609,
16954,17253,17549,17818,18120,18446,18766,19059,19343,19642,19938,20207,20479,20802,21122,21415,21478,21622,21773,21884,
};
static const u16 xm_mi_cora_zone_vt[50]={2626,2612,1640,1571,1115,2186,0,1537,1693,2656,2657,2146,2147,2148,1637,1638,
1639,1128,1129,1130,619,620,109,110,111,2687,172,3244,2185,1112,1113,1658,
1045,2590,2078,1558,2071,1559,2205,1557,3103,3087,512,2114,16,529,3221,118,
2183,159,
};
static const u32 xm_mi_cora_zone_anc[11]={123639683,122971957,61819841,123639683,123639683,92625106,155776239,110150435,
123639683,147033190,247279365,
};
static const u8 xm_mi_cora_zone_fx[1]={255,
};
static const u32 xm_mi_cora_zone_len[11]={6157,24646,3264,2344,4865,2625,1878,3729,3990,30744,4899,
};
static const s8* const xm_mi_cora_zone_data[11]={xm_mi_cora_zone_S0,xm_mi_cora_zone_S1,xm_mi_cora_zone_S2,xm_mi_cora_zone_S3,xm_mi_cora_zone_S4,xm_mi_cora_zone_S5,xm_mi_cora_zone_S6,xm_mi_cora_zone_S7,xm_mi_cora_zone_S8,xm_earth_and_the_space_citizens_S13,xm_meltdown_in_mars_house_S3};
static const u8 xm_mi_cora_zone_busL[7]={199,178,152,122,87,51,13,
};
static const u8 xm_mi_cora_zone_busR[7]={13,51,88,122,153,179,200,
};
static const XmSong xm_mi_cora_zone={xm_mi_cora_zone_order,xm_mi_cora_zone_rows,xm_mi_cora_zone_patOff,xm_mi_cora_zone_ev,xm_mi_cora_zone_vt,xm_mi_cora_zone_anc,xm_mi_cora_zone_fx,xm_mi_cora_zone_len,xm_mi_cora_zone_data,xm_mi_cora_zone_busL,xm_mi_cora_zone_busR,92,0,1023,228};
// ---- excuses_house  (from tools/excuses_house.xm) ----
static const u8 xm_excuses_house_order[106]={0,1,0,1,2,3,2,3,2,4,5,6,7,6,8,9,10,11,12,13,14,13,14,13,14,13,15,16,15,16,
15,16,15,17,18,19,20,19,20,19,21,22,21,22,23,24,25,26,27,26,27,26,27,26,28,29,28,29,28,29,
28,30,31,32,33,32,33,32,33,34,33,32,33,32,35,36,37,38,39,40,41,40,41,40,41,40,41,40,41,40,
41,40,41,42,43,44,43,44,45,46,45,46,45,47,48,49,
};
static const u16 xm_excuses_house_rows[50]={64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,
64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,16,
};
static const u32 xm_excuses_house_patOff[50]={0,31,62,185,305,428,665,899,1133,1527,1921,2318,2721,3142,3560,3978,4444,4910,5400,5452,5496,5545,5716,5884,
6058,6254,6723,7189,7655,8082,8512,8951,9077,9197,9320,9443,9612,9781,9953,10150,10628,11106,11581,12068,12386,12704,12827,12947,
12972,12997,
};
static const u16 xm_excuses_house_vt[36]={1636,136,1673,3210,2287,1536,2611,2255,3342,152,1689,3226,1757,302,546,2269,
1553,2781,1245,733,2627,629,1654,2679,2814,1822,1723,2143,188,3260,168,1705,
3242,1739,204,3276,
};
static const u32 xm_excuses_house_anc[19]={61819841,247279365,247279365,247279365,247279365,247279365,61819841,41259794,
41259794,82519588,165039176,61819841,247279365,247279365,165039176,165039176,
165039176,61819841,247279365,
};
static const u8 xm_excuses_house_fx[1]={255,
};
static const u32 xm_excuses_house_len[19]={1725,4886,716,6576,1382,14957,1570,949,10738,21456,42914,3730,23308,4928,42835,86379,21554,5810,19987,
};
static const s8* const xm_excuses_house_data[19]={xm_excuses_house_S0,xm_excuses_house_S1,xm_excuses_house_S2,xm_excuses_house_S3,xm_excuses_house_S4,xm_excuses_house_S5,xm_excuses_house_S6,xm_excuses_house_S7,xm_excuses_house_S8,xm_excuses_house_S9,xm_excuses_house_S10,xm_excuses_house_S11,xm_excuses_house_S12,xm_excuses_house_S13,xm_excuses_house_S14,xm_excuses_house_S15,xm_excuses_house_S16,xm_excuses_house_S17,xm_excuses_house_S18};
static const u8 xm_excuses_house_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_excuses_house_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_excuses_house={xm_excuses_house_order,xm_excuses_house_rows,xm_excuses_house_patOff,xm_excuses_house_ev,xm_excuses_house_vt,xm_excuses_house_anc,xm_excuses_house_fx,xm_excuses_house_len,xm_excuses_house_data,xm_excuses_house_busL,xm_excuses_house_busR,106,0,1098,53};
// ---- whistler_shuffle  (from tools/whistler_shuffle.xm) ----
static const u8 xm_whistler_shuffle_order[71]={0,0,1,2,3,4,4,4,4,4,4,5,6,6,6,6,6,6,6,6,7,8,8,8,8,8,8,9,10,10,
10,10,10,10,10,10,11,11,11,12,13,14,14,14,14,14,14,14,15,15,15,15,15,15,15,16,17,17,17,17,
17,17,17,17,18,18,18,18,19,19,20,
};
static const u16 xm_whistler_shuffle_rows[21]={48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,16,
};
static const u32 xm_whistler_shuffle_patOff[21]={0,62,286,529,850,1168,1504,1900,2293,2683,3088,3430,3690,3969,4362,4752,5232,5727,6111,6335,6379,
};
static const u16 xm_whistler_shuffle_vt[18]={662,1687,2712,1740,1536,2611,1669,1553,681,639,1058,2628,1210,2235,2644,2765,
2782,623,
};
static const u32 xm_whistler_shuffle_anc[14]={61819841,247279365,247279365,247279365,247279365,247279365,247279365,247279365,
61819841,123639683,247279365,165039176,41259794,247279365,
};
static const u8 xm_whistler_shuffle_fx[1]={255,
};
static const u32 xm_whistler_shuffle_len[14]={1226,4541,1401,857,6219,2383,18304,18320,2488,13341,4092,6079,2201,11545,
};
static const s8* const xm_whistler_shuffle_data[14]={xm_whistler_shuffle_S0,xm_whistler_shuffle_S1,xm_whistler_shuffle_S2,xm_whistler_shuffle_S3,xm_whistler_shuffle_S4,xm_whistler_shuffle_S5,xm_whistler_shuffle_S6,xm_whistler_shuffle_S7,xm_whistler_shuffle_S8,xm_whistler_shuffle_S9,xm_whistler_shuffle_S10,xm_whistler_shuffle_S11,xm_whistler_shuffle_S12,xm_whistler_shuffle_S13};
static const u8 xm_whistler_shuffle_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_whistler_shuffle_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_whistler_shuffle={xm_whistler_shuffle_order,xm_whistler_shuffle_rows,xm_whistler_shuffle_patOff,xm_whistler_shuffle_ev,xm_whistler_shuffle_vt,xm_whistler_shuffle_anc,xm_whistler_shuffle_fx,xm_whistler_shuffle_len,xm_whistler_shuffle_data,xm_whistler_shuffle_busL,xm_whistler_shuffle_busR,71,0,1815,179};
// ---- whistler_shuffle_old  (from tools/whistler_shuffle_old.xm) ----
static const u8 xm_whistler_shuffle_old_order[71]={0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,12,18,19,20,21,20,22,23,24,25,26,
27,27,28,29,30,31,32,32,32,33,34,35,36,37,38,39,38,35,40,41,42,43,44,40,45,46,47,48,49,50,
51,52,53,54,55,55,55,55,56,56,57,
};
static const u16 xm_whistler_shuffle_old_rows[58]={48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,
48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,16,
};
static const u32 xm_whistler_shuffle_old_patOff[58]={0,62,296,546,867,1185,1503,1821,2139,2457,2775,3111,3507,3903,4299,4695,5091,5487,5883,6276,6666,7056,7446,7836,
8226,8631,8973,9315,9657,9999,10341,10683,11025,11229,11451,11844,12234,12624,13014,13404,13794,14274,14754,15234,15714,16194,16674,17169,
17553,17937,18321,18705,19089,19473,19857,20241,20475,20519,
};
static const u16 xm_whistler_shuffle_old_vt[18]={662,1687,2712,1740,1536,2611,1669,1553,639,681,1058,2628,1210,2235,2644,2765,
2782,623,
};
static const u32 xm_whistler_shuffle_old_anc[14]={61819841,247279365,247279365,247279365,247279365,247279365,247279365,247279365,
61819841,123639683,247279365,165039176,41259794,247279365,
};
static const u8 xm_whistler_shuffle_old_fx[1]={255,
};
static const u32 xm_whistler_shuffle_old_len[14]={1226,4541,1401,858,6219,2383,18304,18320,2488,13341,4092,6079,2201,11545,
};
static const s8* const xm_whistler_shuffle_old_data[14]={xm_whistler_shuffle_S0,xm_whistler_shuffle_S1,xm_whistler_shuffle_S2,xm_whistler_shuffle_old_S3,xm_whistler_shuffle_S4,xm_whistler_shuffle_S5,xm_whistler_shuffle_S6,xm_whistler_shuffle_S7,xm_whistler_shuffle_S8,xm_whistler_shuffle_S9,xm_whistler_shuffle_S10,xm_whistler_shuffle_old_S11,xm_whistler_shuffle_old_S12,xm_whistler_shuffle_S13};
static const u8 xm_whistler_shuffle_old_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_whistler_shuffle_old_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_whistler_shuffle_old={xm_whistler_shuffle_old_order,xm_whistler_shuffle_old_rows,xm_whistler_shuffle_old_patOff,xm_whistler_shuffle_old_ev,xm_whistler_shuffle_old_vt,xm_whistler_shuffle_old_anc,xm_whistler_shuffle_old_fx,xm_whistler_shuffle_old_len,xm_whistler_shuffle_old_data,xm_whistler_shuffle_old_busL,xm_whistler_shuffle_old_busR,71,0,1815,179};
// ---- cynicaller_dnb  (from tools/cynicaller_dnb.xm) ----
static const u8 xm_cynicaller_dnb_order[87]={0,1,0,1,2,3,4,3,5,6,5,7,8,9,10,9,10,9,10,9,10,9,10,9,10,9,10,11,12,13,
14,13,14,13,14,13,15,16,15,16,17,16,18,19,20,21,22,21,22,21,22,21,22,21,22,21,22,21,22,21,
23,24,25,24,25,24,26,27,28,29,30,29,30,29,30,29,30,29,30,29,31,32,31,32,33,34,35,
};
static const u16 xm_cynicaller_dnb_rows[36]={128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
128,128,128,128,128,128,
};
static const u32 xm_cynicaller_dnb_patOff[36]={0,75,150,614,1075,1536,2126,2716,3477,4154,4825,5496,6335,7075,7812,8549,8971,9393,9881,10306,10902,11639,12370,13101,
13916,14728,15540,16355,17335,18078,18815,19552,20004,20456,20524,20589,
};
static const u16 xm_cynicaller_dnb_vt[22]={679,1704,2729,1245,1536,1669,2746,1647,698,2611,1553,1739,596,2764,1058,2302,
1686,1663,580,743,1768,2793,
};
static const u32 xm_cynicaller_dnb_anc[16]={61819841,247279365,247279365,247279365,247279365,247279365,247279365,41259794,
41259794,82519588,82519588,123639683,247279365,247279365,247279365,165039176,
};
static const u8 xm_cynicaller_dnb_fx[1]={255,
};
static const u32 xm_cynicaller_dnb_len[16]={1301,4280,1214,597,5212,1080,16655,2480,2484,4976,7754,1124,8316,13325,3571,15581,
};
static const s8* const xm_cynicaller_dnb_data[16]={xm_cynicaller_dnb_S0,xm_cynicaller_dnb_S1,xm_cynicaller_dnb_S2,xm_cynicaller_dnb_S3,xm_cynicaller_dnb_S4,xm_cynicaller_dnb_S5,xm_cynicaller_dnb_S6,xm_cynicaller_dnb_S7,xm_cynicaller_dnb_S8,xm_cynicaller_dnb_S9,xm_cynicaller_dnb_S10,xm_cynicaller_dnb_S11,xm_cynicaller_dnb_S12,xm_cynicaller_dnb_S13,xm_cynicaller_dnb_S14,xm_cynicaller_dnb_S15};
static const u8 xm_cynicaller_dnb_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_cynicaller_dnb_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_cynicaller_dnb={xm_cynicaller_dnb_order,xm_cynicaller_dnb_rows,xm_cynicaller_dnb_patOff,xm_cynicaller_dnb_ev,xm_cynicaller_dnb_vt,xm_cynicaller_dnb_anc,xm_cynicaller_dnb_fx,xm_cynicaller_dnb_len,xm_cynicaller_dnb_data,xm_cynicaller_dnb_busL,xm_cynicaller_dnb_busR,87,0,394,184};
// ---- hotdamn_rave  (from tools/hotdamn_rave.xm) ----
static const u8 xm_hotdamn_rave_order[69]={0,1,2,3,4,5,6,7,8,9,10,7,8,9,11,12,13,12,14,15,16,17,18,19,20,21,19,20,22,23,
24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,
54,55,56,57,58,59,60,61,62,
};
static const u16 xm_hotdamn_rave_rows[63]={128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
128,128,128,
};
static const u32 xm_hotdamn_rave_patOff[63]={0,104,213,322,498,676,1000,1353,1685,2036,2405,2751,3142,3529,3917,4271,4614,4974,5442,5549,5658,5767,5871,6109,
6341,6869,7501,7872,8216,8601,8985,9358,9717,10123,10551,11081,11636,12101,12549,12940,13425,13764,14318,14679,15022,15382,15762,16150,
16537,16910,17269,17675,18080,18468,18957,19307,19639,19898,20162,20271,20375,20478,20566,
};
static const u16 xm_hotdamn_rave_vt[31]={1702,744,1769,2794,2781,733,2611,728,1753,2778,1058,1553,2350,1536,1207,1803,
1647,1631,1685,780,1653,1669,580,1223,2845,797,760,1785,2810,1819,796,
};
static const u32 xm_hotdamn_rave_anc[19]={61819841,247279365,247279365,247279365,247279365,165039176,82519588,123639683,
123639683,247279365,41259794,165039176,123639683,82519588,165039176,165039176,
247279365,247279365,165039176,
};
static const u8 xm_hotdamn_rave_fx[1]={255,
};
static const u32 xm_hotdamn_rave_len[19]={1231,3949,1396,688,4909,9967,4966,1638,4563,5796,2201,7686,2044,7217,17711,13227,7475,11647,15579,
};
static const s8* const xm_hotdamn_rave_data[19]={xm_hotdamn_rave_S0,xm_hotdamn_rave_S1,xm_hotdamn_rave_S2,xm_hotdamn_rave_S3,xm_hotdamn_rave_S4,xm_hotdamn_rave_S5,xm_hotdamn_rave_S6,xm_hotdamn_rave_S7,xm_hotdamn_rave_S8,xm_hotdamn_rave_S9,xm_hotdamn_rave_S10,xm_hotdamn_rave_S11,xm_hotdamn_rave_S12,xm_hotdamn_rave_S13,xm_hotdamn_rave_S14,xm_hotdamn_rave_S15,xm_hotdamn_rave_S16,xm_hotdamn_rave_S17,xm_hotdamn_rave_S18};
static const u8 xm_hotdamn_rave_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_hotdamn_rave_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_hotdamn_rave={xm_hotdamn_rave_order,xm_hotdamn_rave_rows,xm_hotdamn_rave_patOff,xm_hotdamn_rave_ev,xm_hotdamn_rave_vt,xm_hotdamn_rave_anc,xm_hotdamn_rave_fx,xm_hotdamn_rave_len,xm_hotdamn_rave_data,xm_hotdamn_rave_busL,xm_hotdamn_rave_busR,69,0,504,92};
// ---- hotdamn_rave_old  (from tools/hotdamn_rave_old.xm) ----
static const u8 xm_hotdamn_rave_old_order[64]={0,1,2,3,4,5,6,7,8,9,10,7,8,9,11,12,13,12,14,15,16,17,18,19,20,21,19,20,22,23,
24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,
54,55,56,57,
};
static const u16 xm_hotdamn_rave_old_rows[58]={128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
};
static const u32 xm_hotdamn_rave_old_patOff[58]={0,104,213,322,540,761,1125,1559,1971,2405,2851,3278,3775,4256,4750,5190,5618,6065,6617,6724,6833,6942,7046,7320,
7585,8111,8804,9261,9713,10192,10663,11144,11670,12202,12763,13490,14174,14670,15338,15878,16539,17100,17798,18263,18709,19174,19656,20168,
20667,21148,21674,22206,22744,23256,23857,23964,24073,24182,
};
static const u16 xm_hotdamn_rave_old_vt[31]={1702,744,1769,2794,2781,733,2611,728,1753,2778,1058,1553,2350,1536,1653,1207,
1803,1647,1631,1685,580,780,1669,1223,2845,797,760,1785,2810,1819,796,
};
static const u32 xm_hotdamn_rave_old_anc[19]={61819841,247279365,247279365,247279365,247279365,165039176,82519588,123639683,
123639683,247279365,41259794,165039176,123639683,82519588,165039176,165039176,
247279365,247279365,165039176,
};
static const u8 xm_hotdamn_rave_old_fx[1]={255,
};
static const u32 xm_hotdamn_rave_old_len[19]={1231,3949,1396,688,4909,9967,4966,1638,4563,5796,2201,7686,2044,7217,17711,13227,7475,11647,15579,
};
static const s8* const xm_hotdamn_rave_old_data[19]={xm_hotdamn_rave_S0,xm_hotdamn_rave_S1,xm_hotdamn_rave_S2,xm_hotdamn_rave_S3,xm_hotdamn_rave_S4,xm_hotdamn_rave_S5,xm_hotdamn_rave_S6,xm_hotdamn_rave_S7,xm_hotdamn_rave_S8,xm_hotdamn_rave_S9,xm_hotdamn_rave_S10,xm_hotdamn_rave_S11,xm_hotdamn_rave_S12,xm_hotdamn_rave_S13,xm_hotdamn_rave_S14,xm_hotdamn_rave_S15,xm_hotdamn_rave_S16,xm_hotdamn_rave_S17,xm_hotdamn_rave_S18};
static const u8 xm_hotdamn_rave_old_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_hotdamn_rave_old_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_hotdamn_rave_old={xm_hotdamn_rave_old_order,xm_hotdamn_rave_old_rows,xm_hotdamn_rave_old_patOff,xm_hotdamn_rave_old_ev,xm_hotdamn_rave_old_vt,xm_hotdamn_rave_old_anc,xm_hotdamn_rave_old_fx,xm_hotdamn_rave_old_len,xm_hotdamn_rave_old_data,xm_hotdamn_rave_old_busL,xm_hotdamn_rave_old_busR,64,0,504,92};
// ---- aim_and_shoot  (from tools/aim_and_shoot.xm) ----
static const u8 xm_aim_and_shoot_order[29]={0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
};
static const u16 xm_aim_and_shoot_rows[29]={128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,
};
static const u32 xm_aim_and_shoot_patOff[29]={0,115,288,508,917,1250,1645,1993,2384,2825,3291,3747,4218,4725,5244,5810,6381,6582,6809,7292,7809,8307,8856,9426,
10023,10616,11177,11391,11534,
};
static const u16 xm_aim_and_shoot_vt[22]={612,1190,1663,596,1685,728,1753,2778,766,1536,1058,2231,2627,1074,1553,1679,
1739,2215,2749,782,2284,1568,
};
static const u32 xm_aim_and_shoot_anc[17]={61819841,247279365,61819841,247279365,247279365,61819841,61819841,165039176,
165039176,41259794,247279365,247279365,82519588,165039176,165039176,123639683,
41259794,
};
static const u8 xm_aim_and_shoot_fx[1]={255,
};
static const u32 xm_aim_and_shoot_len[17]={1649,4936,1435,1867,2884,1223,1231,13357,11085,2211,14903,11564,6645,17735,11038,7480,2758,
};
static const s8* const xm_aim_and_shoot_data[17]={xm_aim_and_shoot_S0,xm_aim_and_shoot_S1,xm_aim_and_shoot_S2,xm_aim_and_shoot_S3,xm_aim_and_shoot_S4,xm_aim_and_shoot_S5,xm_aim_and_shoot_S6,xm_aim_and_shoot_S7,xm_aim_and_shoot_S8,xm_aim_and_shoot_S9,xm_aim_and_shoot_S10,xm_aim_and_shoot_S11,xm_aim_and_shoot_S12,xm_aim_and_shoot_S13,xm_aim_and_shoot_S14,xm_aim_and_shoot_S15,xm_aim_and_shoot_S16};
static const u8 xm_aim_and_shoot_busL[7]={199,179,152,122,88,51,13,
};
static const u8 xm_aim_and_shoot_busR[7]={13,51,88,122,152,179,199,
};
static const XmSong xm_aim_and_shoot={xm_aim_and_shoot_order,xm_aim_and_shoot_rows,xm_aim_and_shoot_patOff,xm_aim_and_shoot_ev,xm_aim_and_shoot_vt,xm_aim_and_shoot_anc,xm_aim_and_shoot_fx,xm_aim_and_shoot_len,xm_aim_and_shoot_data,xm_aim_and_shoot_busL,xm_aim_and_shoot_busR,29,0,840,154};
