// rampdata.h - GENERATED by tools/make_skate_items.py. Surface heights (px) that match the ramp sprites, used by ramps.h.
static const u8 qpH[8]={1,1,2,3,5,7,10,14};   // quarter pipe, per eighth of the tile from the low edge to the lip
#define KICKER_H 8   // kicker height at the lip
#define LAUNCH_H 12   // launch ramp height at the lip (pack 2)
