// sfxtakes.h - GENERATED by tools/chop_sfx.py (do not edit by hand): the takes cut out of the long recordings in tools/sfx_src.
// Each is source/sfx/x_<take>.adp (4-bit IMA-ADPCM, 6554 Hz). TK_<EFFECT> lists the take(s) an effect plays (main.c sfxTab / sfxPlay);
// an effect with several cycles through them. To change which take an effect plays, edit ROLES in tools/chop_sfx.py and run it again.
#ifndef SFXTAKES_H
#define SFXTAKES_H
#define TAKE_LIST(X) \
    X(hit1) \
    X(hit2) \
    X(hit4) \
    X(hit5) \
    X(scr3) \
    X(scr6) \
    X(scr1) \
    X(ins3) \
    X(cry5) \
    X(grn1) \
    X(scr7) \
    X(cry6) \
    X(grn7) \
    X(scr5)
#define TK_ASM(n) ".global x_" #n "\nx_" #n ":\n.incbin \"source/sfx/x_" #n ".adp\"\n.balign 4\n"
__asm__(".pushsection .rodata\n.balign 4\n" TAKE_LIST(TK_ASM) ".popsection\n");
#define TK_EXT(n) extern const u8 x_##n[];
TAKE_LIST(TK_EXT)
#define TK_BONK x_hit1
#define TK_BONK_N 1
#define TK_BONK_FIRST x_hit1
#define TK_HIT x_hit1,x_hit2,x_hit4,x_hit5
#define TK_HIT_N 4
#define TK_HIT_FIRST x_hit1
#define TK_SCREAM x_scr3
#define TK_SCREAM_N 1
#define TK_SCREAM_FIRST x_scr3
#define TK_NEARLY x_scr6
#define TK_NEARLY_N 1
#define TK_NEARLY_FIRST x_scr6
#define TK_DEATH x_scr1
#define TK_DEATH_N 1
#define TK_DEATH_FIRST x_scr1
#define TK_INSTANT x_ins3
#define TK_INSTANT_N 1
#define TK_INSTANT_FIRST x_ins3
#define TK_CRY x_cry5
#define TK_CRY_N 1
#define TK_CRY_FIRST x_cry5
#define TK_GROAN x_grn1
#define TK_GROAN_N 1
#define TK_GROAN_FIRST x_grn1
#define TK_YELP x_scr7,x_cry6,x_grn7
#define TK_YELP_N 3
#define TK_YELP_FIRST x_scr7
#define TK_KO x_scr5
#define TK_KO_N 1
#define TK_KO_FIRST x_scr5
#endif
