// skateart.h - GENERATED by tools/make_skate_items.py (edit the art there, then re-run). Included by itembake.h (host-only; the baked result is source/itemrom.h).
// Kicker ramp, quarter pipe, ledge, bench and the v2 grind rail, in the same textured-box model as items.h.
static const u16 pKi[5]={RGB(7,4,2),RGB(24,17,9),RGB(20,13,6),RGB(28,21,12),RGB(12,7,3)};
static const u16 pKiR[5]={RGB(9,5,2),RGB(31,22,12),RGB(26,17,8),RGB(31,28,16),RGB(16,9,4)};
static const u16 pQp[7]={RGB(6,4,3),RGB(22,15,8),RGB(17,11,5),RGB(27,19,11),RGB(11,7,3),RGB(21,22,25),RGB(30,30,31)};
static const u16 pQpR[7]={RGB(8,5,4),RGB(29,20,10),RGB(22,14,6),RGB(31,25,14),RGB(14,9,4),RGB(28,29,31),RGB(31,31,31)};
static const u16 pLe[5]={RGB(6,6,8),RGB(16,16,18),RGB(12,12,14),RGB(27,28,30),RGB(21,22,25)};
static const u16 pBe[5]={RGB(6,4,2),RGB(25,18,9),RGB(13,8,4),RGB(18,19,23),RGB(29,22,12)};
static const u16 pRl[5]={RGB(7,7,10),RGB(19,20,24),RGB(29,30,31),RGB(30,26,5),RGB(12,12,15)};
static const u16 pLa[5]={RGB(3,5,10),RGB(8,14,24),RGB(14,22,31),RGB(24,29,31),RGB(5,9,17)};
static const u16 pLaR[5]={RGB(4,6,13),RGB(10,18,31),RGB(18,29,31),RGB(31,31,31),RGB(6,12,22)};
static const u16 pFb[6]={RGB(5,5,9),RGB(14,13,20),RGB(20,18,27),RGB(28,26,31),RGB(10,9,15),RGB(31,27,6)};
static const u16 pBa[5]={RGB(8,2,2),RGB(24,6,5),RGB(30,12,9),RGB(14,3,3),RGB(31,24,20)};
static const u16 pTr[5]={RGB(3,5,4),RGB(12,18,14),RGB(17,24,19),RGB(22,28,24),RGB(7,11,8)};
static const u16 pPl[8]={RGB(6,3,2),RGB(20,10,6),RGB(26,15,9),RGB(14,7,4),RGB(9,6,3),RGB(8,22,6),RGB(14,28,9),RGB(30,10,16)};
static const u16 pPt[5]={RGB(6,4,2),RGB(25,18,9),RGB(18,12,6),RGB(29,22,12),RGB(13,8,4)};
static const u16 pJe[7]={RGB(6,6,8),RGB(17,17,19),RGB(22,22,24),RGB(27,28,30),RGB(12,12,14),RGB(27,6,5),RGB(30,30,30)};
static const u16 pPd[5]={RGB(6,6,8),RGB(16,16,18),RGB(21,22,25),RGB(30,26,5),RGB(24,20,3)};
MAT(mKiT0,pKi,8,1,"cccccccc")
MAT(mKiR0,pKiR,1,1,"c")
MAT(mKiS0,pKi,1,1,"e")
MAT(mKiT1,pKi,8,1,"bbbbbbbb")
MAT(mKiR1,pKiR,1,1,"b")
MAT(mKiS1,pKi,1,1,"e")
MAT(mKiT2,pKi,8,1,"bbbbbbbb")
MAT(mKiR2,pKiR,1,1,"b")
MAT(mKiS2,pKi,1,1,"e")
MAT(mKiT3,pKi,8,1,"cccccccc")
MAT(mKiR3,pKiR,1,1,"c")
MAT(mKiS3,pKi,1,1,"e")
MAT(mKiT4,pKi,8,1,"bbbbbbbb")
MAT(mKiR4,pKiR,1,1,"b")
MAT(mKiS4,pKi,1,1,"e")
MAT(mKiT5,pKi,8,1,"bbbbbbbb")
MAT(mKiR5,pKiR,1,1,"b")
MAT(mKiS5,pKi,1,1,"e")
MAT(mKiT6,pKi,8,1,"cccccccc")
MAT(mKiR6,pKiR,1,1,"c")
MAT(mKiS6,pKi,1,1,"e")
MAT(mKiT7,pKi,8,1,"bbbbbbbb")
MAT(mKiR7,pKiR,1,1,"b")
MAT(mKiS7,pKi,1,1,"e")
MAT(mQpT0,pQp,8,1,"ffffffff")
MAT(mQpR0,pQpR,1,14,"g","f","b","b","c","b","b","b","c","b","b","b","b","b")
MAT(mQpS0,pQp,1,1,"e")
MAT(mQpT1,pQp,8,1,"bbbbbbbb")
MAT(mQpR1,pQpR,1,1,"b")
MAT(mQpS1,pQp,1,1,"e")
MAT(mQpT2,pQp,8,1,"cccccccc")
MAT(mQpR2,pQpR,1,1,"c")
MAT(mQpS2,pQp,1,1,"e")
MAT(mQpT3,pQp,8,1,"bbbbbbbb")
MAT(mQpR3,pQpR,1,1,"b")
MAT(mQpS3,pQp,1,1,"e")
MAT(mQpT4,pQp,8,1,"cccccccc")
MAT(mQpR4,pQpR,1,1,"c")
MAT(mQpS4,pQp,1,1,"e")
MAT(mQpT5,pQp,8,1,"bbbbbbbb")
MAT(mQpR5,pQpR,1,1,"b")
MAT(mQpS5,pQp,1,1,"e")
MAT(mQpT6,pQp,8,1,"cccccccc")
MAT(mQpR6,pQpR,1,1,"c")
MAT(mQpS6,pQp,1,1,"e")
MAT(mQpT7,pQp,8,1,"bbbbbbbb")
MAT(mQpR7,pQpR,1,1,"b")
MAT(mQpS7,pQp,1,1,"e")
MAT(mLeSide,pLe,8,9,"eeeeeeee","bbbbbbbb","bbbcbbbb","bbbbbbbb","bcbbbbbb","bbbbbbbb","bbbbcbbb","bbbbbbbb","bbbbbbbb")
MAT(mLeTopU,pLe,8,8,"dddddddd","bbbbbbbb","bbcbbbbb","bbbbbbcb","bcbbbbbb","bbbbbbbb","bbbcbbbb","dddddddd")
MAT(mLeTopV,pLe,8,8,"dbbbbbbd","dbbcbbbd","dbbbbcbd","dcbbbbbd","dbbbbbbd","dbbbcbbd","dbbbbbbd","dbcbbbbd")
MAT(mBeLeg,pBe,1,1,"d")
MAT(mBeEdge,pBe,8,2,"bbbbbbbb","cccccccc")
MAT(mBeTopU,pBe,8,4,"bbbbbbbb","bbbbbbbb","cccccccc","bbbbbbbb")
MAT(mBeTopV,pBe,4,8,"bbcb","bbcb","bbcb","bbcb","bbcb","bbcb","bbcb","bbcb")
MAT(mRlPlate,pRl,1,1,"e")
MAT(mRlPost,pRl,1,1,"a")
MAT(mRlLong,pRl,8,2,"cccccccc","bbbbbbbb")
MAT(mRlShort,pRl,2,2,"cc","bb")
MAT(mRlTopL,pRl,8,2,"cccccccc","cdcdcdcd")
MAT(mRlLongV,pRl,8,2,"cccccccc","bbbbbbbb")
MAT(mRlShortV,pRl,2,2,"cc","bb")
MAT(mRlTopS,pRl,2,8,"cc","cd","cc","cd","cc","cd","cc","cd")
MAT(mLaT0,pLa,8,1,"bbbddbbb")
MAT(mLaR0,pLaR,1,1,"c")
MAT(mLaS0,pLa,1,1,"e")
MAT(mLaT1,pLa,8,1,"bbbddbbb")
MAT(mLaR1,pLaR,1,1,"b")
MAT(mLaS1,pLa,1,1,"e")
MAT(mLaT2,pLa,8,1,"bbbddbbb")
MAT(mLaR2,pLaR,1,1,"b")
MAT(mLaS2,pLa,1,1,"e")
MAT(mLaT3,pLa,8,1,"bbbddbbb")
MAT(mLaR3,pLaR,1,1,"c")
MAT(mLaS3,pLa,1,1,"e")
MAT(mLaT4,pLa,8,1,"bbbddbbb")
MAT(mLaR4,pLaR,1,1,"b")
MAT(mLaS4,pLa,1,1,"e")
MAT(mLaT5,pLa,8,1,"bbbddbbb")
MAT(mLaR5,pLaR,1,1,"b")
MAT(mLaS5,pLa,1,1,"e")
MAT(mLaT6,pLa,8,1,"bbbddbbb")
MAT(mLaR6,pLaR,1,1,"c")
MAT(mLaS6,pLa,1,1,"e")
MAT(mLaT7,pLa,8,1,"bbbddbbb")
MAT(mLaR7,pLaR,1,1,"b")
MAT(mLaS7,pLa,1,1,"e")
MAT(mFbSide,pFb,8,14,"dddddddd","eeeeeeee","bbbbbbbb","bbcbbbbb","bbbbbbbb","ffffffff","ffffffff","bbbbbbbb","bbbbcbbb","bbbbbbbb","bbcbbbbb","bbbbbbbb","bbbbbbbb","eeeeeeee")
MAT(mFbTop,pFb,8,8,"dddddddd","dbbbbbbd","dbbcbbbd","dbbbbbcd","dbcbbbbd","dbbbbbbd","dbbbcbbd","dddddddd")
MAT(mBaSide,pBa,8,13,"bbcbbbbb","dddddddd","bbcbbbbb","bbcbbbbb","bbcbbbbb","bbcbbbbb","dddddddd","bbcbbbbb","bbcbbbbb","bbcbbbbb","bbcbbbbb","dddddddd","bbcbbbbb")
MAT(mBaTop,pBa,6,6,"dddddd","dbbbbd","dbeebd","dbeebd","dbbbbd","dddddd")
MAT(mTrBody,pTr,8,13,"bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc","bcbcbcbc")
MAT(mTrLidS,pTr,1,1,"d")
MAT(mTrLidT,pTr,8,8,"dddddddd","dcccccdd","dcdddcdd","dcccccdd","dddddddd","dcccccdd","dcdddcdd","dddddddd")
MAT(mPlSide,pPl,8,9,"cbbbcbbb","dddddddd","bbcbbbcb","dddddddd","cbbbcbbb","dddddddd","bbcbbbcb","dddddddd","cbbbcbbb")
MAT(mPlTop,pPl,8,8,"cccccccc","cefeefec","cffefeec","cefhfefc","cfeefhec","cefefeec","cfehefec","cccccccc")
MAT(mPtLeg,pPt,1,1,"e")
MAT(mPtSeatE,pPt,8,1,"bbbbbbbb")
MAT(mPtSeatT,pPt,8,2,"bbbbbbbb","bbcbbbbb")
MAT(mPtTopE,pPt,8,2,"dddddddd","cccccccc")
MAT(mPtTopT,pPt,8,6,"dddddddd","cccccccc","dddddddd","cccccccc","dddddddd","cccccccc")
MAT(mJeBase,pJe,8,2,"bbbbbbbb","eeeeeeee")
MAT(mJeMid,pJe,8,2,"cccccccc","bbbbbbbb")
MAT(mJeStripe,pJe,8,2,"ffggffgg","ggffggff")
MAT(mJeTopU,pJe,4,8,"dddd","dddd","dddd","dddd","dddd","dddd","dddd","dddd")
MAT(mJeTopV,pJe,8,4,"dddddddd","dddddddd","dddddddd","dddddddd")
MAT(mPdSide,pPd,3,3,"bbb","cccccccc","bbbbbbbb")
MAT(mPdTop,pPd,8,8,"dddddddd","dbbbbbbd","dbcbbbcd","dbbcbcbd","dbbbcbbd","dbbcbcbd","dbcbbbcd","dddddddd")
MAT(mKiG0T0,pKi,8,1,"cccccccc")
MAT(mKiG0R0,pKiR,1,1,"c")
MAT(mKiG0S0,pKi,1,1,"e")
MAT(mKiG0T1,pKi,8,1,"bbbbbbbb")
MAT(mKiG0R1,pKiR,1,1,"b")
MAT(mKiG0S1,pKi,1,1,"e")
MAT(mKiG0T2,pKi,8,1,"bbbbbbbb")
MAT(mKiG0R2,pKiR,1,1,"b")
MAT(mKiG0S2,pKi,1,1,"e")
MAT(mKiG0T3,pKi,8,1,"cccccccc")
MAT(mKiG0R3,pKiR,1,1,"c")
MAT(mKiG0S3,pKi,1,1,"e")
MAT(mKiG0T4,pKi,8,1,"bbbbbbbb")
MAT(mKiG0R4,pKiR,1,1,"b")
MAT(mKiG0S4,pKi,1,1,"e")
MAT(mKiG0T5,pKi,8,1,"bbbbbbbb")
MAT(mKiG0R5,pKiR,1,1,"b")
MAT(mKiG0S5,pKi,1,1,"e")
MAT(mKiG0T6,pKi,8,1,"cccccccc")
MAT(mKiG0R6,pKiR,1,1,"c")
MAT(mKiG0S6,pKi,1,1,"e")
MAT(mKiG0T7,pKi,8,1,"bbbbbbbb")
MAT(mKiG0R7,pKiR,1,1,"b")
MAT(mKiG0S7,pKi,1,1,"e")
MAT(mKiG1T0,pKi,8,1,"cccccccc")
MAT(mKiG1R0,pKiR,1,1,"c")
MAT(mKiG1S0,pKi,1,1,"e")
MAT(mKiG1T1,pKi,8,1,"bbbbbbbb")
MAT(mKiG1R1,pKiR,1,1,"b")
MAT(mKiG1S1,pKi,1,1,"e")
MAT(mKiG1T2,pKi,8,1,"bbbbbbbb")
MAT(mKiG1R2,pKiR,1,1,"b")
MAT(mKiG1S2,pKi,1,1,"e")
MAT(mKiG1T3,pKi,8,1,"cccccccc")
MAT(mKiG1R3,pKiR,1,1,"c")
MAT(mKiG1S3,pKi,1,1,"e")
MAT(mKiG1T4,pKi,8,1,"bbbbbbbb")
MAT(mKiG1R4,pKiR,1,1,"b")
MAT(mKiG1S4,pKi,1,1,"e")
MAT(mKiG1T5,pKi,8,1,"bbbbbbbb")
MAT(mKiG1R5,pKiR,1,1,"b")
MAT(mKiG1S5,pKi,1,1,"e")
MAT(mKiG1T6,pKi,8,1,"cccccccc")
MAT(mKiG1R6,pKiR,1,1,"c")
MAT(mKiG1S6,pKi,1,1,"e")
MAT(mKiG1T7,pKi,8,1,"bbbbbbbb")
MAT(mKiG1R7,pKiR,1,1,"b")
MAT(mKiG1S7,pKi,1,1,"e")
MAT(mKiG2T0,pKi,8,1,"cccccccc")
MAT(mKiG2R0,pKiR,1,1,"c")
MAT(mKiG2S0,pKi,1,1,"e")
MAT(mKiG2T1,pKi,8,1,"bbbbbbbb")
MAT(mKiG2R1,pKiR,1,1,"b")
MAT(mKiG2S1,pKi,1,1,"e")
MAT(mKiG2T2,pKi,8,1,"bbbbbbbb")
MAT(mKiG2R2,pKiR,1,1,"b")
MAT(mKiG2S2,pKi,1,1,"e")
MAT(mKiG2T3,pKi,8,1,"cccccccc")
MAT(mKiG2R3,pKiR,1,1,"c")
MAT(mKiG2S3,pKi,1,1,"e")
MAT(mKiG2T4,pKi,8,1,"bbbbbbbb")
MAT(mKiG2R4,pKiR,1,1,"b")
MAT(mKiG2S4,pKi,1,1,"e")
MAT(mKiG2T5,pKi,8,1,"bbbbbbbb")
MAT(mKiG2R5,pKiR,1,1,"b")
MAT(mKiG2S5,pKi,1,1,"e")
MAT(mKiG2T6,pKi,8,1,"cccccccc")
MAT(mKiG2R6,pKiR,1,1,"c")
MAT(mKiG2S6,pKi,1,1,"e")
MAT(mKiG2T7,pKi,8,1,"bbbbbbbb")
MAT(mKiG2R7,pKiR,1,1,"b")
MAT(mKiG2S7,pKi,1,1,"e")
MAT(mKiG3T0,pKi,8,1,"cccccccc")
MAT(mKiG3R0,pKiR,1,1,"c")
MAT(mKiG3S0,pKi,1,1,"e")
MAT(mKiG3T1,pKi,8,1,"bbbbbbbb")
MAT(mKiG3R1,pKiR,1,1,"b")
MAT(mKiG3S1,pKi,1,1,"e")
MAT(mKiG3T2,pKi,8,1,"bbbbbbbb")
MAT(mKiG3R2,pKiR,1,1,"b")
MAT(mKiG3S2,pKi,1,1,"e")
MAT(mKiG3T3,pKi,8,1,"cccccccc")
MAT(mKiG3R3,pKiR,1,1,"c")
MAT(mKiG3S3,pKi,1,1,"e")
MAT(mKiG3T4,pKi,8,1,"bbbbbbbb")
MAT(mKiG3R4,pKiR,1,1,"b")
MAT(mKiG3S4,pKi,1,1,"e")
MAT(mKiG3T5,pKi,8,1,"bbbbbbbb")
MAT(mKiG3R5,pKiR,1,1,"b")
MAT(mKiG3S5,pKi,1,1,"e")
MAT(mKiG3T6,pKi,8,1,"cccccccc")
MAT(mKiG3R6,pKiR,1,1,"c")
MAT(mKiG3S6,pKi,1,1,"e")
MAT(mKiG3T7,pKi,8,1,"bbbbbbbb")
MAT(mKiG3R7,pKiR,1,1,"b")
MAT(mKiG3S7,pKi,1,1,"e")
MAT(mLaG0T0,pLa,8,1,"bbbddbbb")
MAT(mLaG0R0,pLaR,1,1,"c")
MAT(mLaG0S0,pLa,1,1,"e")
MAT(mLaG0T1,pLa,8,1,"bbbddbbb")
MAT(mLaG0R1,pLaR,1,1,"b")
MAT(mLaG0S1,pLa,1,1,"e")
MAT(mLaG0T2,pLa,8,1,"bbbddbbb")
MAT(mLaG0R2,pLaR,1,1,"b")
MAT(mLaG0S2,pLa,1,1,"e")
MAT(mLaG0T3,pLa,8,1,"bbbddbbb")
MAT(mLaG0R3,pLaR,1,1,"c")
MAT(mLaG0S3,pLa,1,1,"e")
MAT(mLaG0T4,pLa,8,1,"bbbddbbb")
MAT(mLaG0R4,pLaR,1,1,"b")
MAT(mLaG0S4,pLa,1,1,"e")
MAT(mLaG0T5,pLa,8,1,"bbbddbbb")
MAT(mLaG0R5,pLaR,1,1,"b")
MAT(mLaG0S5,pLa,1,1,"e")
MAT(mLaG0T6,pLa,8,1,"bbbddbbb")
MAT(mLaG0R6,pLaR,1,1,"c")
MAT(mLaG0S6,pLa,1,1,"e")
MAT(mLaG0T7,pLa,8,1,"bbbddbbb")
MAT(mLaG0R7,pLaR,1,1,"b")
MAT(mLaG0S7,pLa,1,1,"e")
MAT(mLaG1T0,pLa,8,1,"bbbddbbb")
MAT(mLaG1R0,pLaR,1,1,"c")
MAT(mLaG1S0,pLa,1,1,"e")
MAT(mLaG1T1,pLa,8,1,"bbbddbbb")
MAT(mLaG1R1,pLaR,1,1,"b")
MAT(mLaG1S1,pLa,1,1,"e")
MAT(mLaG1T2,pLa,8,1,"bbbddbbb")
MAT(mLaG1R2,pLaR,1,1,"b")
MAT(mLaG1S2,pLa,1,1,"e")
MAT(mLaG1T3,pLa,8,1,"bbbddbbb")
MAT(mLaG1R3,pLaR,1,1,"c")
MAT(mLaG1S3,pLa,1,1,"e")
MAT(mLaG1T4,pLa,8,1,"bbbddbbb")
MAT(mLaG1R4,pLaR,1,1,"b")
MAT(mLaG1S4,pLa,1,1,"e")
MAT(mLaG1T5,pLa,8,1,"bbbddbbb")
MAT(mLaG1R5,pLaR,1,1,"b")
MAT(mLaG1S5,pLa,1,1,"e")
MAT(mLaG1T6,pLa,8,1,"bbbddbbb")
MAT(mLaG1R6,pLaR,1,1,"c")
MAT(mLaG1S6,pLa,1,1,"e")
MAT(mLaG1T7,pLa,8,1,"bbbddbbb")
MAT(mLaG1R7,pLaR,1,1,"b")
MAT(mLaG1S7,pLa,1,1,"e")
MAT(mLaG2T0,pLa,8,1,"bbbddbbb")
MAT(mLaG2R0,pLaR,1,1,"c")
MAT(mLaG2S0,pLa,1,1,"e")
MAT(mLaG2T1,pLa,8,1,"bbbddbbb")
MAT(mLaG2R1,pLaR,1,1,"b")
MAT(mLaG2S1,pLa,1,1,"e")
MAT(mLaG2T2,pLa,8,1,"bbbddbbb")
MAT(mLaG2R2,pLaR,1,1,"b")
MAT(mLaG2S2,pLa,1,1,"e")
MAT(mLaG2T3,pLa,8,1,"bbbddbbb")
MAT(mLaG2R3,pLaR,1,1,"c")
MAT(mLaG2S3,pLa,1,1,"e")
MAT(mLaG2T4,pLa,8,1,"bbbddbbb")
MAT(mLaG2R4,pLaR,1,1,"b")
MAT(mLaG2S4,pLa,1,1,"e")
MAT(mLaG2T5,pLa,8,1,"bbbddbbb")
MAT(mLaG2R5,pLaR,1,1,"b")
MAT(mLaG2S5,pLa,1,1,"e")
MAT(mLaG2T6,pLa,8,1,"bbbddbbb")
MAT(mLaG2R6,pLaR,1,1,"c")
MAT(mLaG2S6,pLa,1,1,"e")
MAT(mLaG2T7,pLa,8,1,"bbbddbbb")
MAT(mLaG2R7,pLaR,1,1,"b")
MAT(mLaG2S7,pLa,1,1,"e")
static const IBox bxKicker[8]={ // wedge, 12 px lip
 {0,0,8,1,0,12,{&mKiR0,&mKiS0,&mKiS0,&mKiS0,&mKiT0}},
 {0,1,8,2,0,11,{&mKiR1,&mKiS1,&mKiS1,&mKiS1,&mKiT1}},
 {0,2,8,3,0,9,{&mKiR2,&mKiS2,&mKiS2,&mKiS2,&mKiT2}},
 {0,3,8,4,0,8,{&mKiR3,&mKiS3,&mKiS3,&mKiS3,&mKiT3}},
 {0,4,8,5,0,6,{&mKiR4,&mKiS4,&mKiS4,&mKiS4,&mKiT4}},
 {0,5,8,6,0,5,{&mKiR5,&mKiS5,&mKiS5,&mKiS5,&mKiT5}},
 {0,6,8,7,0,3,{&mKiR6,&mKiS6,&mKiS6,&mKiS6,&mKiT6}},
 {0,7,8,8,0,2,{&mKiR7,&mKiS7,&mKiS7,&mKiS7,&mKiT7}} };
static const IBox bxQuarterPipe[8]={ // concave, 24 px
 {0,0,8,1,0,24,{&mQpR0,&mQpS0,&mQpS0,&mQpS0,&mQpT0}},
 {0,1,8,2,0,17,{&mQpR1,&mQpS1,&mQpS1,&mQpS1,&mQpT1}},
 {0,2,8,3,0,12,{&mQpR2,&mQpS2,&mQpS2,&mQpS2,&mQpT2}},
 {0,3,8,4,0,9,{&mQpR3,&mQpS3,&mQpS3,&mQpS3,&mQpT3}},
 {0,4,8,5,0,5,{&mQpR4,&mQpS4,&mQpS4,&mQpS4,&mQpT4}},
 {0,5,8,6,0,3,{&mQpR5,&mQpS5,&mQpS5,&mQpS5,&mQpT5}},
 {0,6,8,7,0,2,{&mQpR6,&mQpS6,&mQpS6,&mQpS6,&mQpT6}},
 {0,7,8,8,0,1,{&mQpR7,&mQpS7,&mQpS7,&mQpS7,&mQpT7}} };
static const IBox bxLedgeU[1]={ // grind ledge, runs along a
 {0,0,8,8,0,9,{&mLeSide,&mLeSide,&mLeSide,&mLeSide,&mLeTopU}} };
static const IBox bxLedgeV[1]={ // grind ledge, runs along b
 {0,0,8,8,0,9,{&mLeSide,&mLeSide,&mLeSide,&mLeSide,&mLeTopV}} };
static const IBox bxBenchU[3]={ // bench, runs along a
 {1,2,2,6,0,7,{&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg}},
 {6,2,7,6,0,7,{&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg}},
 {0,2,8,6,7,9,{&mBeEdge,&mBeEdge,&mBeEdge,&mBeEdge,&mBeTopU}} };
static const IBox bxBenchV[3]={ // bench, runs along b
 {2,1,6,2,0,7,{&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg}},
 {2,6,6,7,0,7,{&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg,&mBeLeg}},
 {2,0,6,8,7,9,{&mBeEdge,&mBeEdge,&mBeEdge,&mBeEdge,&mBeTopV}} };
static const IBox bxRailU[3]={ // grind rail along a
 {2,2,6,6,0,1,{&mRlPlate,&mRlPlate,&mRlPlate,&mRlPlate,&mRlPlate}},
 {3,3,5,5,1,7,{&mRlPost,&mRlPost,&mRlPost,&mRlPost,&mRlPost}},
 {0,3,8,5,7,9,{&mRlLong,&mRlShort,&mRlLong,&mRlShort,&mRlTopL}} };
static const IBox bxRailV[3]={ // grind rail along b
 {2,2,6,6,0,1,{&mRlPlate,&mRlPlate,&mRlPlate,&mRlPlate,&mRlPlate}},
 {3,3,5,5,1,7,{&mRlPost,&mRlPost,&mRlPost,&mRlPost,&mRlPost}},
 {3,0,5,8,7,9,{&mRlShortV,&mRlLongV,&mRlShortV,&mRlLongV,&mRlTopS}} };
static const IBox bxLaunch[8]={ // launch ramp, 18 px lip
 {0,0,8,1,0,18,{&mLaR0,&mLaS0,&mLaS0,&mLaS0,&mLaT0}},
 {0,1,8,2,0,16,{&mLaR1,&mLaS1,&mLaS1,&mLaS1,&mLaT1}},
 {0,2,8,3,0,14,{&mLaR2,&mLaS2,&mLaS2,&mLaS2,&mLaT2}},
 {0,3,8,4,0,11,{&mLaR3,&mLaS3,&mLaS3,&mLaS3,&mLaT3}},
 {0,4,8,5,0,9,{&mLaR4,&mLaS4,&mLaS4,&mLaS4,&mLaT4}},
 {0,5,8,6,0,7,{&mLaR5,&mLaS5,&mLaS5,&mLaS5,&mLaT5}},
 {0,6,8,7,0,5,{&mLaR6,&mLaS6,&mLaS6,&mLaS6,&mLaT6}},
 {0,7,8,8,0,2,{&mLaR7,&mLaS7,&mLaS7,&mLaS7,&mLaT7}} };
static const IBox bxFunbox[1]={ // platform, 14 px, solid (ollie onto it)
 {0,0,8,8,0,14,{&mFbSide,&mFbSide,&mFbSide,&mFbSide,&mFbTop}} };
static const IBox bxBarrel[1]={ // oil drum, 13 px, solid
 {1,1,7,7,0,13,{&mBaSide,&mBaSide,&mBaSide,&mBaSide,&mBaTop}} };
static const IBox bxTrashCan[2]={ // trash can, 14 px, solid
 {1,1,7,7,0,13,{&mTrBody,&mTrBody,&mTrBody,&mTrBody,&mTrBody}},
 {0,0,8,8,13,14,{&mTrLidS,&mTrLidS,&mTrLidS,&mTrLidS,&mTrLidT}} };
static const IBox bxPlanter[1]={ // planter box, grind 9 px
 {0,0,8,8,0,9,{&mPlSide,&mPlSide,&mPlSide,&mPlSide,&mPlTop}} };
static const IBox bxPicnicTable[7]={ // picnic table, grind 9 px
 {1,0,2,8,0,3,{&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg}},
 {6,0,7,8,0,3,{&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg}},
 {0,0,8,2,3,4,{&mPtSeatE,&mPtSeatE,&mPtSeatE,&mPtSeatE,&mPtSeatT}},
 {0,6,8,8,3,4,{&mPtSeatE,&mPtSeatE,&mPtSeatE,&mPtSeatE,&mPtSeatT}},
 {1,1,7,7,8,9,{&mPtTopE,&mPtTopE,&mPtTopE,&mPtTopE,&mPtTopT}},
 {2,1,3,7,4,8,{&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg}},
 {5,1,6,7,4,8,{&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg,&mPtLeg}} };
static const IBox bxJerseyU[3]={ // jersey barrier, runs along a
 {0,1,8,7,0,2,{&mJeBase,&mJeBase,&mJeBase,&mJeBase,&mJeMid}},
 {0,2,8,6,2,5,{&mJeMid,&mJeMid,&mJeMid,&mJeMid,&mJeMid}},
 {0,3,8,5,5,9,{&mJeStripe,&mJeStripe,&mJeStripe,&mJeStripe,&mJeTopU}} };
static const IBox bxJerseyV[3]={ // jersey barrier, runs along b
 {1,0,7,8,0,2,{&mJeBase,&mJeBase,&mJeBase,&mJeBase,&mJeMid}},
 {2,0,6,8,2,5,{&mJeMid,&mJeMid,&mJeMid,&mJeMid,&mJeMid}},
 {3,0,5,8,5,9,{&mJeStripe,&mJeStripe,&mJeStripe,&mJeStripe,&mJeTopV}} };
static const IBox bxManualPad[1]={ // manual pad, 3 px, rides on without a jump
 {0,0,8,8,0,3,{&mPdSide,&mPdSide,&mPdSide,&mPdSide,&mPdTop}} };
static const IBox bxKickerSeg0[8]={ // long kicker, tile 0 (0 to 8 px)
 {0,0,8,1,0,8,{&mKiG0R0,&mKiG0S0,&mKiG0S0,&mKiG0S0,&mKiG0T0}},
 {0,1,8,2,0,7,{&mKiG0R1,&mKiG0S1,&mKiG0S1,&mKiG0S1,&mKiG0T1}},
 {0,2,8,3,0,6,{&mKiG0R2,&mKiG0S2,&mKiG0S2,&mKiG0S2,&mKiG0T2}},
 {0,3,8,4,0,5,{&mKiG0R3,&mKiG0S3,&mKiG0S3,&mKiG0S3,&mKiG0T3}},
 {0,4,8,5,0,4,{&mKiG0R4,&mKiG0S4,&mKiG0S4,&mKiG0S4,&mKiG0T4}},
 {0,5,8,6,0,3,{&mKiG0R5,&mKiG0S5,&mKiG0S5,&mKiG0S5,&mKiG0T5}},
 {0,6,8,7,0,2,{&mKiG0R6,&mKiG0S6,&mKiG0S6,&mKiG0S6,&mKiG0T6}},
 {0,7,8,8,0,1,{&mKiG0R7,&mKiG0S7,&mKiG0S7,&mKiG0S7,&mKiG0T7}} };
static const IBox bxKickerSeg1[8]={ // long kicker, tile 1 (8 to 16 px)
 {0,0,8,1,0,16,{&mKiG1R0,&mKiG1S0,&mKiG1S0,&mKiG1S0,&mKiG1T0}},
 {0,1,8,2,0,15,{&mKiG1R1,&mKiG1S1,&mKiG1S1,&mKiG1S1,&mKiG1T1}},
 {0,2,8,3,0,14,{&mKiG1R2,&mKiG1S2,&mKiG1S2,&mKiG1S2,&mKiG1T2}},
 {0,3,8,4,0,13,{&mKiG1R3,&mKiG1S3,&mKiG1S3,&mKiG1S3,&mKiG1T3}},
 {0,4,8,5,0,12,{&mKiG1R4,&mKiG1S4,&mKiG1S4,&mKiG1S4,&mKiG1T4}},
 {0,5,8,6,0,11,{&mKiG1R5,&mKiG1S5,&mKiG1S5,&mKiG1S5,&mKiG1T5}},
 {0,6,8,7,0,10,{&mKiG1R6,&mKiG1S6,&mKiG1S6,&mKiG1S6,&mKiG1T6}},
 {0,7,8,8,0,9,{&mKiG1R7,&mKiG1S7,&mKiG1S7,&mKiG1S7,&mKiG1T7}} };
static const IBox bxKickerSeg2[8]={ // long kicker, tile 2 (16 to 24 px)
 {0,0,8,1,0,24,{&mKiG2R0,&mKiG2S0,&mKiG2S0,&mKiG2S0,&mKiG2T0}},
 {0,1,8,2,0,23,{&mKiG2R1,&mKiG2S1,&mKiG2S1,&mKiG2S1,&mKiG2T1}},
 {0,2,8,3,0,22,{&mKiG2R2,&mKiG2S2,&mKiG2S2,&mKiG2S2,&mKiG2T2}},
 {0,3,8,4,0,21,{&mKiG2R3,&mKiG2S3,&mKiG2S3,&mKiG2S3,&mKiG2T3}},
 {0,4,8,5,0,20,{&mKiG2R4,&mKiG2S4,&mKiG2S4,&mKiG2S4,&mKiG2T4}},
 {0,5,8,6,0,19,{&mKiG2R5,&mKiG2S5,&mKiG2S5,&mKiG2S5,&mKiG2T5}},
 {0,6,8,7,0,18,{&mKiG2R6,&mKiG2S6,&mKiG2S6,&mKiG2S6,&mKiG2T6}},
 {0,7,8,8,0,17,{&mKiG2R7,&mKiG2S7,&mKiG2S7,&mKiG2S7,&mKiG2T7}} };
static const IBox bxKickerSeg3[8]={ // long kicker, flat deck at 24 px
 {0,0,8,1,0,24,{&mKiG3R0,&mKiG3S0,&mKiG3S0,&mKiG3S0,&mKiG3T0}},
 {0,1,8,2,0,24,{&mKiG3R1,&mKiG3S1,&mKiG3S1,&mKiG3S1,&mKiG3T1}},
 {0,2,8,3,0,24,{&mKiG3R2,&mKiG3S2,&mKiG3S2,&mKiG3S2,&mKiG3T2}},
 {0,3,8,4,0,24,{&mKiG3R3,&mKiG3S3,&mKiG3S3,&mKiG3S3,&mKiG3T3}},
 {0,4,8,5,0,24,{&mKiG3R4,&mKiG3S4,&mKiG3S4,&mKiG3S4,&mKiG3T4}},
 {0,5,8,6,0,24,{&mKiG3R5,&mKiG3S5,&mKiG3S5,&mKiG3S5,&mKiG3T5}},
 {0,6,8,7,0,24,{&mKiG3R6,&mKiG3S6,&mKiG3S6,&mKiG3S6,&mKiG3T6}},
 {0,7,8,8,0,24,{&mKiG3R7,&mKiG3S7,&mKiG3S7,&mKiG3S7,&mKiG3T7}} };
static const IBox bxLaunchSeg0[8]={ // long launch ramp, tile 0 (0 to 12 px)
 {0,0,8,1,0,12,{&mLaG0R0,&mLaG0S0,&mLaG0S0,&mLaG0S0,&mLaG0T0}},
 {0,1,8,2,0,11,{&mLaG0R1,&mLaG0S1,&mLaG0S1,&mLaG0S1,&mLaG0T1}},
 {0,2,8,3,0,9,{&mLaG0R2,&mLaG0S2,&mLaG0S2,&mLaG0S2,&mLaG0T2}},
 {0,3,8,4,0,8,{&mLaG0R3,&mLaG0S3,&mLaG0S3,&mLaG0S3,&mLaG0T3}},
 {0,4,8,5,0,6,{&mLaG0R4,&mLaG0S4,&mLaG0S4,&mLaG0S4,&mLaG0T4}},
 {0,5,8,6,0,5,{&mLaG0R5,&mLaG0S5,&mLaG0S5,&mLaG0S5,&mLaG0T5}},
 {0,6,8,7,0,3,{&mLaG0R6,&mLaG0S6,&mLaG0S6,&mLaG0S6,&mLaG0T6}},
 {0,7,8,8,0,2,{&mLaG0R7,&mLaG0S7,&mLaG0S7,&mLaG0S7,&mLaG0T7}} };
static const IBox bxLaunchSeg1[8]={ // long launch ramp, tile 1 (12 to 24 px)
 {0,0,8,1,0,24,{&mLaG1R0,&mLaG1S0,&mLaG1S0,&mLaG1S0,&mLaG1T0}},
 {0,1,8,2,0,23,{&mLaG1R1,&mLaG1S1,&mLaG1S1,&mLaG1S1,&mLaG1T1}},
 {0,2,8,3,0,21,{&mLaG1R2,&mLaG1S2,&mLaG1S2,&mLaG1S2,&mLaG1T2}},
 {0,3,8,4,0,20,{&mLaG1R3,&mLaG1S3,&mLaG1S3,&mLaG1S3,&mLaG1T3}},
 {0,4,8,5,0,18,{&mLaG1R4,&mLaG1S4,&mLaG1S4,&mLaG1S4,&mLaG1T4}},
 {0,5,8,6,0,17,{&mLaG1R5,&mLaG1S5,&mLaG1S5,&mLaG1S5,&mLaG1T5}},
 {0,6,8,7,0,15,{&mLaG1R6,&mLaG1S6,&mLaG1S6,&mLaG1S6,&mLaG1T6}},
 {0,7,8,8,0,14,{&mLaG1R7,&mLaG1S7,&mLaG1S7,&mLaG1S7,&mLaG1T7}} };
static const IBox bxLaunchSeg2[8]={ // long launch ramp, flat deck at 24 px
 {0,0,8,1,0,24,{&mLaG2R0,&mLaG2S0,&mLaG2S0,&mLaG2S0,&mLaG2T0}},
 {0,1,8,2,0,24,{&mLaG2R1,&mLaG2S1,&mLaG2S1,&mLaG2S1,&mLaG2T1}},
 {0,2,8,3,0,24,{&mLaG2R2,&mLaG2S2,&mLaG2S2,&mLaG2S2,&mLaG2T2}},
 {0,3,8,4,0,24,{&mLaG2R3,&mLaG2S3,&mLaG2S3,&mLaG2S3,&mLaG2T3}},
 {0,4,8,5,0,24,{&mLaG2R4,&mLaG2S4,&mLaG2S4,&mLaG2S4,&mLaG2T4}},
 {0,5,8,6,0,24,{&mLaG2R5,&mLaG2S5,&mLaG2S5,&mLaG2S5,&mLaG2T5}},
 {0,6,8,7,0,24,{&mLaG2R6,&mLaG2S6,&mLaG2S6,&mLaG2S6,&mLaG2T6}},
 {0,7,8,8,0,24,{&mLaG2R7,&mLaG2S7,&mLaG2S7,&mLaG2S7,&mLaG2T7}} };
