// voices.h - GENERATED by tools/encode_voices.py (do not edit by hand): the 43 voice clips of the Sim you control.
// Each is source/sfx/v_<name>.adp (4-bit IMA-ADPCM, 6554 Hz, the same blobs the effect voice already plays), baked into the ROM here.
// They sit after the old effects in sfxTab: sound id = SFX_VOICE0 + V_<name>. Play one with voxPlay(V_<name>) (main.c); who plays what is in voxEvent
// (sims events) and voxSoc (house.h, socials), plus a few spots in main.c (falls, bails, fights, needs).
#ifndef VOICES_H
#define VOICES_H
#define VOICE_LIST(X) \
    X(needs_something) \
    X(after_smoke_cough) \
    X(after_smoke_cough_2) \
    X(agree) \
    X(amgry) \
    X(angered) \
    X(burst_crying) \
    X(cry) \
    X(cry_after_bad_advent_2) \
    X(cry_after_bad_event) \
    X(death_of_hunger) \
    X(die_of_shock) \
    X(disagree) \
    X(finished) \
    X(flirt) \
    X(flirt_2) \
    X(hey_i_need_something_h) \
    X(im_hungryrururyry) \
    X(joke_good) \
    X(joke_not_land) \
    X(laughing) \
    X(laughing_2) \
    X(laughing_small_or_not) \
    X(lets_fight) \
    X(lighter_spark) \
    X(losing_the_fight) \
    X(lost_the_fight) \
    X(nah) \
    X(naughty_joke) \
    X(naughty_jokw_2) \
    X(need_to_pee) \
    X(not_agree) \
    X(peed_self) \
    X(reading_or_thinking) \
    X(serenade_bad) \
    X(serenade_good) \
    X(shriek) \
    X(sniiize_2) \
    X(snoore) \
    X(spark_inhale) \
    X(win_the_fight) \
    X(yahoo) \
    X(yeha)
#define VX_ASM(n) ".global v_" #n "\nv_" #n ":\n.incbin \"source/sfx/v_" #n ".adp\"\n.balign 4\n"
__asm__(".pushsection .rodata\n.balign 4\n" VOICE_LIST(VX_ASM) ".popsection\n");
#define VX_EXT(n) extern const u8 v_##n[];
VOICE_LIST(VX_EXT)
#define VX_ENUM(n) V_##n,
enum { VOICE_LIST(VX_ENUM) VOICE_N };
#define VX_TAB(n) v_##n,
#define VOICE_TAB VOICE_LIST(VX_TAB)
static signed char vxQ[2]; static int vxQn;   // clips waiting for the current one to end (voxChain)
#endif
