      - name: Build
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITARM=/opt/devkitpro/devkitARM
          export PATH=$DEVKITARM/bin:$DEVKITPRO/tools/bin:$PATH
          make
